ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "bio" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "qualifications" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "teachingLevels" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "centerName" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "centerAddress" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "centerCity" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "centerWebsite" TEXT;
