-- YEMA · A1 v2 platform provisioning for P-1 / non-production release preparation
-- Source of truth: src/content/monde-a1-v2
-- Contract: 12 units × 5 lessons = 60 active platform modules.
-- Idempotent DML. Do not use this script as a Production release signal.
-- Legacy U1-U6 L6 rows are retained and marked retired to preserve referential history.

BEGIN;

UPDATE public.courses
SET
  title = 'Allemand A1 — Autonomie du quotidien',
  description = 'Un parcours A1 en 12 missions : premières rencontres, famille, café, routine, ville, achats, logement, travail, santé, services, voyage et consolidation.',
  "durationHours" = 36,
  tags = ARRAY['MONDE','DEUTSCH','A1','ADULT','A1_V2_REFONTE']::text[],
  "isPublished" = false,
  "updatedAt" = CURRENT_TIMESTAMP
WHERE id = 'monde-adulte-de-a1';

INSERT INTO public.modules (
  id, "courseId", title, description, type, content,
  "sortOrder", "xpReward", "isPublished", "updatedAt"
) VALUES
('de-a1-u1-l1', 'monde-adulte-de-a1', 'Comprendre une première rencontre', 'Repérer nom, origine, ville et langues dans un échange oral', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u1-refonte-r3","unitId":"de-a1-u1","unitOrder":1,"lessonId":"de-a1-u1-l1","lessonOrder":1,"phase":"Comprends","exerciseCount":5,"activeInPlatform":true}'::jsonb, 0, 20, false, CURRENT_TIMESTAMP),
('de-a1-u1-l2', 'monde-adulte-de-a1', 'Dire qui tu es', 'Produire les quatre informations personnelles de base · Poser une question en plaçant le verbe en deuxième position', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u1-refonte-r3","unitId":"de-a1-u1","unitOrder":1,"lessonId":"de-a1-u1-l2","lessonOrder":2,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 1, 20, false, CURRENT_TIMESTAMP),
('de-a1-u1-l3', 'monde-adulte-de-a1', 'Poser les bonnes questions', 'Poser une question en plaçant le verbe en deuxième position · Enchaîner une courte première rencontre en répondant et en relançant', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u1-refonte-r3","unitId":"de-a1-u1","unitOrder":1,"lessonId":"de-a1-u1-l3","lessonOrder":3,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 2, 20, false, CURRENT_TIMESTAMP),
('de-a1-u1-l4', 'monde-adulte-de-a1', 'Saluer, prononcer et enchaîner', 'Choisir une salutation et une formule de fin adaptées à la situation · Rendre compréhensibles les sons-clés de la première rencontre · Enchaîner une courte première rencontre en répondant et en relançant', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u1-refonte-r3","unitId":"de-a1-u1","unitOrder":1,"lessonId":"de-a1-u1-l4","lessonOrder":4,"phase":"Produis","exerciseCount":5,"activeInPlatform":true}'::jsonb, 3, 20, false, CURRENT_TIMESTAMP),
('de-a1-u1-l5', 'monde-adulte-de-a1', 'Mission finale : première rencontre', 'Repérer nom, origine, ville et langues dans un échange oral · Produire les quatre informations personnelles de base · Poser une question en plaçant le verbe en deuxième position · Enchaîner une courte première rencontre en répondant et en relançant', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u1-refonte-r3","unitId":"de-a1-u1","unitOrder":1,"lessonId":"de-a1-u1-l5","lessonOrder":5,"phase":"Valide","exerciseCount":5,"activeInPlatform":true}'::jsonb, 4, 40, false, CURRENT_TIMESTAMP),
('de-a1-u2-l1', 'monde-adulte-de-a1', 'Comprendre un portrait de famille', 'Repérer le lien familial, le prénom, l’âge et le lieu dans une présentation orale', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u2-refonte-r1","unitId":"de-a1-u2","unitOrder":2,"lessonId":"de-a1-u2-l1","lessonOrder":1,"phase":"Comprends","exerciseCount":5,"activeInPlatform":true}'::jsonb, 5, 20, false, CURRENT_TIMESTAMP),
('de-a1-u2-l2', 'monde-adulte-de-a1', 'Nommer les proches et utiliser mein/meine', 'Nommer les membres essentiels d’une famille · Choisir mein/meine et dein/deine selon le nom', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u2-refonte-r1","unitId":"de-a1-u2","unitOrder":2,"lessonId":"de-a1-u2-l2","lessonOrder":2,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 6, 20, false, CURRENT_TIMESTAMP),
('de-a1-u2-l3', 'monde-adulte-de-a1', 'Avoir, ne pas avoir et reprendre avec er/sie', 'Dire ce que l’on a ou n’a pas avec haben et keine · Reprendre une personne avec er/sie et accorder le verbe au pluriel', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u2-refonte-r1","unitId":"de-a1-u2","unitOrder":2,"lessonId":"de-a1-u2-l3","lessonOrder":3,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 7, 20, false, CURRENT_TIMESTAMP),
('de-a1-u2-l4', 'monde-adulte-de-a1', 'Décrire une personne clairement', 'Reprendre une personne avec er/sie et accorder le verbe au pluriel · Présenter plusieurs proches et répondre à des questions simples', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u2-refonte-r1","unitId":"de-a1-u2","unitOrder":2,"lessonId":"de-a1-u2-l4","lessonOrder":4,"phase":"Produis","exerciseCount":5,"activeInPlatform":true}'::jsonb, 8, 20, false, CURRENT_TIMESTAMP),
('de-a1-u2-l5', 'monde-adulte-de-a1', 'Mission finale : présenter sa famille', 'Repérer le lien familial, le prénom, l’âge et le lieu dans une présentation orale · Choisir mein/meine et dein/deine selon le nom · Dire ce que l’on a ou n’a pas avec haben et keine · Reprendre une personne avec er/sie et accorder le verbe au pluriel · Présenter plusieurs proches et répondre à des questions simples', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u2-refonte-r1","unitId":"de-a1-u2","unitOrder":2,"lessonId":"de-a1-u2-l5","lessonOrder":5,"phase":"Valide","exerciseCount":5,"activeInPlatform":true}'::jsonb, 9, 40, false, CURRENT_TIMESTAMP),
('de-a1-u3-l1', 'monde-adulte-de-a1', 'Comprendre une commande', 'Repérer produits, préférences, prix et moyen de paiement dans une commande orale', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u3-refonte-r1","unitId":"de-a1-u3","unitOrder":3,"lessonId":"de-a1-u3-l1","lessonOrder":1,"phase":"Comprends","exerciseCount":5,"activeInPlatform":true}'::jsonb, 10, 20, false, CURRENT_TIMESTAMP),
('de-a1-u3-l2', 'monde-adulte-de-a1', 'Choisir et personnaliser une commande', 'Personnaliser une commande avec mit et ohne · Mener une commande courte du salut au paiement', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u3-refonte-r1","unitId":"de-a1-u3","unitOrder":3,"lessonId":"de-a1-u3-l2","lessonOrder":2,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 11, 20, false, CURRENT_TIMESTAMP),
('de-a1-u3-l3', 'monde-adulte-de-a1', 'Commander avec la bonne forme', 'Commander poliment avec Ich hätte gern et la forme einen/eine/ein', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u3-refonte-r1","unitId":"de-a1-u3","unitOrder":3,"lessonId":"de-a1-u3-l3","lessonOrder":3,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 12, 20, false, CURRENT_TIMESTAMP),
('de-a1-u3-l4', 'monde-adulte-de-a1', 'Comprendre un prix et payer', 'Comprendre un prix simple et demander combien cela coûte · Demander l’addition et préciser un moyen de paiement · Mener une commande courte du salut au paiement', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u3-refonte-r1","unitId":"de-a1-u3","unitOrder":3,"lessonId":"de-a1-u3-l4","lessonOrder":4,"phase":"Produis","exerciseCount":5,"activeInPlatform":true}'::jsonb, 13, 20, false, CURRENT_TIMESTAMP),
('de-a1-u3-l5', 'monde-adulte-de-a1', 'Mission finale : commander et payer', 'Repérer produits, préférences, prix et moyen de paiement dans une commande orale · Personnaliser une commande avec mit et ohne · Commander poliment avec Ich hätte gern et la forme einen/eine/ein · Comprendre un prix simple et demander combien cela coûte · Demander l’addition et préciser un moyen de paiement · Mener une commande courte du salut au paiement', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u3-refonte-r1","unitId":"de-a1-u3","unitOrder":3,"lessonId":"de-a1-u3-l5","lessonOrder":5,"phase":"Valide","exerciseCount":5,"activeInPlatform":true}'::jsonb, 14, 40, false, CURRENT_TIMESTAMP),
('de-a1-u4-l1', 'monde-adulte-de-a1', 'Comprendre une routine quotidienne', 'Repérer actions et horaires dans une journée · Exprimer une heure précise ou approximative', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u4-refonte-r1","unitId":"de-a1-u4","unitOrder":4,"lessonId":"de-a1-u4-l1","lessonOrder":1,"phase":"Comprends","exerciseCount":5,"activeInPlatform":true}'::jsonb, 15, 20, false, CURRENT_TIMESTAMP),
('de-a1-u4-l2', 'monde-adulte-de-a1', 'Nommer et ordonner les actions du quotidien', 'Organiser une routine avec zuerst, dann et danach · Décrire sa journée et répondre à des questions d’horaires', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u4-refonte-r1","unitId":"de-a1-u4","unitOrder":4,"lessonId":"de-a1-u4-l2","lessonOrder":2,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 16, 20, false, CURRENT_TIMESTAMP),
('de-a1-u4-l3', 'monde-adulte-de-a1', 'Maîtriser les verbes séparables', 'Construire des phrases avec des verbes séparables · Maintenir le verbe en deuxième position après un moment initial', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u4-refonte-r1","unitId":"de-a1-u4","unitOrder":4,"lessonId":"de-a1-u4-l3","lessonOrder":3,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 17, 20, false, CURRENT_TIMESTAMP),
('de-a1-u4-l4', 'monde-adulte-de-a1', 'Dire l’heure et structurer la journée', 'Exprimer une heure précise ou approximative · Maintenir le verbe en deuxième position après un moment initial · Décrire sa journée et répondre à des questions d’horaires', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u4-refonte-r1","unitId":"de-a1-u4","unitOrder":4,"lessonId":"de-a1-u4-l4","lessonOrder":4,"phase":"Produis","exerciseCount":5,"activeInPlatform":true}'::jsonb, 18, 20, false, CURRENT_TIMESTAMP),
('de-a1-u4-l5', 'monde-adulte-de-a1', 'Mission finale : une journée typique', 'Repérer actions et horaires dans une journée · Organiser une routine avec zuerst, dann et danach · Construire des phrases avec des verbes séparables · Exprimer une heure précise ou approximative · Maintenir le verbe en deuxième position après un moment initial · Décrire sa journée et répondre à des questions d’horaires', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u4-refonte-r1","unitId":"de-a1-u4","unitOrder":4,"lessonId":"de-a1-u4-l5","lessonOrder":5,"phase":"Valide","exerciseCount":5,"activeInPlatform":true}'::jsonb, 19, 40, false, CURRENT_TIMESTAMP),
('de-a1-u5-l1', 'monde-adulte-de-a1', 'Comprendre des indications simples', 'Repérer direction, point de repère et durée dans un itinéraire oral · Utiliser geradeaus, links, rechts et les repères urbains', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u5-refonte-r1","unitId":"de-a1-u5","unitOrder":5,"lessonId":"de-a1-u5-l1","lessonOrder":1,"phase":"Comprends","exerciseCount":5,"activeInPlatform":true}'::jsonb, 20, 20, false, CURRENT_TIMESTAMP),
('de-a1-u5-l2', 'monde-adulte-de-a1', 'Utiliser directions et repères', 'Utiliser geradeaus, links, rechts et les repères urbains · Comprendre et produire l’impératif de politesse avec Sie', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u5-refonte-r1","unitId":"de-a1-u5","unitOrder":5,"lessonId":"de-a1-u5-l2","lessonOrder":2,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 21, 20, false, CURRENT_TIMESTAMP),
('de-a1-u5-l3', 'monde-adulte-de-a1', 'Demander et reformuler son chemin', 'Demander poliment où se trouve un lieu · Demander, reformuler et confirmer un itinéraire simple', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u5-refonte-r1","unitId":"de-a1-u5","unitOrder":5,"lessonId":"de-a1-u5-l3","lessonOrder":3,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 22, 20, false, CURRENT_TIMESTAMP),
('de-a1-u5-l4', 'monde-adulte-de-a1', 'Acheter un billet simple', 'Acheter un billet simple et comprendre quelques questions de transport · Demander, reformuler et confirmer un itinéraire simple', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u5-refonte-r1","unitId":"de-a1-u5","unitOrder":5,"lessonId":"de-a1-u5-l4","lessonOrder":4,"phase":"Produis","exerciseCount":5,"activeInPlatform":true}'::jsonb, 23, 20, false, CURRENT_TIMESTAMP),
('de-a1-u5-l5', 'monde-adulte-de-a1', 'Mission finale : trouver la gare', 'Repérer direction, point de repère et durée dans un itinéraire oral · Utiliser geradeaus, links, rechts et les repères urbains · Demander poliment où se trouve un lieu · Comprendre et produire l’impératif de politesse avec Sie · Acheter un billet simple et comprendre quelques questions de transport · Demander, reformuler et confirmer un itinéraire simple', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u5-refonte-r1","unitId":"de-a1-u5","unitOrder":5,"lessonId":"de-a1-u5-l5","lessonOrder":5,"phase":"Valide","exerciseCount":5,"activeInPlatform":true}'::jsonb, 24, 40, false, CURRENT_TIMESTAMP),
('de-a1-u6-l1', 'monde-adulte-de-a1', 'Einkauf und Verabredung verstehen', 'Repérer produit, couleur, taille, prix, activité, heure et lieu dans deux scènes', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u6-refonte-r1","unitId":"de-a1-u6","unitOrder":6,"lessonId":"de-a1-u6-l1","lessonOrder":1,"phase":"Comprends","exerciseCount":5,"activeInPlatform":true}'::jsonb, 25, 20, false, CURRENT_TIMESTAMP),
('de-a1-u6-l2', 'monde-adulte-de-a1', 'Kleidung suchen, anprobieren und wählen', 'Demander un vêtement, préciser couleur/taille et décider de l’achat · Dire si un vêtement convient ou s’il est trop grand/petit', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u6-refonte-r1","unitId":"de-a1-u6","unitOrder":6,"lessonId":"de-a1-u6-l2","lessonOrder":2,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 26, 20, false, CURRENT_TIMESTAMP),
('de-a1-u6-l3', 'monde-adulte-de-a1', 'Mit können höflich fragen', 'Formuler une demande avec können et l’infinitif final', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u6-refonte-r1","unitId":"de-a1-u6","unitOrder":6,"lessonId":"de-a1-u6-l3","lessonOrder":3,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 27, 20, false, CURRENT_TIMESTAMP),
('de-a1-u6-l4', 'monde-adulte-de-a1', 'Eine Aktivität vorschlagen und einen Treffpunkt festlegen', 'Proposer une activité avec Wollen wir…? et accepter/refuser simplement · Fixer une heure et un lieu de rendez-vous de façon précise', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u6-refonte-r1","unitId":"de-a1-u6","unitOrder":6,"lessonId":"de-a1-u6-l4","lessonOrder":4,"phase":"Produis","exerciseCount":5,"activeInPlatform":true}'::jsonb, 28, 20, false, CURRENT_TIMESTAMP),
('de-a1-u6-l5', 'monde-adulte-de-a1', 'Mission: Einkauf und Verabredung', 'Repérer produit, couleur, taille, prix, activité, heure et lieu dans deux scènes · Demander un vêtement, préciser couleur/taille et décider de l’achat · Formuler une demande avec können et l’infinitif final · Dire si un vêtement convient ou s’il est trop grand/petit · Proposer une activité avec Wollen wir…? et accepter/refuser simplement · Fixer une heure et un lieu de rendez-vous de façon précise', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u6-refonte-r1","unitId":"de-a1-u6","unitOrder":6,"lessonId":"de-a1-u6-l5","lessonOrder":5,"phase":"Valide","exerciseCount":5,"activeInPlatform":true}'::jsonb, 29, 40, false, CURRENT_TIMESTAMP),
('de-a1-u7-l1', 'monde-adulte-de-a1', 'Eine Wohnungsanzeige verstehen', 'Comprendre les informations essentielles d’une annonce de logement simple · Dire ce qu’il y a avec es gibt', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u7-reconstruction-r1","unitId":"de-a1-u7","unitOrder":7,"lessonId":"de-a1-u7-l1","lessonOrder":1,"phase":"Comprends","exerciseCount":5,"activeInPlatform":true}'::jsonb, 30, 20, false, CURRENT_TIMESTAMP),
('de-a1-u7-l2', 'monde-adulte-de-a1', 'Räume, Möbel und wichtige Dinge', 'Nommer les pièces, meubles et objets essentiels', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u7-reconstruction-r1","unitId":"de-a1-u7","unitOrder":7,"lessonId":"de-a1-u7-l2","lessonOrder":2,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 31, 20, false, CURRENT_TIMESTAMP),
('de-a1-u7-l3', 'monde-adulte-de-a1', 'Sagen, was da ist und wo es ist', 'Dire ce qu’il y a avec es gibt · Dire où se trouve un objet avec ist/sind et des prépositions spatiales simples · Poser et comprendre des questions simples pendant une visite', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u7-reconstruction-r1","unitId":"de-a1-u7","unitOrder":7,"lessonId":"de-a1-u7-l3","lessonOrder":3,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 32, 20, false, CURRENT_TIMESTAMP),
('de-a1-u7-l4', 'monde-adulte-de-a1', 'Die eigene Wohnung beschreiben', 'Décrire simplement un logement avec taille, pièces et caractéristiques · Dire où se trouve un objet avec ist/sind et des prépositions spatiales simples', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u7-reconstruction-r1","unitId":"de-a1-u7","unitOrder":7,"lessonId":"de-a1-u7-l4","lessonOrder":4,"phase":"Produis","exerciseCount":5,"activeInPlatform":true}'::jsonb, 33, 20, false, CURRENT_TIMESTAMP),
('de-a1-u7-l5', 'monde-adulte-de-a1', 'Mission: eine Wohnung besichtigen', 'Comprendre les informations essentielles d’une annonce de logement simple · Nommer les pièces, meubles et objets essentiels · Dire ce qu’il y a avec es gibt · Dire où se trouve un objet avec ist/sind et des prépositions spatiales simples · Décrire simplement un logement avec taille, pièces et caractéristiques · Poser et comprendre des questions simples pendant une visite', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u7-reconstruction-r1","unitId":"de-a1-u7","unitOrder":7,"lessonId":"de-a1-u7-l5","lessonOrder":5,"phase":"Valide","exerciseCount":5,"activeInPlatform":true}'::jsonb, 34, 40, false, CURRENT_TIMESTAMP),
('de-a1-u8-l1', 'monde-adulte-de-a1', 'Eine berufliche Vorstellung verstehen', 'Comprendre une présentation professionnelle ou étudiante simple', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u8-reconstruction-r1","unitId":"de-a1-u8","unitOrder":8,"lessonId":"de-a1-u8-l1","lessonOrder":1,"phase":"Comprends","exerciseCount":5,"activeInPlatform":true}'::jsonb, 35, 20, false, CURRENT_TIMESTAMP),
('de-a1-u8-l2', 'monde-adulte-de-a1', 'Berufe, Studium und Arbeitsorte', 'Nommer quelques métiers, études et lieux de travail fréquents · Se présenter très simplement dans un contexte professionnel ou d’études', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u8-reconstruction-r1","unitId":"de-a1-u8","unitOrder":8,"lessonId":"de-a1-u8-l2","lessonOrder":2,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 36, 20, false, CURRENT_TIMESTAMP),
('de-a1-u8-l3', 'monde-adulte-de-a1', 'Über Arbeitszeiten und Aufgaben sprechen', 'Parler simplement de ses jours, horaires et pauses · Nommer quelques tâches courantes au travail ou dans les études', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u8-reconstruction-r1","unitId":"de-a1-u8","unitOrder":8,"lessonId":"de-a1-u8-l3","lessonOrder":3,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 37, 20, false, CURRENT_TIMESTAMP),
('de-a1-u8-l4', 'monde-adulte-de-a1', 'Sagen, was ich kann', 'Dire ce que l’on sait faire avec können · Se présenter très simplement dans un contexte professionnel ou d’études', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u8-reconstruction-r1","unitId":"de-a1-u8","unitOrder":8,"lessonId":"de-a1-u8-l4","lessonOrder":4,"phase":"Produis","exerciseCount":5,"activeInPlatform":true}'::jsonb, 38, 20, false, CURRENT_TIMESTAMP),
('de-a1-u8-l5', 'monde-adulte-de-a1', 'Mission: mich bei der Arbeit vorstellen', 'Comprendre une présentation professionnelle ou étudiante simple · Nommer quelques métiers, études et lieux de travail fréquents · Parler simplement de ses jours, horaires et pauses · Nommer quelques tâches courantes au travail ou dans les études · Dire ce que l’on sait faire avec können · Se présenter très simplement dans un contexte professionnel ou d’études', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u8-reconstruction-r1","unitId":"de-a1-u8","unitOrder":8,"lessonId":"de-a1-u8-l5","lessonOrder":5,"phase":"Valide","exerciseCount":5,"activeInPlatform":true}'::jsonb, 39, 40, false, CURRENT_TIMESTAMP),
('de-a1-u9-l1', 'monde-adulte-de-a1', 'Ein einfaches Gesundheitsproblem verstehen', 'Comprendre un problème de santé courant exprimé très simplement · Exprimer un besoin simple avec brauchen · Demander et fixer un rendez-vous avec jour et heure', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u9-reconstruction-r1","unitId":"de-a1-u9","unitOrder":9,"lessonId":"de-a1-u9-l1","lessonOrder":1,"phase":"Comprends","exerciseCount":5,"activeInPlatform":true}'::jsonb, 40, 20, false, CURRENT_TIMESTAMP),
('de-a1-u9-l2', 'monde-adulte-de-a1', 'Körper und häufige Symptome', 'Nommer quelques parties du corps et symptômes courants · Comprendre un problème de santé courant exprimé très simplement', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u9-reconstruction-r1","unitId":"de-a1-u9","unitOrder":9,"lessonId":"de-a1-u9-l2","lessonOrder":2,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 41, 20, false, CURRENT_TIMESTAMP),
('de-a1-u9-l3', 'monde-adulte-de-a1', 'Sagen, was weh tut und was ich brauche', 'Dire ce qui fait mal avec haben ou tut weh · Exprimer un besoin simple avec brauchen', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u9-reconstruction-r1","unitId":"de-a1-u9","unitOrder":9,"lessonId":"de-a1-u9-l3","lessonOrder":3,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 42, 20, false, CURRENT_TIMESTAMP),
('de-a1-u9-l4', 'monde-adulte-de-a1', 'Einen Termin vereinbaren', 'Demander et fixer un rendez-vous avec jour et heure · Mener un échange très court au téléphone, au cabinet ou à la pharmacie', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u9-reconstruction-r1","unitId":"de-a1-u9","unitOrder":9,"lessonId":"de-a1-u9-l4","lessonOrder":4,"phase":"Produis","exerciseCount":5,"activeInPlatform":true}'::jsonb, 43, 20, false, CURRENT_TIMESTAMP),
('de-a1-u9-l5', 'monde-adulte-de-a1', 'Mission: Apotheke oder Praxis', 'Comprendre un problème de santé courant exprimé très simplement · Nommer quelques parties du corps et symptômes courants · Dire ce qui fait mal avec haben ou tut weh · Exprimer un besoin simple avec brauchen · Demander et fixer un rendez-vous avec jour et heure · Mener un échange très court au téléphone, au cabinet ou à la pharmacie', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u9-reconstruction-r1","unitId":"de-a1-u9","unitOrder":9,"lessonId":"de-a1-u9-l5","lessonOrder":5,"phase":"Valide","exerciseCount":5,"activeInPlatform":true}'::jsonb, 44, 40, false, CURRENT_TIMESTAMP),
('de-a1-u10-l1', 'monde-adulte-de-a1', 'Eine Service-Anweisung verstehen', 'Comprendre une consigne simple dans un service · Demander de l’aide de façon simple et polie dans un service', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u10-reconstruction-r1","unitId":"de-a1-u10","unitOrder":10,"lessonId":"de-a1-u10-l1","lessonOrder":1,"phase":"Comprends","exerciseCount":5,"activeInPlatform":true}'::jsonb, 45, 20, false, CURRENT_TIMESTAMP),
('de-a1-u10-l2', 'monde-adulte-de-a1', 'Daten, Zahlen und persönliche Informationen', 'Comprendre et donner des dates, numéros et informations personnelles simples · Remplir ou dicter des informations simples dans un formulaire', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u10-reconstruction-r1","unitId":"de-a1-u10","unitOrder":10,"lessonId":"de-a1-u10-l2","lessonOrder":2,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 46, 20, false, CURRENT_TIMESTAMP),
('de-a1-u10-l3', 'monde-adulte-de-a1', 'Um Wiederholung oder Erklärung bitten', 'Demander de répéter, parler plus lentement ou expliquer un mot · Demander de l’aide de façon simple et polie dans un service', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u10-reconstruction-r1","unitId":"de-a1-u10","unitOrder":10,"lessonId":"de-a1-u10-l3","lessonOrder":3,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 47, 20, false, CURRENT_TIMESTAMP),
('de-a1-u10-l4', 'monde-adulte-de-a1', 'Informationen eintragen und bestätigen', 'Remplir ou dicter des informations simples dans un formulaire · Confirmer ou corriger une information entendue', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u10-reconstruction-r1","unitId":"de-a1-u10","unitOrder":10,"lessonId":"de-a1-u10-l4","lessonOrder":4,"phase":"Produis","exerciseCount":5,"activeInPlatform":true}'::jsonb, 48, 20, false, CURRENT_TIMESTAMP),
('de-a1-u10-l5', 'monde-adulte-de-a1', 'Mission: um Hilfe bitten', 'Comprendre une consigne simple dans un service · Comprendre et donner des dates, numéros et informations personnelles simples · Demander de répéter, parler plus lentement ou expliquer un mot · Remplir ou dicter des informations simples dans un formulaire · Confirmer ou corriger une information entendue · Demander de l’aide de façon simple et polie dans un service', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u10-reconstruction-r1","unitId":"de-a1-u10","unitOrder":10,"lessonId":"de-a1-u10-l5","lessonOrder":5,"phase":"Valide","exerciseCount":5,"activeInPlatform":true}'::jsonb, 49, 40, false, CURRENT_TIMESTAMP),
('de-a1-u11-l1', 'monde-adulte-de-a1', 'Eine Reiseinformation verstehen', 'Comprendre une information de voyage simple : départ, heure, voie ou retard', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u11-reconstruction-r1","unitId":"de-a1-u11","unitOrder":11,"lessonId":"de-a1-u11-l1","lessonOrder":1,"phase":"Comprends","exerciseCount":5,"activeInPlatform":true}'::jsonb, 50, 20, false, CURRENT_TIMESTAMP),
('de-a1-u11-l2', 'monde-adulte-de-a1', 'Wetter, Tage und Daten', 'Comprendre et décrire une météo très simple · Utiliser jours, dates et marqueurs temporels proches', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u11-reconstruction-r1","unitId":"de-a1-u11","unitOrder":11,"lessonId":"de-a1-u11-l2","lessonOrder":2,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 51, 20, false, CURRENT_TIMESTAMP),
('de-a1-u11-l3', 'monde-adulte-de-a1', 'Sagen, wohin und wann ich fahre', 'Dire où et quand on va avec un moyen de transport simple · Utiliser jours, dates et marqueurs temporels proches', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u11-reconstruction-r1","unitId":"de-a1-u11","unitOrder":11,"lessonId":"de-a1-u11-l3","lessonOrder":3,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 52, 20, false, CURRENT_TIMESTAMP),
('de-a1-u11-l4', 'monde-adulte-de-a1', 'Eine kurze Reise vorbereiten', 'Préparer un petit déplacement avec heure, transport et objets essentiels · Présenter et comprendre un projet de voyage court', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u11-reconstruction-r1","unitId":"de-a1-u11","unitOrder":11,"lessonId":"de-a1-u11-l4","lessonOrder":4,"phase":"Produis","exerciseCount":5,"activeInPlatform":true}'::jsonb, 53, 20, false, CURRENT_TIMESTAMP),
('de-a1-u11-l5', 'monde-adulte-de-a1', 'Mission: eine kurze Reise organisieren', 'Comprendre une information de voyage simple : départ, heure, voie ou retard · Comprendre et décrire une météo très simple · Utiliser jours, dates et marqueurs temporels proches · Dire où et quand on va avec un moyen de transport simple · Préparer un petit déplacement avec heure, transport et objets essentiels · Présenter et comprendre un projet de voyage court', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u11-reconstruction-r1","unitId":"de-a1-u11","unitOrder":11,"lessonId":"de-a1-u11-l5","lessonOrder":5,"phase":"Valide","exerciseCount":5,"activeInPlatform":true}'::jsonb, 54, 40, false, CURRENT_TIMESTAMP),
('de-a1-u12-l1', 'monde-adulte-de-a1', 'Mehrere A1-Situationen verstehen', 'Comprendre l’essentiel dans plusieurs situations A1 enchaînées · Réparer une interaction en demandant de répéter, ralentir, expliquer ou aider', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u12-reconstruction-r1","unitId":"de-a1-u12","unitOrder":12,"lessonId":"de-a1-u12-l1","lessonOrder":1,"phase":"Comprends","exerciseCount":5,"activeInPlatform":true}'::jsonb, 55, 20, false, CURRENT_TIMESTAMP),
('de-a1-u12-l2', 'monde-adulte-de-a1', 'Häufige Fehler reparieren', 'Corriger des erreurs fréquentes de position du verbe, modal, nombre et question · Réparer une interaction en demandant de répéter, ralentir, expliquer ou aider', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u12-reconstruction-r1","unitId":"de-a1-u12","unitOrder":12,"lessonId":"de-a1-u12-l2","lessonOrder":2,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 56, 20, false, CURRENT_TIMESTAMP),
('de-a1-u12-l3', 'monde-adulte-de-a1', 'Wortschatz des Niveaus reaktivieren', 'Réactiver rapidement du lexique et des chunks issus de tout le niveau · Corriger des erreurs fréquentes de position du verbe, modal, nombre et question', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u12-reconstruction-r1","unitId":"de-a1-u12","unitOrder":12,"lessonId":"de-a1-u12-l3","lessonOrder":3,"phase":"Pratique","exerciseCount":5,"activeInPlatform":true}'::jsonb, 57, 20, false, CURRENT_TIMESTAMP),
('de-a1-u12-l4', 'monde-adulte-de-a1', 'Zwei reale Situationen verbinden', 'Enchaîner deux situations quotidiennes simples sans repartir du français · Réparer une interaction en demandant de répéter, ralentir, expliquer ou aider', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u12-reconstruction-r1","unitId":"de-a1-u12","unitOrder":12,"lessonId":"de-a1-u12-l4","lessonOrder":4,"phase":"Produis","exerciseCount":5,"activeInPlatform":true}'::jsonb, 58, 20, false, CURRENT_TIMESTAMP),
('de-a1-u12-l5', 'monde-adulte-de-a1', 'A1-Bilanz vor den Probeprüfungen', 'Comprendre l’essentiel dans plusieurs situations A1 enchaînées · Réparer une interaction en demandant de répéter, ralentir, expliquer ou aider · Corriger des erreurs fréquentes de position du verbe, modal, nombre et question · Réactiver rapidement du lexique et des chunks issus de tout le niveau · Enchaîner deux situations quotidiennes simples sans repartir du français · Réaliser un bilan guidé des fonctions essentielles avant les examens blancs', 'LESSON'::"ModuleType", '{"source":"monde-a1-v2","platformContentVersion":"2026.09.21-a1-v2-platform-r1","unitContentVersion":"2026.09.20-u12-reconstruction-r1","unitId":"de-a1-u12","unitOrder":12,"lessonId":"de-a1-u12-l5","lessonOrder":5,"phase":"Valide","exerciseCount":5,"activeInPlatform":true}'::jsonb, 59, 40, false, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO UPDATE SET
  "courseId" = EXCLUDED."courseId",
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  type = EXCLUDED.type,
  content = EXCLUDED.content,
  "sortOrder" = EXCLUDED."sortOrder",
  "xpReward" = EXCLUDED."xpReward",
  "isPublished" = false,
  "updatedAt" = CURRENT_TIMESTAMP;

UPDATE public.modules
SET
  "isPublished" = false,
  "sortOrder" = 1000 + CASE id
    WHEN 'de-a1-u1-l6' THEN 1
    WHEN 'de-a1-u2-l6' THEN 2
    WHEN 'de-a1-u3-l6' THEN 3
    WHEN 'de-a1-u4-l6' THEN 4
    WHEN 'de-a1-u5-l6' THEN 5
    WHEN 'de-a1-u6-l6' THEN 6
    ELSE 99
  END,
  content = COALESCE(content, '{}'::jsonb)
    || '{"retiredBy":"a1-v2-platform","activeInPlatform":false}'::jsonb,
  "updatedAt" = CURRENT_TIMESTAMP
WHERE id IN ('de-a1-u1-l6', 'de-a1-u2-l6', 'de-a1-u3-l6', 'de-a1-u4-l6', 'de-a1-u5-l6', 'de-a1-u6-l6');

COMMIT;
