-- YEMA · German A1 adult runtime provisioning
-- Canonical editorial source: src/data/courses/monde/adulte/de-a1
-- Course contract: 2026.08.04 · 6 units · 36 lessons.
-- Data-only, idempotent. Does not delete the legacy TEST_A1_BETA fixture.

INSERT INTO public.courses (
  id, title, description, level, "isPublished", "isFree",
  "durationHours", tags, "sortOrder", "updatedAt"
) VALUES (
  'monde-adulte-de-a1', 'Allemand A1 — Premiers échanges du quotidien', 'Un parcours A1 orienté vers l’action : se présenter, parler de sa famille, commander, décrire sa journée, se déplacer et organiser une sortie.', 'A1'::"DifficultyLevel", true, false, 9, ARRAY['MONDE','DEUTSCH','A1','ADULT']::text[], 10, CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  level = EXCLUDED.level,
  "isPublished" = EXCLUDED."isPublished",
  "isFree" = EXCLUDED."isFree",
  "durationHours" = EXCLUDED."durationHours",
  tags = EXCLUDED.tags,
  "sortOrder" = EXCLUDED."sortOrder",
  "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO public.modules (
  id, "courseId", title, description, type, content,
  "sortOrder", "xpReward", "isPublished", "updatedAt"
) VALUES
('de-a1-u1-l1', 'monde-adulte-de-a1', 'Comprendre une première présentation', 'Repérer le nom, l’origine, la ville et les langues dans un dialogue.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u1","unitOrder":1,"lessonId":"de-a1-u1-l1","lessonOrder":1,"phase":"Comprends","exerciseCount":3}'::jsonb, 0, 20, true, CURRENT_TIMESTAMP),
('de-a1-u1-l2', 'monde-adulte-de-a1', 'Construire sa carte d’identité orale', 'Utiliser les expressions de base pour parler de soi.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u1","unitOrder":1,"lessonId":"de-a1-u1-l2","lessonOrder":2,"phase":"Pratique","exerciseCount":3}'::jsonb, 1, 20, true, CURRENT_TIMESTAMP),
('de-a1-u1-l3', 'monde-adulte-de-a1', 'Poser des questions simples', 'Former des questions avec wie, wo et woher.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u1","unitOrder":1,"lessonId":"de-a1-u1-l3","lessonOrder":3,"phase":"Pratique","exerciseCount":3}'::jsonb, 2, 20, true, CURRENT_TIMESTAMP),
('de-a1-u1-l4', 'monde-adulte-de-a1', 'Prononcer les premiers sons allemands', 'Distinguer et reproduire ch, w et z.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u1","unitOrder":1,"lessonId":"de-a1-u1-l4","lessonOrder":4,"phase":"Pratique","exerciseCount":3}'::jsonb, 3, 20, true, CURRENT_TIMESTAMP),
('de-a1-u1-l5', 'monde-adulte-de-a1', 'Créer ta présentation personnelle', 'Préparer et dire une présentation de 30 à 45 secondes.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u1","unitOrder":1,"lessonId":"de-a1-u1-l5","lessonOrder":5,"phase":"Produis","exerciseCount":2}'::jsonb, 4, 20, true, CURRENT_TIMESTAMP),
('de-a1-u1-l6', 'monde-adulte-de-a1', 'Mission finale : première rencontre', 'Te présenter et poser deux questions à une nouvelle connaissance.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u1","unitOrder":1,"lessonId":"de-a1-u1-l6","lessonOrder":6,"phase":"Valide","exerciseCount":3}'::jsonb, 5, 40, true, CURRENT_TIMESTAMP),
('de-a1-u2-l1', 'monde-adulte-de-a1', 'Comprendre une présentation de famille', 'Identifier les liens familiaux, les prénoms et les lieux.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u2","unitOrder":2,"lessonId":"de-a1-u2-l1","lessonOrder":1,"phase":"Comprends","exerciseCount":3}'::jsonb, 6, 20, true, CURRENT_TIMESTAMP),
('de-a1-u2-l2', 'monde-adulte-de-a1', 'Nommer les membres de la famille', 'Utiliser le vocabulaire des liens familiaux.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u2","unitOrder":2,"lessonId":"de-a1-u2-l2","lessonOrder":2,"phase":"Pratique","exerciseCount":3}'::jsonb, 7, 20, true, CURRENT_TIMESTAMP),
('de-a1-u2-l3', 'monde-adulte-de-a1', 'Utiliser les possessifs et haben', 'Dire à qui appartient le lien familial et si l’on a des frères, sœurs ou enfants.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u2","unitOrder":2,"lessonId":"de-a1-u2-l3","lessonOrder":3,"phase":"Pratique","exerciseCount":3}'::jsonb, 8, 20, true, CURRENT_TIMESTAMP),
('de-a1-u2-l4', 'monde-adulte-de-a1', 'Prononcer les noms de famille clairement', 'Distinguer les voyelles longues et courtes.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u2","unitOrder":2,"lessonId":"de-a1-u2-l4","lessonOrder":4,"phase":"Pratique","exerciseCount":3}'::jsonb, 9, 20, true, CURRENT_TIMESTAMP),
('de-a1-u2-l5', 'monde-adulte-de-a1', 'Préparer une présentation de famille', 'Organiser trois mini-présentations cohérentes.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u2","unitOrder":2,"lessonId":"de-a1-u2-l5","lessonOrder":5,"phase":"Produis","exerciseCount":2}'::jsonb, 10, 20, true, CURRENT_TIMESTAMP),
('de-a1-u2-l6', 'monde-adulte-de-a1', 'Mission finale : ma famille en trois portraits', 'Présenter trois proches et répondre à deux questions.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u2","unitOrder":2,"lessonId":"de-a1-u2-l6","lessonOrder":6,"phase":"Valide","exerciseCount":3}'::jsonb, 11, 40, true, CURRENT_TIMESTAMP),
('de-a1-u3-l1', 'monde-adulte-de-a1', 'Comprendre une commande', 'Repérer les produits, les préférences et le prix.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u3","unitOrder":3,"lessonId":"de-a1-u3-l1","lessonOrder":1,"phase":"Comprends","exerciseCount":3}'::jsonb, 12, 20, true, CURRENT_TIMESTAMP),
('de-a1-u3-l2', 'monde-adulte-de-a1', 'Choisir et personnaliser une commande', 'Utiliser le vocabulaire du café et les mots mit et ohne.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u3","unitOrder":3,"lessonId":"de-a1-u3-l2","lessonOrder":2,"phase":"Pratique","exerciseCount":3}'::jsonb, 13, 20, true, CURRENT_TIMESTAMP),
('de-a1-u3-l3', 'monde-adulte-de-a1', 'Commander avec la bonne forme', 'Utiliser einen, eine et ein après Ich hätte gern.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u3","unitOrder":3,"lessonId":"de-a1-u3-l3","lessonOrder":3,"phase":"Pratique","exerciseCount":3}'::jsonb, 14, 20, true, CURRENT_TIMESTAMP),
('de-a1-u3-l4', 'monde-adulte-de-a1', 'Donner un prix et demander à payer', 'Comprendre les prix et utiliser les formules de paiement.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u3","unitOrder":3,"lessonId":"de-a1-u3-l4","lessonOrder":4,"phase":"Pratique","exerciseCount":3}'::jsonb, 15, 20, true, CURRENT_TIMESTAMP),
('de-a1-u3-l5', 'monde-adulte-de-a1', 'Préparer ta commande complète', 'Enchaîner salutation, commande, préférence, prix et paiement.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u3","unitOrder":3,"lessonId":"de-a1-u3-l5","lessonOrder":5,"phase":"Produis","exerciseCount":2}'::jsonb, 16, 20, true, CURRENT_TIMESTAMP),
('de-a1-u3-l6', 'monde-adulte-de-a1', 'Mission finale : commander et payer', 'Réaliser une interaction complète au café.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u3","unitOrder":3,"lessonId":"de-a1-u3-l6","lessonOrder":6,"phase":"Valide","exerciseCount":3}'::jsonb, 17, 40, true, CURRENT_TIMESTAMP),
('de-a1-u4-l1', 'monde-adulte-de-a1', 'Comprendre une routine quotidienne', 'Repérer les actions et les horaires d’une journée.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u4","unitOrder":4,"lessonId":"de-a1-u4-l1","lessonOrder":1,"phase":"Comprends","exerciseCount":3}'::jsonb, 18, 20, true, CURRENT_TIMESTAMP),
('de-a1-u4-l2', 'monde-adulte-de-a1', 'Nommer les actions du quotidien', 'Utiliser les verbes essentiels de la routine.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u4","unitOrder":4,"lessonId":"de-a1-u4-l2","lessonOrder":2,"phase":"Pratique","exerciseCount":3}'::jsonb, 19, 20, true, CURRENT_TIMESTAMP),
('de-a1-u4-l3', 'monde-adulte-de-a1', 'Maîtriser les verbes séparables', 'Placer correctement le préfixe à la fin de la phrase.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u4","unitOrder":4,"lessonId":"de-a1-u4-l3","lessonOrder":3,"phase":"Pratique","exerciseCount":3}'::jsonb, 20, 20, true, CURRENT_TIMESTAMP),
('de-a1-u4-l4', 'monde-adulte-de-a1', 'Dire l’heure et organiser le temps', 'Utiliser um, gegen, morgens, mittags et abends.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u4","unitOrder":4,"lessonId":"de-a1-u4-l4","lessonOrder":4,"phase":"Pratique","exerciseCount":3}'::jsonb, 21, 20, true, CURRENT_TIMESTAMP),
('de-a1-u4-l5', 'monde-adulte-de-a1', 'Écrire et dire ta routine', 'Construire une description cohérente de six à huit phrases.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u4","unitOrder":4,"lessonId":"de-a1-u4-l5","lessonOrder":5,"phase":"Produis","exerciseCount":2}'::jsonb, 22, 20, true, CURRENT_TIMESTAMP),
('de-a1-u4-l6', 'monde-adulte-de-a1', 'Mission finale : une journée typique', 'Décrire sa routine et répondre à des questions sur ses horaires.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u4","unitOrder":4,"lessonId":"de-a1-u4-l6","lessonOrder":6,"phase":"Valide","exerciseCount":3}'::jsonb, 23, 40, true, CURRENT_TIMESTAMP),
('de-a1-u5-l1', 'monde-adulte-de-a1', 'Comprendre des indications simples', 'Repérer la direction, le point de repère et la durée.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u5","unitOrder":5,"lessonId":"de-a1-u5-l1","lessonOrder":1,"phase":"Comprends","exerciseCount":3}'::jsonb, 24, 20, true, CURRENT_TIMESTAMP),
('de-a1-u5-l2', 'monde-adulte-de-a1', 'Utiliser les mots de direction', 'Associer directions, lieux et points de repère.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u5","unitOrder":5,"lessonId":"de-a1-u5-l2","lessonOrder":2,"phase":"Pratique","exerciseCount":3}'::jsonb, 25, 20, true, CURRENT_TIMESTAMP),
('de-a1-u5-l3', 'monde-adulte-de-a1', 'Demander son chemin poliment', 'Former une demande et comprendre l’impératif de politesse.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u5","unitOrder":5,"lessonId":"de-a1-u5-l3","lessonOrder":3,"phase":"Pratique","exerciseCount":3}'::jsonb, 26, 20, true, CURRENT_TIMESTAMP),
('de-a1-u5-l4', 'monde-adulte-de-a1', 'Acheter un ticket simple', 'Demander un billet et comprendre une destination ou un nombre d’arrêts.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u5","unitOrder":5,"lessonId":"de-a1-u5-l4","lessonOrder":4,"phase":"Pratique","exerciseCount":3}'::jsonb, 27, 20, true, CURRENT_TIMESTAMP),
('de-a1-u5-l5', 'monde-adulte-de-a1', 'Préparer un échange d’orientation', 'Enchaîner une demande, une reformulation et un remerciement.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u5","unitOrder":5,"lessonId":"de-a1-u5-l5","lessonOrder":5,"phase":"Produis","exerciseCount":2}'::jsonb, 28, 20, true, CURRENT_TIMESTAMP),
('de-a1-u5-l6', 'monde-adulte-de-a1', 'Mission finale : trouver la gare', 'Demander un itinéraire, le vérifier et acheter un ticket.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u5","unitOrder":5,"lessonId":"de-a1-u5-l6","lessonOrder":6,"phase":"Valide","exerciseCount":3}'::jsonb, 29, 40, true, CURRENT_TIMESTAMP),
('de-a1-u6-l1', 'monde-adulte-de-a1', 'Comprendre un achat et un rendez-vous', 'Repérer le produit, la taille, le prix, l’activité et l’heure.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u6","unitOrder":6,"lessonId":"de-a1-u6-l1","lessonOrder":1,"phase":"Comprends","exerciseCount":3}'::jsonb, 30, 20, true, CURRENT_TIMESTAMP),
('de-a1-u6-l2', 'monde-adulte-de-a1', 'Demander un vêtement', 'Utiliser les mots du magasin, les couleurs et les tailles.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u6","unitOrder":6,"lessonId":"de-a1-u6-l2","lessonOrder":2,"phase":"Pratique","exerciseCount":3}'::jsonb, 31, 20, true, CURRENT_TIMESTAMP),
('de-a1-u6-l3', 'monde-adulte-de-a1', 'Utiliser können pour demander poliment', 'Construire des questions avec kann ich et placer l’infinitif à la fin.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u6","unitOrder":6,"lessonId":"de-a1-u6-l3","lessonOrder":3,"phase":"Pratique","exerciseCount":3}'::jsonb, 32, 20, true, CURRENT_TIMESTAMP),
('de-a1-u6-l4', 'monde-adulte-de-a1', 'Proposer une sortie et fixer un rendez-vous', 'Utiliser wollen wir, um et un lieu de rencontre.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u6","unitOrder":6,"lessonId":"de-a1-u6-l4","lessonOrder":4,"phase":"Pratique","exerciseCount":3}'::jsonb, 33, 20, true, CURRENT_TIMESTAMP),
('de-a1-u6-l5', 'monde-adulte-de-a1', 'Préparer les deux parties de la mission', 'Créer un dialogue au magasin puis une invitation.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u6","unitOrder":6,"lessonId":"de-a1-u6-l5","lessonOrder":5,"phase":"Produis","exerciseCount":2}'::jsonb, 34, 20, true, CURRENT_TIMESTAMP),
('de-a1-u6-l6', 'monde-adulte-de-a1', 'Mission finale A1 : achat et sortie', 'Acheter un article puis organiser une sortie complète.', 'LESSON'::"ModuleType", '{"source":"yema-course-registry","contentVersion":"2026.08.04","unitId":"de-a1-u6","unitOrder":6,"lessonId":"de-a1-u6-l6","lessonOrder":6,"phase":"Valide","exerciseCount":3}'::jsonb, 35, 40, true, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO UPDATE SET
  "courseId" = EXCLUDED."courseId",
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  type = EXCLUDED.type,
  content = EXCLUDED.content,
  "sortOrder" = EXCLUDED."sortOrder",
  "xpReward" = EXCLUDED."xpReward",
  "isPublished" = EXCLUDED."isPublished",
  "updatedAt" = CURRENT_TIMESTAMP;
