"use client"
import { usePathname } from "next/navigation"

// ─── Landing page ─────────────────────────────────────────────────────────────
const landing = {
  fr: {
    badge: "Plateforme bêta ouverte · Première destination : Allemagne",
    title: "Apprendre. Se préparer.",
    titleAccent: "S'intégrer.",
    subtitle: "La plateforme d'apprentissage de l'allemand conçue pour les Camerounais. Compétences orales, écrites et culturelles — du A1 au C1.",
    subtitle2: "Sans blabla. Sans engagement. Juste de la progression réelle.",
    ctaPrimary: "Commencer gratuitement",
    ctaSecondary: "Tester mon niveau",
    ctaMicro: "Test gratuit après inscription.",
    connexion: "Connexion",
    getStarted: "Démarrer",
    navFeatures: "Fonctionnalités",
    navLevels: "Niveaux",
    navPricing: "Tarifs",
    navCenters: "Centres",
    b2bLabel: "Solution B2B",
    statsUsers: "Apprenants",
    statsLevels: "Niveaux CEFR",
    statsSuccess: "Taux de réussite",
    statsCenters: "Centres partenaires",
    stat1Value: "Bêta", stat1Label: "Accès ouvert",
    stat2Value: "A1", stat2Label: "Niveau disponible",
    stat3Value: "FR & EN", stat3Label: "Langues d'interface",
    stat4Value: "✦", stat4Label: "Construit au Cameroun",
    featuresTitle: "Ce que vous allez vraiment apprendre",
    featuresSubtitle: "8 outils conçus pour une progression concrète — pas juste de la théorie.",
    feature1Title: "Pratique orale guidée", feature1Desc: "Conversez avec un interlocuteur IA en allemand. Progression adaptée à votre niveau — sans pression, sans jugement.", feature1Badge: "IA",
    feature2Title: "Audio allemand authentique", feature2Desc: "Des voix natives, des dialogues réels. Entraînez votre oreille à l'allemand du quotidien.",
    feature3Title: "Correction vocale en temps réel", feature3Desc: "Parlez, l'IA vous corrige immédiatement. Votre accent et votre fluidité s'améliorent leçon après leçon.", feature3Badge: "IA",
    feature4Title: "Coaching écriture IA", feature4Desc: "Rédigez en allemand. Le coach IA Yema vous explique chaque correction avec des exemples contextuels.", feature4Badge: "IA",
    feature5Title: "Quiz qui s'adapte à vous", feature5Desc: "Plus vous progressez, plus le niveau s'ajuste. Chaque session cible vos vraies lacunes.", feature5Badge: "Adaptatif",
    feature6Title: "Classes virtuelles", feature6Desc: "Rejoignez la classe d'un enseignant ou créez votre groupe d'étude. Progression collective visible.", feature6Badge: "Bientôt",
    feature7Title: "Solution centres de langues", feature7Desc: "Un tableau de bord pour gérer enseignants, élèves et classes. Idéal pour les instituts de formation.", feature7Badge: "B2B",
    feature8Title: "Suivi de vos 5 compétences", feature8Desc: "Mesurez vos progrès sur Lecture, Écoute, Expression orale, Écriture et Grammaire.", feature8Badge: "Insights",
    levelsTitle: "Programme CECRL — de A1 à C1",
    levelsSubtitle: "Contenu pédagogique original aligné sur le Cadre Européen Commun de Référence pour les Langues.",
    available: "Disponible", locked: "🔒 Premium", modules: "modules",
    level1Name: "Débutant", level1Desc: "Salutations, famille, chiffres, routine quotidienne",
    level2Name: "Élémentaire", level2Desc: "Vie urbaine, médias, santé, voyages",
    level3Name: "Intermédiaire", level3Desc: "Travail, société, culture, environnement",
    level4Name: "Avancé", level4Desc: "Sciences, économie, médias, histoire",
    level5Name: "Maîtrise", level5Desc: "Philosophie, littérature, carrière internationale",
    visionTitle: "Une plateforme. Trois ambitions.",
    visionSubtitle: "Yema n'est pas une simple application de vocabulaire. C'est un parcours complet vers la maîtrise de l'allemand.",
    vision1Label: "Apprendre", vision1Title: "Des bases solides", vision1Desc: "Un programme structuré, du A1 au C1, avec des exercices oraux, écrits et audio pour bâtir de véritables compétences.",
    vision2Label: "Se préparer", vision2Title: "Pour un vrai objectif", vision2Desc: "Que vous visiez des études, un emploi ou une installation en Allemagne — Yema adapte votre apprentissage à votre projet de vie.",
    vision3Label: "S'intégrer", vision3Title: "La langue, la culture, le quotidien", vision3Desc: "Comprendre l'Allemagne au-delà des mots : les usages, les codes culturels, les situations de la vie réelle.",
    germanyTitle: "Pourquoi l'Allemagne ?",
    germanyText: "L'Allemagne reste l'une des destinations les plus accessibles pour les Camerounais souhaitant étudier ou travailler en Europe. La langue est la clé.",
    germany1: "Plus de 400 universités, dont beaucoup proposent des cursus gratuits ou peu coûteux",
    germany2: "Des opportunités professionnelles dans l'ingénierie, la santé et l'informatique",
    germany3: "Une diaspora camerounaise établie, facilitant l'intégration",
    germany4: "Niveau B1 minimum requis pour la majorité des démarches universitaires et professionnelles",
    testimonialsTitle: "Ce que Yema veut résoudre",
    testimonial1Text: "", testimonial1Role: "",
    testimonial2Text: "", testimonial2Role: "",
    testimonial3Text: "", testimonial3Role: "",
    problem1Title: "Les cours classiques ne suffisent pas",
    problem1Desc: "Les méthodes traditionnelles enseignent la grammaire, mais pas comment parler ou comprendre un Allemand dans la vraie vie.",
    problem2Title: "Les ressources coûtent cher",
    problem2Desc: "Manuels importés, cours particuliers, abonnements en devises — apprendre l'allemand reste inaccessible pour beaucoup.",
    problem3Title: "Personne ne prépare au contexte camerounais",
    problem3Desc: "Les plateformes internationales ignorent les objectifs réels : études en Allemagne, mobilité professionnelle, regroupement familial.",
    simTitle: "Fonctionnalité phare", simHeadline: "Entraînez-vous en allemand avec l'IA",
    simDesc: "Notre assistant IA vous met en situation réelle : conversations, vocabulaire des démarches administratives, expressions du quotidien. Chaque réponse est analysée et corrigée pour vous faire progresser.",
    simCta: "Essayer gratuitement →", simConsulOnline: "Assistant IA · En ligne",
    simMsg1: "Bonjour. Pouvez-vous vous présenter ?", simMsg2: "Bonjour. Je m'appelle Paul, je viens du Cameroun.", simMsg3: "Pourquoi souhaitez-vous apprendre l'allemand ?",
    simScoreLabel: "📊 Score en temps réel", simGrammar: "Grammaire", simVocab: "Vocab", simRelevance: "Pertinence",
    simVisa1: "Vocabulaire des démarches administratives", simVisa2: "Expressions du monde du travail", simVisa3: "Vie quotidienne et intégration", simVisa4: "Études et parcours universitaire", simVisa5: "Culture et codes sociaux allemands",
    centerTitle: "Vous êtes un centre de langues ou un enseignant ?",
    centerDesc: "Yema accompagne les centres avec des outils digitaux pour suivre les apprenants, soutenir les enseignants et structurer la progression.",
    centerFeature1: "Espace dédié pour votre centre", centerFeature2: "Suivi des apprenants en temps réel", centerFeature3: "Support pour les enseignants", centerFeature4: "Accès aux parcours Yema (A1→C1)", centerFeature5: "Accompagnement adapté à vos besoins",
    centerCta: "Demander un devis →", centerOnDemand: "Sur devis", centerPerMonth: "/mois",
    centerReassurance: "Le tarif dépend du nombre d'apprenants, d'enseignants et des fonctionnalités nécessaires.",
    centerAudience1Label: "Apprenants", centerAudience1Desc: "Apprenez à votre rythme avec des cours en ligne, de la pratique orale et un suivi de progression.",
    centerAudience2Label: "Enseignants", centerAudience2Desc: "Utilisez Yema comme outil de support numérique pour guider vos apprenants et structurer leur progression.",
    centerAudience3Label: "Centres", centerAudience3Desc: "Gérez classes, enseignants et apprenants depuis un espace dédié.",
    faqTitle: "Questions fréquentes",
    faq1Q: "Comment fonctionne l'entraînement oral avec l'IA ?", faq1A: "Vous conversez avec notre assistant IA en allemand. Il analyse votre réponse, signale les erreurs de grammaire et de vocabulaire, et vous suggère des formulations plus naturelles — en temps réel.",
    faq2Q: "Le plan gratuit est-il vraiment gratuit ?", faq2A: "Oui, totalement gratuit. Pas de carte bancaire requise. Accès complet au niveau A1 avec 3 leçons par jour.",
    faq3Q: "Yema prépare-t-il aux examens de langue allemande ?", faq3A: "Yema développe vos compétences orales et écrites en allemand, alignées sur le Cadre CECRL (A1-C1). Nous sommes une plateforme indépendante. Pour les certifications officielles, renseignez-vous auprès des organismes accrédités dans votre pays.",
    faq4Q: "Puis-je rejoindre la classe d'un enseignant ?", faq4A: "Oui. Entrez le code de classe de votre enseignant lors de l'inscription ou depuis votre tableau de bord. Votre enseignant validera votre accès.",
    faq5Q: "Y a-t-il une application mobile ?", faq5A: "La plateforme est entièrement optimisée pour mobile via le navigateur. Une application native est en cours de développement.",
    faq6Q: "Comment devenir centre partenaire ?", faq6A: "Contactez-nous via WhatsApp ou email. Nous proposons un accès découverte gratuit pour tester la solution avec votre équipe avant tout engagement.",
    ctaFinalTitle: "Apprendre. Se préparer.", ctaFinalSub: "S'intégrer.",
    ctaFinalDesc: "Pas de carte bancaire. Pas d'engagement. Accès immédiat au niveau A1 complet.",
    ctaFinalBtn: "Rejoins la bêta", ctaFinalSocial: "Sans carte bancaire · A1 gratuit · CECRL A1→C1",
    ctaFinalAppLabel: "Bientôt disponible sur", ctaFinalCities: "Disponible au Cameroun — bientôt en Afrique centrale",
    footerTagline: "Apprendre. Se préparer. S'intégrer.",
    footerDisclaimer: "Yema Languages propose une pratique linguistique indépendante alignée sur le CECRL et n'est affiliée à aucun organisme officiel d'examen.",
    footerMade: "Construit au Cameroun, pour l'Afrique", footerLegal: "Mentions légales", footerTerms: "CGU", footerPrivacy: "Confidentialité", footerContact: "Contact",
  },
  en: {
    badge: "Open beta · First destination: Germany",
    title: "Learn. Prepare.",
    titleAccent: "Belong.",
    subtitle: "Yema helps you learn a language, prepare for life abroad, and build the confidence to integrate into a new country.",
    subtitle2: "We are starting with German and Germany — interactive lessons, speaking practice and realistic simulations.",
    ctaPrimary: "Start for free",
    ctaSecondary: "Test my level",
    ctaMicro: "Free test after registration.",
    connexion: "Log in",
    getStarted: "Get started",
    navFeatures: "Features",
    navLevels: "Levels",
    navPricing: "Pricing",
    navCenters: "Centers",
    b2bLabel: "Learners · Teachers · Centers",
    statsUsers: "Learners",
    statsLevels: "CEFR Levels",
    statsSuccess: "Success rate",
    statsCenters: "Partner centers",
    stat1Value: "Beta", stat1Label: "Open access",
    stat2Value: "A1", stat2Label: "Available now",
    stat3Value: "FR & EN", stat3Label: "Interface languages",
    stat4Value: "✦", stat4Label: "Built in Cameroon",
    featuresTitle: "Tools to progress with confidence",
    featuresSubtitle: "From speaking practice to real-life situations — tools to build real skills.",
    feature1Title: "Train with real-life situations", feature1Desc: "Work on conversations useful for daily life, studies and practical procedures in Germany.", feature1Badge: "Practice",
    feature2Title: "Listen and learn", feature2Desc: "Audio content with native German voices, calibrated for your level.",
    feature3Title: "Practice speaking", feature3Desc: "Speak out loud and get instant feedback to improve your pronunciation and fluency.", feature3Badge: "Speaking",
    feature4Title: "Correct your writing", feature4Desc: "Understand your grammar and vocabulary errors with clear, detailed explanations.", feature4Badge: "AI",
    feature5Title: "Learn with a clear path", feature5Desc: "Progress step by step with short lessons designed around the CEFR A1 framework.", feature5Badge: "Structured",
    feature6Title: "Move at your own pace", feature6Desc: "Learn online in a more flexible and accessible way than traditional classroom courses.", feature6Badge: "",
    feature7Title: "For teachers and centers", feature7Desc: "Digital tools to support, guide and manage learners in a structured way.", feature7Badge: "B2B",
    feature8Title: "Track your progress", feature8Desc: "See what you have learned, your strengths and the skills still to improve.", feature8Badge: "Insights",
    levelsTitle: "A CEFR-aligned learning path",
    levelsSubtitle: "Recognized levels to help you progress from beginner to advanced.",
    available: "Available", locked: "🔒 Coming soon", modules: "modules",
    level1Name: "Beginner", level1Desc: "Introduce yourself, talk about your family and understand simple sentences.",
    level2Name: "Elementary", level2Desc: "Communicate in common everyday situations.",
    level3Name: "Intermediate", level3Desc: "Interact with more independence in personal, professional or administrative situations.",
    level4Name: "Advanced", level4Desc: "Express opinions, explain projects and understand more complex content.",
    level5Name: "Mastery", level5Desc: "Communicate with ease in academic, professional or advanced integration contexts.",
    visionTitle: "One platform for the whole journey",
    visionSubtitle: "Learning a language is only the beginning. Yema combines learning, preparation and integration.",
    vision1Label: "Yema Languages", vision1Title: "Learn", vision1Desc: "Structured lessons, interactive exercises and AI tools to help you progress in the language.",
    vision2Label: "Yema Coach · coming soon", vision2Title: "Prepare", vision2Desc: "Simulations, checklists and soon personal coaches to help you prepare for your goals abroad.",
    vision3Label: "Yema Community · coming soon", vision3Title: "Belong", vision3Desc: "A future community to find learning partners, connect with the diaspora and move forward together.",
    germanyTitle: "First destination: Germany",
    germanyText: "For the beta, Yema focuses on German and practical situations useful for studying, working, living or growing in Germany.",
    germany1: "A1 lessons to get started",
    germany2: "Speaking practice with feedback",
    germany3: "Real-life situations",
    germany4: "Useful paths for students, workers and diaspora",
    testimonialsTitle: "What Yema is built to solve",
    testimonial1Text: "", testimonial1Role: "",
    testimonial2Text: "", testimonial2Role: "",
    testimonial3Text: "", testimonial3Role: "",
    problem1Title: "Traditional courses are not enough",
    problem1Desc: "Standard methods teach grammar but not how to actually speak or understand real conversations with native speakers.",
    problem2Title: "Quality resources are out of reach",
    problem2Desc: "Textbooks, private lessons and foreign-currency subscriptions keep quality language learning inaccessible for many.",
    problem3Title: "Platforms ignore your context",
    problem3Desc: "Most language apps are not built for learners in Africa preparing for an international life project.",
    simTitle: "Practice", simHeadline: "Practice realistic conversations",
    simDesc: "Yema helps you practice situations inspired by real life: introductions, personal questions, study goals, work, housing and practical procedures.",
    simCta: "Try the simulator →", simConsulOnline: "AI Assistant · Online",
    simMsg1: "Hello! Could you introduce yourself?", simMsg2: "Hello. My name is Paul, I'm from Cameroon.", simMsg3: "Why do you want to learn German?",
    simScoreLabel: "📊 Live score", simGrammar: "Grammar", simVocab: "Vocabulary", simRelevance: "Relevance",
    simVisa1: "Daily introductions", simVisa2: "Study goals and university life", simVisa3: "Work and professional situations", simVisa4: "Housing and practical procedures", simVisa5: "Building confidence in German",
    centerTitle: "For learners, teachers and centers",
    centerDesc: "Yema helps learners progress independently while giving teachers and centers digital tools to support and structure learning.",
    centerFeature1: "Learn at your own pace with online lessons, speaking practice and progress tracking.", centerFeature2: "Use Yema as a digital support tool to guide learners and structure their progression.", centerFeature3: "Manage classes, teachers and learners through a dedicated space.", centerFeature4: "Mobile-friendly for all learners", centerFeature5: "Partner center access · coming soon",
    centerCta: "Request a demo →", centerOnDemand: "On request", centerPerMonth: "/month",
    centerReassurance: "Pricing depends on the number of learners, teachers and features needed.",
    centerAudience1Label: "Learners", centerAudience1Desc: "Learn at your own pace with online lessons, speaking practice and progress tracking.",
    centerAudience2Label: "Teachers", centerAudience2Desc: "Use Yema as a digital support tool to guide learners and structure their progression.",
    centerAudience3Label: "Centers", centerAudience3Desc: "Manage classes, teachers and learners through a dedicated space.",
    faqTitle: "Common questions",
    faq1Q: "How does speaking practice work?", faq1A: "You interact with an AI assistant in German. It analyzes your responses, flags grammar and vocabulary errors, and suggests more natural phrasing in real time. Sessions are designed to build confidence through practice.",
    faq2Q: "Is the free plan actually free?", faq2A: "Yes — completely free. No credit card required. Full access to A1 with 3 lessons per day.",
    faq3Q: "Does Yema prepare you for German language exams?", faq3A: "Yema develops your spoken and written German skills, aligned with the CEFR framework (A1-C1). We are an independent platform. For official certifications, contact accredited examination bodies in your country.",
    faq4Q: "Can I join a teacher's class?", faq4A: "Absolutely. Enter your teacher's class code when you sign up or from your dashboard. Your teacher approves your enrollment.",
    faq5Q: "Is there a mobile app?", faq5A: "The platform works great on mobile (iOS and Android) through your browser. A native app is on the roadmap.",
    faq6Q: "How do I become a partner center?", faq6A: "Reach out on WhatsApp or email. We offer a free discovery period to try the solution with your team — no commitment.",
    ctaFinalTitle: "Learn. Prepare.", ctaFinalSub: "Belong.",
    ctaFinalDesc: "No credit card. No commitment. Full A1 access — start today.",
    ctaFinalBtn: "Join the beta", ctaFinalSocial: "Beta access · Free A1 · CEFR aligned",
    ctaFinalAppLabel: "Coming soon on", ctaFinalCities: "Starting with German and Germany — more languages coming.",
    footerTagline: "Learn. Prepare. Belong.",
    footerDisclaimer: "Yema Languages provides independent CEFR-aligned language practice and is not affiliated with any official examination institute.",
    footerMade: "Built from Cameroon for learners with international ambitions.", footerLegal: "Legal", footerTerms: "Terms", footerPrivacy: "Privacy", footerContact: "Contact",
  },
}

// ─── Navigation ────────────────────────────────────────────────────────────────
const nav = {
  fr: {
    home: "Accueil", courses: "Cours", myClasses: "Mes Classes", discover: "Découvrir",
    simulator: "Simulateur IA", progress: "Progression", settings: "Paramètres",
    overview: "Vue d'ensemble", students: "Élèves", assignments: "Devoirs",
    generateCourse: "Générer cours", stats: "Statistiques", teachers: "Enseignants",
    billing: "Facturation", users: "Utilisateurs", centers: "Centres",
    login: "Se connecter", register: "Commencer gratuitement", logout: "Se déconnecter",
    // Teacher-centered nav labels
    today: "Aujourd'hui", learners: "Apprenants", corrections: "Corrections",
    tracking: "Suivi", resources: "Ressources",
  },
  en: {
    home: "Home", courses: "Courses", myClasses: "My Classes", discover: "Explore",
    simulator: "Simulator", progress: "My Progress", settings: "Settings",
    overview: "Overview", students: "Students", assignments: "Assignments",
    generateCourse: "Generate Course", stats: "Statistics", teachers: "Teachers",
    billing: "Billing", users: "Users", centers: "Centers",
    login: "Log in", register: "Get started free", logout: "Log out",
    // Teacher-centered nav labels
    today: "Today", learners: "Learners", corrections: "Corrections",
    tracking: "Tracking", resources: "Resources",
  },
}

// ─── Student dashboard ─────────────────────────────────────────────────────────
const dashboard = {
  fr: {
    xpLabel: "Points XP", lessonsLabel: "Leçons", scoreLabel: "Score moy.", streakLabel: "Jours streak",
    badgesLabel: "Badges", levelLabel: "Niveau actuel",
    launchSim: "Lancer une simulation", simulatorsTitle: "Simulateurs d'ambassade", simulatorsDesc: "Conversations IA avec Herr Bauer",
    skills: "Compétences", detailedProgress: "Progression détaillée", noSkills: "Commencez votre première leçon pour voir vos compétences !",
    joinClassTitle: "Avancer avec un enseignant", joinClassLabel: "Rejoindre une classe", joinClassDesc: "Tu peux apprendre seul, ou rejoindre une classe avec un code donné par ton enseignant ou ton centre.",
    joinCodePlaceholder: "DEUTSCH-A1-XXXX", pendingTitle: "Inscription en attente", pendingDesc: "Votre enseignant doit valider votre demande.",
    rewardsLabel: "Récompenses", badgesTitle: "Badges obtenus", noBadge: "Complétez votre première leçon pour gagner un badge",
    communityLabel: "Communauté", discoverLabel: "🔍 Découvrir",
    grammar: "Grammaire", vocabulary: "Vocabulaire", pronunciation: "Prononciation", comprehension: "Compréhension",
    classesAvailable: "Classes disponibles", classesJoin: "Rejoindre une classe", groupsLabel: "Groupes d'élèves",
    studyGroup: "Étudier en groupe", findPartner: "Trouver un partenaire", soloStudents: "Élèves en solo",
    loading: "Chargement...",
    greetReturn: "Bonjour",
    greetSubtitle: "Ton parcours ne se construit pas en un jour. Aujourd'hui, fais simplement un petit pas.",
    greetEmotional: "Yema est là pour t'aider à apprendre, te préparer et t'intégrer à ton rythme.",
    streakActive: "jours d'affilée — continuez !",
    streakEmpty: "Connecte-toi chaque jour pour construire ta série",
    levelCurrentLabel: "Niveau actuel",
    levelTowardsLabel: "vers",
    levelConfirm: "À confirmer",
    simPracticeTitle: "Pratique orale",
    simPracticeDesc: "Entraîne-toi avec des scénarios réalistes pour gagner en confiance en allemand.",
    ctaTestLevel: "Tester mon niveau",
    ctaFirstLesson: "Commencer ma première leçon →",
    ctaContinue: "Continuer mon parcours",
    ctaSimulator: "Lancer une simulation",
    journeyTitle: "Votre parcours Yema",
    pillar1Label: "Apprendre", pillar1Desc: "Construis tes bases avec des leçons courtes et progressives.",
    pillar2Label: "Se préparer", pillar2Desc: "Pratique des situations réalistes pour gagner en confiance.",
    pillar3Label: "S'intégrer", pillar3Desc: "Bientôt : trouve des partenaires, groupes et ressources pour avancer ensemble.",
    pillar3Badge: "Bientôt",
    communityGroupsSoon: "Bientôt disponible",
    communityPartnerSoon: "Bientôt disponible",
    badgeStreak: "7 jours", badgeFirstA: "Premier A", badgePrecision: "Précision",
    badgeChampion: "Champion", badgeDiamond: "Diamant", badgeRocket: "Fusée",
    progressWidgetTitle: "Ma progression",
    progressZeroTitle: "Tu commences ici",
    progressZeroText: "Ton parcours commence ici. Une première leçon suffit pour lancer ta progression.",
    progressViewDetail: "Voir le détail",
    progressStartA1: "Commencer A1",
    progressTestLevel: "Tester mon niveau",
    progressContinue: "Continuer mon parcours",
    greetNew: "Bienvenue dans ton parcours Yema",
    greetSubtitleNew: "Ton parcours ne se construit pas en un jour. Aujourd'hui, fais simplement un petit pas.",
    greetSubtitleReturn: "Ton parcours ne se construit pas en un jour. Aujourd'hui, fais simplement un petit pas.",
    encouragementPill: "Chaque étape compte.",
    nextStepCardTitle: "Ton prochain pas",
    nextStep1Title: "Commence par connaître ton niveau",
    nextStep1Text: "Fais le test gratuit pour savoir par où commencer.",
    nextStep1CTA: "Tester mon niveau",
    nextStep2Title: "Commence avec une première leçon",
    nextStep2Text: "Quelques minutes suffisent pour poser tes premières bases.",
    nextStep2CTA: "Commencer ma première leçon",
    nextStep3Title: "Continue là où tu t'es arrêté",
    nextStep3Text: "Reprendre aujourd'hui, même quelques minutes, aide à garder le rythme.",
    nextStep3CTA: "Continuer mon parcours",
    progressViewProgress: "Voir ma progression",
    progressLevelLabel: "Niveau",
    progressXpLabel: "XP total",
    progressModulesLabel: "Modules terminés",
    progressDaysLabel: "Jours de pratique",
    progressNextLabel: "Prochaine étape",
    simCTA: "Pratiquer avec le simulateur",
    classCardTitle: "Avancer avec un enseignant",
    classCardText: "Tu peux apprendre seul, ou rejoindre une classe avec un code donné par ton enseignant ou ton centre.",
    classCardCTA: "Rejoindre une classe",
    communityCardTitle: "Bientôt avec Yema Community",
    communityCardText: "Trouve des partenaires d'apprentissage, rejoins des groupes et avance avec des personnes qui ont les mêmes objectifs.",
    actionLearnTitle: "Apprendre",
    actionLearnText: "Reprends tes cours et avance étape par étape.",
    actionLearnCTA: "Voir les cours",
    actionPracticeTitle: "Pratiquer",
    actionPracticeText: "Entraîne-toi à parler en allemand dans des situations réalistes.",
    actionPracticeCTA: "Pratiquer l'oral",
    actionSupportTitle: "Être accompagné",
    actionSupportText: "Rejoins une classe avec un code donné par ton enseignant ou ton centre.",
    actionSupportCTA: "Rejoindre une classe",
    communityTitle: "Bientôt : avancer avec une communauté",
    communityText: "Yema Community permettra de trouver des partenaires d'apprentissage, des groupes et des personnes qui avancent vers les mêmes objectifs.",
  },
  en: {
    xpLabel: "XP earned", lessonsLabel: "Lessons completed", scoreLabel: "Average score", streakLabel: "Day streak",
    badgesLabel: "Badges", levelLabel: "Current level",
    launchSim: "Start a simulation", simulatorsTitle: "AI Simulator", simulatorsDesc: "Practice conversations with AI",
    skills: "Skills", detailedProgress: "Detailed progress", noSkills: "Complete a lesson to start tracking your skills here.",
    joinClassTitle: "Move forward with a teacher", joinClassLabel: "Join a class", joinClassDesc: "You can learn on your own, or join a class with a code shared by your teacher or center.",
    joinCodePlaceholder: "DEUTSCH-A1-XXXX", pendingTitle: "Pending enrollment", pendingDesc: "Your teacher will approve your enrollment shortly.",
    rewardsLabel: "Rewards", badgesTitle: "Your badges", noBadge: "Finish your first lesson to unlock your first badge.",
    communityLabel: "Community", discoverLabel: "🔍 Discover",
    grammar: "Grammar", vocabulary: "Vocabulary", pronunciation: "Pronunciation", comprehension: "Comprehension",
    classesAvailable: "Available classes", classesJoin: "Join a class", groupsLabel: "Study groups",
    studyGroup: "Study in a group", findPartner: "Find a partner", soloStudents: "Solo students",
    loading: "Loading...",
    greetReturn: "Hi",
    greetSubtitle: "Your journey is not built in one day. Today, just take one small step.",
    greetEmotional: "Yema is here to help you learn, prepare and belong at your own pace.",
    streakActive: "days in a row — keep it up!",
    streakEmpty: "Log in every day to build your streak",
    levelCurrentLabel: "Current level",
    levelTowardsLabel: "towards",
    levelConfirm: "To confirm",
    simPracticeTitle: "Speaking practice",
    simPracticeDesc: "Train with realistic scenarios to build confidence in German.",
    ctaTestLevel: "Test my level",
    ctaFirstLesson: "Start my first lesson →",
    ctaContinue: "Continue my path",
    ctaSimulator: "Start a simulation",
    journeyTitle: "Your Yema journey",
    pillar1Label: "Learn", pillar1Desc: "Build your foundation with short, progressive lessons.",
    pillar2Label: "Prepare", pillar2Desc: "Practice realistic situations to gain confidence.",
    pillar3Label: "Belong", pillar3Desc: "Coming soon: find partners, groups and resources to move forward together.",
    pillar3Badge: "Coming soon",
    communityGroupsSoon: "Coming soon",
    communityPartnerSoon: "Coming soon",
    badgeStreak: "7-day streak", badgeFirstA: "First A", badgePrecision: "Precision",
    badgeChampion: "Champion", badgeDiamond: "Diamond", badgeRocket: "Rocket",
    progressWidgetTitle: "My progress",
    progressZeroTitle: "You start here",
    progressZeroText: "Your journey starts here. One first lesson is enough to begin your progress.",
    progressViewDetail: "View details",
    progressStartA1: "Start A1",
    progressTestLevel: "Test my level",
    progressContinue: "Continue my path",
    greetNew: "Welcome to your Yema journey",
    greetSubtitleNew: "Your journey is not built in one day. Today, just take one small step.",
    greetSubtitleReturn: "Your journey is not built in one day. Today, just take one small step.",
    encouragementPill: "Every step matters.",
    nextStepCardTitle: "Your next step",
    nextStep1Title: "Start by knowing your level",
    nextStep1Text: "Take the free test to know where to begin.",
    nextStep1CTA: "Test my level",
    nextStep2Title: "Start with your first lesson",
    nextStep2Text: "A few minutes are enough to build your first foundation.",
    nextStep2CTA: "Start my first lesson",
    nextStep3Title: "Continue where you left off",
    nextStep3Text: "Coming back today, even for a few minutes, helps you keep your rhythm.",
    nextStep3CTA: "Continue my path",
    progressViewProgress: "View my progress",
    progressLevelLabel: "Level",
    progressXpLabel: "Total XP",
    progressModulesLabel: "Completed modules",
    progressDaysLabel: "Practice days",
    progressNextLabel: "Next step",
    simCTA: "Practice with the simulator",
    classCardTitle: "Move forward with a teacher",
    classCardText: "You can learn on your own, or join a class with a code shared by your teacher or center.",
    classCardCTA: "Join a class",
    communityCardTitle: "Coming soon with Yema Community",
    communityCardText: "Find learning partners, join groups and move forward with people working toward similar goals.",
    actionLearnTitle: "Learn",
    actionLearnText: "Return to your lessons and move forward step by step.",
    actionLearnCTA: "View courses",
    actionPracticeTitle: "Practice",
    actionPracticeText: "Train your German speaking skills with realistic situations.",
    actionPracticeCTA: "Practice speaking",
    actionSupportTitle: "Get support",
    actionSupportText: "Join a class with a code shared by your teacher or center.",
    actionSupportCTA: "Join a class",
    communityTitle: "Coming soon: move forward with a community",
    communityText: "Yema Community will help you find learning partners, groups and people working toward similar goals.",
  },
}

// ─── Teacher ───────────────────────────────────────────────────────────────────
const teacher = {
  fr: {
    space: "Espace Enseignant", access: "Accès Professeur · Vérifié", role: "Enseignant · Yema",
    greeting: "Bonjour, {name}", newClass: "+ Nouvelle classe", studentView: "Vue élève",
    myTeacherCode: "Mon code enseignant", myClassCodes: "Codes de mes classes",
    shareCodeStudents: "Partagez ce code aux élèves pour qu'ils vous trouvent sur Découvrir",
    shareClassCode: "Partagez votre code de classe pour inviter des élèves",
    copied: "✓ Copié", copy: "Copier",
    statStudentsLabel: "Apprenants actifs", statAvgLabel: "Moyenne de la classe", statAvgSub: "Sur 10",
    statAssignmentsLabel: "Travaux à corriger", statAssignmentsSub: "En attente de votre retour",
    statCompletionLabel: "Taux de complétion", statCompletionSub: "Modules terminés cette semaine",
    sectionClasses: "Mes Classes", sectionActivity: "Activité récente",
    activityEmpty: "L'activité récente apparaîtra ici",
    classesEmpty: "Vous n'avez pas encore de classe.", createFirstClass: "+ Créer ma première classe →",
    viewAll: "Voir tout →", progressChart: "Progression des classes — 4 semaines",
    progressEmpty: "Les données de progression apparaîtront ici dès que vos apprenants commenceront les leçons.",
    struggling: "⚠️ Apprenants en difficulté", allGood: "Tous les apprenants sont au-dessus de 50% 🎉",
    recentAssignments: "Activités récentes", assignmentsEmpty: "Créez votre première activité depuis la page Corrections.",
    viewStudent: "Voir →", classStudents: "apprenants", classProgress: "progression", classAvgScore: "score moyen",
    loading: "Chargement...",
    // Today page
    aiPill: "L'IA assiste. Vous guidez.",
    todaySubtitle: "Votre rôle est précieux. Yema vous aide à enseigner mieux, pas à vous remplacer.",
    action1Title: "Accompagner", action1Desc: "Suivez la progression de vos apprenants et identifiez qui a besoin de soutien.", action1CTA: "Voir les apprenants",
    action2Title: "Préparer", action2Desc: "Créez une nouvelle activité ou ajustez le programme de vos classes.", action2CTA: "Créer une activité",
    action3Title: "Suivre", action3Desc: "Analysez la progression collective et repérez les lacunes à combler.", action3CTA: "Voir le suivi",
    // Corrections page
    correctionsSubtitle: "Revoyez les travaux de vos apprenants et donnez-leur un retour humain.",
    filterToReview: "À corriger", filterWaiting: "En attente", filterDone: "Terminés", filterAll: "Tous",
    reviewBtn: "Revoir les réponses", prepareActivity: "+ Préparer une activité",
    aiTrustNote: "💡 Yema peut suggérer des pistes de correction. Votre jugement reste déterminant.",
    sampleLabel: "Exemple", statusOpen: "Ouvert", statusClosed: "Fermé",
    deadline: "Échéance", maxScoreLabel: "Note max", submittedLabel: "Rendus", submittedPctLabel: "remis",
    newActivityTitle: "Préparer une activité",
    fieldTitle: "Titre", fieldTitlePh: "Ex : Vocabulaire Lektion 5",
    fieldClass: "Classe", fieldClassPh: "Groupe A1 Matin",
    fieldDue: "Date limite",
    // Tracking page
    trackingSubtitle: "Comprenez où en sont vos apprenants pour mieux les accompagner.",
    demoDataBanner: "Ces données sont des exemples. Vos vraies statistiques apparaîtront ici dès que vos apprenants seront actifs.",
    chartWeeksLabel: "Progression des scores — 4 semaines",
    chartModulesLabel: "Complétion par lektion (A1 vs A2)",
  },
  en: {
    space: "Teacher Space", access: "Teacher Access · Verified", role: "Teacher · Yema",
    greeting: "Hi, {name}", newClass: "+ New class", studentView: "Student view",
    myTeacherCode: "My teacher code", myClassCodes: "My class codes",
    shareCodeStudents: "Share this code with students so they can find you on Discover",
    shareClassCode: "Share your class code to invite students",
    copied: "✓ Copied", copy: "Copy",
    statStudentsLabel: "Active learners", statAvgLabel: "Class average", statAvgSub: "Out of 10",
    statAssignmentsLabel: "Work to review", statAssignmentsSub: "Awaiting your feedback",
    statCompletionLabel: "Completion rate", statCompletionSub: "Modules completed this week",
    sectionClasses: "My Classes", sectionActivity: "Recent activity",
    activityEmpty: "Recent activity will appear here",
    classesEmpty: "You haven't created any classes yet.", createFirstClass: "+ Create your first class →",
    viewAll: "View all →", progressChart: "Class progress — last 4 weeks",
    progressEmpty: "Progress data will show up here once your learners start lessons.",
    struggling: "⚠️ Learners needing support", allGood: "All learners are above 50% 🎉",
    recentAssignments: "Recent activities", assignmentsEmpty: "Create your first activity from the Corrections page.",
    viewStudent: "View →", classStudents: "learners", classProgress: "progress", classAvgScore: "avg score",
    loading: "Loading...",
    // Today page
    aiPill: "AI assists. You guide.",
    todaySubtitle: "Your role matters. Yema helps you teach better — it doesn't replace you.",
    action1Title: "Guide", action1Desc: "Follow your learners' progress and identify who needs support.", action1CTA: "View learners",
    action2Title: "Prepare", action2Desc: "Create a new activity or adjust the programme for your classes.", action2CTA: "Create activity",
    action3Title: "Track", action3Desc: "Analyse collective progress and spot the gaps worth addressing.", action3CTA: "View tracking",
    // Corrections page
    correctionsSubtitle: "Review your learners' work and give them real, human feedback.",
    filterToReview: "To review", filterWaiting: "Waiting", filterDone: "Completed", filterAll: "All",
    reviewBtn: "Review responses", prepareActivity: "+ Prepare an activity",
    aiTrustNote: "💡 Yema can offer correction hints. Your judgment is what counts.",
    sampleLabel: "Sample", statusOpen: "Open", statusClosed: "Closed",
    deadline: "Due", maxScoreLabel: "Max score", submittedLabel: "Submitted", submittedPctLabel: "submitted",
    newActivityTitle: "Prepare an activity",
    fieldTitle: "Title", fieldTitlePh: "E.g.: Vocabulary Lesson 5",
    fieldClass: "Class", fieldClassPh: "Group A1 Morning",
    fieldDue: "Deadline",
    // Tracking page
    trackingSubtitle: "Understand where your learners stand so you can support them better.",
    demoDataBanner: "These are sample figures. Your real data will appear here once your learners are active.",
    chartWeeksLabel: "Score progression — 4 weeks",
    chartModulesLabel: "Completion by lesson (A1 vs A2)",
  },
}

// ─── Center ────────────────────────────────────────────────────────────────────
const center = {
  fr: {
    portal: "Portail Centre", partnerBadge: "⭐ Centre Partenaire", verified: "✓ Vérifié",
    dashboard: "Tableau de bord", proPlan: "⭐ Plan Pro",
    registrationCode: "Code d'inscription de votre centre",
    shareCodeStudents: "Partagez ce code à vos élèves — ils le saisissent lors de leur inscription sur Yema.",
    viewStudents: "Voir les élèves →", copied: "✓ Copié !", copy: "Copier",
    statTeachers: "Enseignants actifs", statStudents: "Élèves inscrits", statClasses: "Classes actives",
    statRevenue: "Revenus du mois", statRevenueSub: "Monétisation à venir",
    registrationsChart: "Évolution des inscriptions", registrationsEmpty: "Les statistiques d'inscription apparaîtront ici au fur et à mesure.",
    alerts: "Alertes & Notifications", noAlerts: "Aucune alerte pour le moment",
    teachersList: "Enseignants du centre", noTeachers: "Aucun enseignant associé au centre pour l'instant.",
    viewAll: "Voir tout →", studentPortal: "← Portail élève", directorRole: "Directeur · CENTER_MANAGER",
    tableTeacher: "Enseignant", tableSpecialty: "Spécialité", tableClasses: "Classes",
    tableStudents: "Élèves", tableAvgScore: "Score moy.", tableStatus: "Statut",
    overview: "Vue d'ensemble", loading: "Chargement...",
  },
  en: {
    portal: "Center Portal", partnerBadge: "⭐ Partner Center", verified: "✓ Verified",
    dashboard: "Dashboard", proPlan: "⭐ Pro Plan",
    registrationCode: "Your center registration code",
    shareCodeStudents: "Share this code with your students — they enter it during registration on Yema.",
    viewStudents: "View students →", copied: "✓ Copied!", copy: "Copy",
    statTeachers: "Active teachers", statStudents: "Enrolled students", statClasses: "Active classes",
    statRevenue: "Monthly revenue", statRevenueSub: "Payments launching soon",
    registrationsChart: "Enrollment trends", registrationsEmpty: "Enrollment stats will appear here as your center grows.",
    alerts: "Alerts & Notifications", noAlerts: "No alerts right now",
    teachersList: "Center teachers", noTeachers: "No teachers added yet.",
    viewAll: "View all →", studentPortal: "← Student portal", directorRole: "Director · Center Manager",
    tableTeacher: "Teacher", tableSpecialty: "Specialty", tableClasses: "Classes",
    tableStudents: "Students", tableAvgScore: "Avg score", tableStatus: "Status",
    overview: "Overview", loading: "Loading...",
  },
}

// ─── Admin ─────────────────────────────────────────────────────────────────────
const admin = {
  fr: {
    navOverview: "Vue d'ensemble", navUsers: "Utilisateurs", navCourses: "Cours & Contenu",
    navValidations: "Validations", navSystem: "Système", backToSite: "← Retour au site",
    greeting: "👋 Bonjour, Admin",
    kpiTotal: "Total utilisateurs", kpiStudents: "Élèves actifs", kpiTeachers: "Enseignants",
    kpiCenters: "Centres", kpiSessions: "Sessions aujourd'hui",
    kpiTotalSub: "ce mois", kpiStudentsSub: "inscrits", kpiTeachersSub: "vérifiés",
    kpiCentersSub: "partenaires", kpiSessionsSub: "moy.",
    chartMonthly: "📈 Inscriptions mensuelles", chartSeriesUsers: "Utilisateurs",
    chartLevels: "🎯 Niveaux CEFR", chartWeekly: "📅 Activité cette semaine",
    chartSeriesStudents: "Élèves", chartSeriesTeachers: "Enseignants", chartSeriesCenters: "Centres",
    recentActivity: "🔔 Activité récente", recentActivityEmpty: "L'activité récente apparaîtra ici",
    topCities: "🌍 Top villes", topCitiesEmpty: "Données géographiques — bientôt disponibles",
    usersTitle: "👥 Utilisateurs", searchPlaceholder: "Rechercher un utilisateur...",
    filterAll: "Tous les rôles", filterStudents: "Élèves", filterTeachers: "Enseignants", filterCenters: "Centres",
    quickStatNew: "Nouveaux aujourd'hui",
    tableUser: "Utilisateur", tableRole: "Rôle", tableLevel: "Niveau", tableCity: "Ville",
    tableDate: "Inscription", tableStatus: "Statut", tableActions: "Actions",
    statusActive: "Actif", statusPending: "En attente",
    roleLabelStudent: "Élève", roleLabelTeacher: "Enseignant", roleLabelCenter: "Centre", roleLabelAdmin: "Admin",
    actionView: "Voir", actionEdit: "Modifier", actionBlock: "Bloquer",
    coursesTitle: "📚 Cours & Contenu", generateBtn: "✨ Générer avec IA",
    kpiCoursesTotal: "Cours total", kpiPublished: "Publiés", kpiDraft: "Brouillons", kpiModules: "Modules total",
    levelGenerated: "Généré par IA", levelGeneratedSuffix: "générés", generateCourseBtn: "+ Générer",
    validationsTitle: "✅ Validations en attente", noValidations: "✅ Aucune validation en attente",
    validTypeCenter: "Centre", validTypeTeacher: "Enseignant",
    validateBtn: "✅ Valider", rejectBtn: "❌ Refuser",
    systemTitle: "⚙️ Système", apisTitle: "🔌 APIs configurées",
    apiStatusActive: "Actif", apiStatusPending: "À configurer",
    pagesTitle: "📄 Pages de la plateforme", envTitle: "🔐 Variables d'environnement",
    pageDashboardStudent: "Dashboard élève", pageCourses: "Cours", pageSimulator: "Simulateur IA",
    pageDiscover: "Découvrir", pageProgress: "Progression",
    pageDashboardTeacher: "Dashboard enseignant", pageDashboardCenter: "Dashboard centre",
    pageQuiz: "Quiz adaptatif", pageVideos: "Vidéos Remotion", pagePricing: "Tarifs",
  },
  en: {
    navOverview: "Overview", navUsers: "Users", navCourses: "Courses & Content",
    navValidations: "Validations", navSystem: "System", backToSite: "← Back to site",
    greeting: "👋 Hello, Admin",
    kpiTotal: "Total users", kpiStudents: "Active students", kpiTeachers: "Teachers",
    kpiCenters: "Centers", kpiSessions: "Sessions today",
    kpiTotalSub: "this month", kpiStudentsSub: "enrolled", kpiTeachersSub: "verified",
    kpiCentersSub: "partners", kpiSessionsSub: "avg.",
    chartMonthly: "📈 Monthly registrations", chartSeriesUsers: "Users",
    chartLevels: "🎯 CEFR Levels", chartWeekly: "📅 Activity this week",
    chartSeriesStudents: "Students", chartSeriesTeachers: "Teachers", chartSeriesCenters: "Centers",
    recentActivity: "🔔 Recent activity", recentActivityEmpty: "Recent activity will appear here",
    topCities: "🌍 Top cities", topCitiesEmpty: "Geographic data — coming soon",
    usersTitle: "👥 Users", searchPlaceholder: "Search a user...",
    filterAll: "All roles", filterStudents: "Students", filterTeachers: "Teachers", filterCenters: "Centers",
    quickStatNew: "New today",
    tableUser: "User", tableRole: "Role", tableLevel: "Level", tableCity: "City",
    tableDate: "Registered", tableStatus: "Status", tableActions: "Actions",
    statusActive: "Active", statusPending: "Pending",
    roleLabelStudent: "Student", roleLabelTeacher: "Teacher", roleLabelCenter: "Center", roleLabelAdmin: "Admin",
    actionView: "View", actionEdit: "Edit", actionBlock: "Block",
    coursesTitle: "📚 Courses & Content", generateBtn: "✨ Generate with AI",
    kpiCoursesTotal: "Total courses", kpiPublished: "Published", kpiDraft: "Drafts", kpiModules: "Total modules",
    levelGenerated: "AI generated", levelGeneratedSuffix: "generated", generateCourseBtn: "+ Generate",
    validationsTitle: "✅ Pending validations", noValidations: "✅ No pending validations",
    validTypeCenter: "Center", validTypeTeacher: "Teacher",
    validateBtn: "✅ Approve", rejectBtn: "❌ Reject",
    systemTitle: "⚙️ System", apisTitle: "🔌 Configured APIs",
    apiStatusActive: "Active", apiStatusPending: "Not configured",
    pagesTitle: "📄 Platform pages", envTitle: "🔐 Environment variables",
    pageDashboardStudent: "Student dashboard", pageCourses: "Courses", pageSimulator: "AI Simulator",
    pageDiscover: "Discover", pageProgress: "Progress",
    pageDashboardTeacher: "Teacher dashboard", pageDashboardCenter: "Center dashboard",
    pageQuiz: "Adaptive quiz", pageVideos: "Remotion videos", pagePricing: "Pricing",
  },
}

// ─── Common ────────────────────────────────────────────────────────────────────
const common = {
  fr: {
    loading: "Chargement...", error: "Une erreur est survenue", retry: "Réessayer",
    save: "Sauvegarder", cancel: "Annuler", confirm: "Confirmer", back: "Retour",
    next: "Suivant", finish: "Terminer", yes: "Oui", no: "Non", or: "ou",
    search: "Rechercher", filter: "Filtrer", viewAll: "Voir tout", comingSoon: "Bientôt disponible",
    free: "Gratuit", premium: "Premium", new: "Nouveau", beta: "Bêta", active: "Actif", inactive: "Inactif",
  },
  en: {
    loading: "Loading...", error: "An error occurred", retry: "Retry",
    save: "Save", cancel: "Cancel", confirm: "Confirm", back: "Back",
    next: "Next", finish: "Done", yes: "Yes", no: "No", or: "or",
    search: "Search", filter: "Filter", viewAll: "View all", comingSoon: "Coming soon",
    free: "Free", premium: "Premium", new: "New", beta: "Beta", active: "Active", inactive: "Inactive",
  },
}

// ─── Auth ──────────────────────────────────────────────────────────────────────
const auth = {
  fr: {
    loginTitle: "Bon retour !", loginSubtitle: "Continuez votre apprentissage",
    email: "Adresse email", emailPlaceholder: "toi@example.com",
    password: "Mot de passe", passwordPlaceholder: "••••••••",
    loginBtn: "Se connecter", loginLoading: "Connexion...",
    noAccount: "Pas encore de compte ?", subscribe: "S'inscrire",
    chooseRole: "Je suis...", chooseRoleHint: "Qui êtes-vous ? Choisissez votre profil 👇",
    roleStudent: "Apprenant", roleStudentDesc: "Je veux apprendre l'allemand",
    roleTeacher: "Enseignant", roleTeacherDesc: "J'enseigne l'allemand",
    roleCenter: "Centre de langues", roleCenterDesc: "Je représente un centre",
    registerTitle: "Créez votre compte", registerSubtitle: "Commence ton voyage linguistique",
    registerBtn: "Créer mon compte", registerLoading: "Création du compte...",
    fullName: "Nom complet", fullNamePlaceholder: "Paul Nkengue", passwordMin: "Min. 6 caractères",
    passwordError: "Le mot de passe doit contenir au moins 6 caractères.",
    hasAccount: "Déjà un compte ?", signIn: "Se connecter", changeRole: "← Changer",
    confirmTitle: "Vérifie ta boîte mail ✉️", confirmSent: "Un lien de confirmation a été envoyé à",
    confirmClick: "Clique sur le lien pour activer ton compte et accéder à l'espace",
    backToLogin: "Retour à la connexion", createAccount: "Créer un compte",
    errorInvalid: "Email ou mot de passe incorrect.",
  },
  en: {
    loginTitle: "Welcome back", loginSubtitle: "Continue your learning journey",
    email: "Email address", emailPlaceholder: "you@example.com",
    password: "Password", passwordPlaceholder: "••••••••",
    loginBtn: "Log in", loginLoading: "Signing in...",
    noAccount: "New here?", subscribe: "Create an account",
    chooseRole: "Who are you?", chooseRoleHint: "Pick the option that describes you",
    roleStudent: "I'm a learner", roleStudentDesc: "Learning a language, A1 to C1",
    roleTeacher: "I'm a teacher", roleTeacherDesc: "I teach languages and manage classes",
    roleCenter: "I manage a center", roleCenterDesc: "Running a language school or institute",
    registerTitle: "Create your account", registerSubtitle: "Start your language journey",
    registerBtn: "Create account", registerLoading: "Creating your account...",
    fullName: "Full name", fullNamePlaceholder: "Paul Nkengue", passwordMin: "At least 6 characters",
    passwordError: "Your password must be at least 6 characters.",
    hasAccount: "Already have an account?", signIn: "Log in", changeRole: "← Back",
    confirmTitle: "Check your inbox ✉️", confirmSent: "We sent a confirmation link to",
    confirmClick: "Click the link to activate your account and get started.",
    backToLogin: "Back to login", createAccount: "Create account",
    errorInvalid: "Wrong email or password. Please try again.",
  },
}

// ─── Layout (sidebar) ──────────────────────────────────────────────────────────
const layout = {
  fr: {
    searchPlaceholder: "Rechercher un cours, un scénario...", goethe: "CEFR · A1 → C1",
    userFallback: "Utilisateur", studentBadge: "✅ Élève inscrit",
    pendingBadge: "⏳ Validation en cours", groupLeader: "👥 Chef de groupe",
    solo: "Solo", levelPrefix: "Niveau",
    teacherRole: "👨‍🏫 Enseignant", centerRole: "⭐ Centre", adminRole: "🛡️ Admin",
  },
  en: {
    searchPlaceholder: "Search...", goethe: "CEFR · A1 → C1",
    userFallback: "User", studentBadge: "✅ Enrolled learner",
    pendingBadge: "⏳ Pending validation", groupLeader: "👥 Group leader",
    solo: "Solo", levelPrefix: "Level",
    teacherRole: "👨‍🏫 Teacher", centerRole: "⭐ Center", adminRole: "🛡️ Admin",
  },
}

// ─── All text ──────────────────────────────────────────────────────────────────
export const TEXT = {
  fr: { landing: landing.fr, nav: nav.fr, dashboard: dashboard.fr, teacher: teacher.fr, center: center.fr, admin: admin.fr, common: common.fr, auth: auth.fr, layout: layout.fr },
  en: { landing: landing.en, nav: nav.en, dashboard: dashboard.en, teacher: teacher.en, center: center.en, admin: admin.en, common: common.en, auth: auth.en, layout: layout.en },
}

export type Locale = "fr" | "en"
export type TextBundle = typeof TEXT.fr

// ─── Hook ──────────────────────────────────────────────────────────────────────
// Reads locale directly from the URL path — no next-intl context needed.
// Works on every navigation: /fr/... = French, /en/... = English.
export function useT(): TextBundle {
  const pathname = usePathname()
  const locale: Locale = pathname.startsWith("/en") ? "en" : "fr"
  return TEXT[locale]
}
