"use client"
import { usePathname } from "next/navigation"

// Micro-typo FR (§1.11 doctrine v2) : espace fine insécable avant : ; ! ? %.
// Appliqué en profondeur au sous-arbre landing.fr uniquement (le reste
// touche l'app connectée et n'a pas besoin de sweep landing).
const NNBSP = " ";
function frTypo(s: string): string {
  return s.replace(/ ([:;!?%€°])/g, `${NNBSP}$1`);
}
type Deep<T> = { [K in keyof T]: T[K] extends string ? string : Deep<T[K]> };
function deepTypo<T extends Record<string, unknown>>(obj: T): Deep<T> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (typeof v === "string") out[k] = frTypo(v);
    else if (Array.isArray(v)) out[k] = v.map((x) => (typeof x === "string" ? frTypo(x) : x));
    else if (v && typeof v === "object") out[k] = deepTypo(v as Record<string, unknown>);
    else out[k] = v;
  }
  return out as Deep<T>;
}

// ─── Landing page ─────────────────────────────────────────────────────────────
const landing = {
  fr: {
    badge: "1re plateforme africaine des langues · Bêta 2026",
    title: "L’Afrique parle.",
    titleAccent: "Toutes ses langues.",
    subtitle: "YEMA est la plateforme africaine d’apprentissage des langues — du monde ET africaines — propulsée par l’IA. Valoriser les langues du continent, ouvrir ses portes sur le monde.",
    subtitle2: "Premier chapitre en cours : l’allemand, de A1 à C1. Prochains : anglais, wolof, bassa, swahili, lingala.",
    ctaPrimary: "Commencer",
    ctaSecondary: "Voir les langues",
    ctaMicro: "Test gratuit après inscription.",
    connexion: "Connexion",
    getStarted: "Démarrer",
    navFeatures: "Langues",
    navLevels: "Méthode",
    navPricing: "Manifeste",
    navCenters: "Centres",
    b2bLabel: "Solution B2B",
    statsUsers: "Apprenants",
    statsLevels: "Niveaux CEFR",
    statsSuccess: "Taux de réussite",
    statsCenters: "Centres partenaires",
    stat1Value: "1re", stat1Label: "plateforme africaine",
    stat2Value: "6", stat2Label: "langues au programme",
    stat3Value: "2", stat3Label: "familles · étrangères · natales",
    stat4Value: "IA", stat4Label: "au cœur du parcours",
    featuresTitle: "Ce que vous allez vraiment apprendre",
    featuresSubtitle: "8 outils conçus pour une progression concrète — pas juste de la théorie.",
    feature1Title: "Pratique orale guidée", feature1Desc: "Conversez avec un interlocuteur IA en allemand. Progression adaptée à votre niveau — sans pression, sans jugement.", feature1Badge: "IA",
    feature2Title: "Audio allemand authentique", feature2Desc: "Des voix natives, des dialogues réels. Entraînez votre oreille à l'allemand du quotidien.",
    feature3Title: "Correction vocale en temps réel", feature3Desc: "Parlez, l'IA vous corrige immédiatement. Votre accent et votre fluidité s'améliorent leçon après leçon.", feature3Badge: "IA",
    feature4Title: "Coaching écriture IA", feature4Desc: "Rédigez en allemand. Le coach IA Yema vous explique chaque correction avec des exemples contextuels.", feature4Badge: "IA",
    feature5Title: "Quiz qui s'adapte à vous", feature5Desc: "Plus vous progressez, plus le niveau s'ajuste. Chaque session cible vos vraies lacunes.", feature5Badge: "Adaptatif",
    feature6Title: "Classes virtuelles", feature6Desc: "Rejoignez la classe d'un enseignant ou créez votre groupe d'étude. Progression collective visible.", feature6Badge: "Bientôt",
    feature7Title: "Solution centres de langues", feature7Desc: "Un tableau de bord pour gérer enseignants, élèves et classes. Idéal pour les instituts de formation.", feature7Badge: "B2B",
    feature8Title: "Suivi de vos 5 compétences", feature8Desc: "Mesurez vos progrès sur Lecture, Écoute, Expression orale, Écriture et Grammaire.", feature8Badge: "Insights",
    levelsTitle: "Premier chapitre : l'allemand",
    levelsSubtitle: "Contenu pédagogique original aligné sur le CECRL (A1 → C1). Prochains chapitres — anglais, wolof, bassa, swahili, lingala — auront leur programme dédié.",
    available: "Disponible", locked: "Bientôt", modules: "modules",
    level1Name: "Débutant", level1Desc: "Salutations, famille, chiffres, routine quotidienne",
    level2Name: "Élémentaire", level2Desc: "Vie urbaine, médias, santé, voyages",
    level3Name: "Intermédiaire", level3Desc: "Travail, société, culture, environnement",
    level4Name: "Avancé", level4Desc: "Sciences, économie, médias, histoire",
    level5Name: "Maîtrise", level5Desc: "Philosophie, littérature, carrière internationale",
    visionTitle: "Une plateforme. Trois ambitions.",
    visionSubtitle: "YEMA n'est pas une application de vocabulaire de plus. C'est un parcours pour ouvrir sur le monde et revenir chez soi — dans la langue de ton choix.",
    vision1Label: "Apprendre", vision1Title: "Des bases solides", vision1Desc: "Un programme structuré, aligné CECRL pour les langues du monde et sur l'échelle YEMA (É1→É5) pour les africaines. Oral, écrit, audio — bâtir de vraies compétences.",
    vision2Label: "Se préparer", vision2Title: "Pour un vrai objectif", vision2Desc: "Études, travail, famille, retour aux sources : chaque parcours part d'un besoin concret. YEMA adapte le contenu à ton projet, pas l'inverse.",
    vision3Label: "S'intégrer", vision3Title: "La langue, la culture, le quotidien", vision3Desc: "Comprendre l'Allemagne, comme comprendre les codes du Ndolo ou d'un salon dakarois. Chaque module accueille la culture qui porte la langue.",
    germanyTitle: "Pourquoi l'Allemagne ?",
    germanyText: "L'Allemagne est l'une des destinations les plus accessibles pour étudier, travailler ou s'installer en Europe. Maîtriser l'allemand est la clé.",
    germany1: "Plus de 400 universités, dont beaucoup proposent des cursus gratuits ou peu coûteux",
    germany2: "Des opportunités professionnelles dans l'ingénierie, la santé et l'informatique",
    germany3: "Une communauté internationale bien établie, facilitant l'intégration",
    germany4: "Niveau B1 minimum requis pour la majorité des démarches universitaires et professionnelles",
    testimonialsTitle: "Ce que Yema veut résoudre",
    testimonial1Text: "", testimonial1Role: "",
    testimonial2Text: "", testimonial2Role: "",
    testimonial3Text: "", testimonial3Role: "",
    problem1Title: "Les cours classiques ne suffisent pas",
    problem1Desc: "Les méthodes traditionnelles enseignent la grammaire, mais pas comment parler ou comprendre un Allemand dans la vraie vie.",
    problem2Title: "Les ressources coûtent cher",
    problem2Desc: "Manuels importés, cours particuliers, abonnements en devises — apprendre l'allemand reste inaccessible pour beaucoup.",
    problem3Title: "Les plateformes ignorent votre contexte réel",
    problem3Desc: "La plupart des applications ne sont pas conçues pour des apprenants préparant un projet concret : études en Allemagne, mobilité professionnelle, regroupement familial.",
    simTitle: "Fonctionnalité phare", simHeadline: "Entraînez-vous en allemand avec l'IA",
    simDesc: "Notre assistant IA vous met en situation réelle : conversations, vocabulaire des démarches administratives, expressions du quotidien. Chaque réponse est analysée et corrigée pour vous faire progresser.",
    simCta: "Essayer gratuitement →", simConsulOnline: "Assistant IA · En ligne",
    simMsg1: "Bonjour. Pouvez-vous vous présenter ?", simMsg2: "Bonjour. Je m'appelle Paul, je viens du Cameroun.", simMsg3: "Pourquoi souhaitez-vous apprendre l'allemand ?",
    simScoreLabel: "Score en direct", simGrammar: "Grammaire", simVocab: "Vocab", simRelevance: "Pertinence",
    simVisa1: "Vocabulaire des démarches administratives", simVisa2: "Expressions du monde du travail", simVisa3: "Vie quotidienne et intégration", simVisa4: "Études et parcours universitaire", simVisa5: "Culture et codes sociaux allemands",
    centerTitle: "Vous êtes un centre de langues ou un enseignant ?",
    centerDesc: "Yema accompagne les centres avec des outils digitaux pour suivre les apprenants, soutenir les enseignants et structurer la progression.",
    centerFeature1: "Espace dédié pour votre centre", centerFeature2: "Suivi des apprenants en temps réel", centerFeature3: "Support pour les enseignants", centerFeature4: "Accès aux parcours Yema (A1→C1)", centerFeature5: "Accompagnement adapté à vos besoins",
    centerCta: "Demander un devis →", centerOnDemand: "Sur devis", centerPerMonth: "/mois",
    centerReassurance: "Le tarif dépend du nombre d'apprenants, d'enseignants et des fonctionnalités nécessaires.",
    centerAudience1Label: "Apprenants", centerAudience1Desc: "Apprenez à votre rythme avec des cours en ligne, de la pratique orale et un suivi de progression.",
    centerAudience2Label: "Enseignants", centerAudience2Desc: "Utilisez Yema comme outil de support numérique pour guider vos apprenants et structurer leur progression.",
    centerAudience3Label: "Centres", centerAudience3Desc: "Gérez classes, enseignants et apprenants depuis un espace dédié.",
    faqTitle: "Questions fréquentes",
    faq1Q: "Comment fonctionne l'entraînement oral avec l'IA ?", faq1A: "Vous conversez avec notre assistant IA en allemand. Il analyse votre réponse, signale les erreurs de grammaire et de vocabulaire, et vous suggère des formulations plus naturelles — en temps réel.",
    faq2Q: "Le plan gratuit est-il vraiment gratuit ?", faq2A: "Oui, totalement gratuit. Pas de carte bancaire requise. Accès complet au niveau A1 avec 3 leçons par jour.",
    faq3Q: "Yema prépare-t-il aux examens de langue allemande ?", faq3A: "Yema développe vos compétences orales et écrites en allemand, alignées sur le Cadre CECRL (A1-C1). Nous sommes une plateforme indépendante. Pour les certifications officielles, renseignez-vous auprès des organismes accrédités dans votre pays.",
    faq4Q: "Puis-je rejoindre la classe d'un enseignant ?", faq4A: "Oui. Entrez le code de classe de votre enseignant lors de l'inscription ou depuis votre tableau de bord. Votre enseignant validera votre accès.",
    faq5Q: "Y a-t-il une application mobile ?", faq5A: "La plateforme est entièrement optimisée pour mobile via le navigateur. Une application native est en cours de développement.",
    faq6Q: "Comment devenir centre partenaire ?", faq6A: "Contactez-nous via WhatsApp ou email. Nous proposons un accès découverte gratuit pour tester la solution avec votre équipe avant tout engagement.",
    ctaFinalTitle: "Apprendre. Se préparer.", ctaFinalSub: "S'intégrer.",
    ctaFinalDesc: "Pas de carte bancaire. Pas d'engagement. Accès immédiat au niveau A1 complet.",
    ctaFinalBtn: "Rejoins la bêta", ctaFinalSocial: "Sans carte bancaire · A1 gratuit · CECRL A1→C1",
    ctaFinalAppLabel: "Bientôt disponible sur", ctaFinalCities: "Bêta ouverte à toute l'Afrique — de Douala à Dakar, de Kinshasa à Abidjan.",
    footerTagline: "Apprendre. Se préparer. S'intégrer.",
    footerDisclaimer: "Yema Languages propose une pratique linguistique indépendante alignée sur le CECRL et n'est affiliée à aucun organisme officiel d'examen.",
    footerMade: "L'Afrique parle. De Douala à Dakar, de Kinshasa à Abidjan.", footerLegal: "Mentions légales", footerTerms: "CGU", footerPrivacy: "Confidentialité", footerContact: "Contact",
  },
  en: {
    badge: "1st pan-African languages platform · Beta 2026",
    title: "Africa speaks.",
    titleAccent: "All its languages.",
    subtitle: "YEMA is the pan-African language learning platform — foreign AND native — powered by AI. Celebrate the continent’s languages, open doors to the world.",
    subtitle2: "First chapter live: German, A1 to C1. Next: English, Wolof, Bassa, Swahili, Lingala.",
    ctaPrimary: "Start",
    ctaSecondary: "See the languages",
    ctaMicro: "Free test after registration.",
    connexion: "Log in",
    getStarted: "Get started",
    navFeatures: "Languages",
    navLevels: "Method",
    navPricing: "Manifesto",
    navCenters: "Centers",
    b2bLabel: "Learners · Teachers · Centers",
    statsUsers: "Learners",
    statsLevels: "CEFR Levels",
    statsSuccess: "Success rate",
    statsCenters: "Partner centers",
    stat1Value: "1st", stat1Label: "pan-African platform",
    stat2Value: "6", stat2Label: "languages in the pipeline",
    stat3Value: "2", stat3Label: "families · foreign · native",
    stat4Value: "AI", stat4Label: "at the heart of the journey",
    featuresTitle: "Tools to progress with confidence",
    featuresSubtitle: "From speaking practice to real-life situations — tools to build real skills.",
    feature1Title: "Train with real-life situations", feature1Desc: "Work on conversations useful for daily life, studies and practical procedures in Germany.", feature1Badge: "Practice",
    feature2Title: "Listen and learn", feature2Desc: "Audio content with native German voices, calibrated for your level.",
    feature3Title: "Practice speaking", feature3Desc: "Speak out loud and get instant feedback to improve your pronunciation and fluency.", feature3Badge: "Speaking",
    feature4Title: "Correct your writing", feature4Desc: "Understand your grammar and vocabulary errors with clear, detailed explanations.", feature4Badge: "AI",
    feature5Title: "Learn with a clear path", feature5Desc: "Progress step by step with short lessons designed around the CEFR A1 framework.", feature5Badge: "Structured",
    feature6Title: "Move at your own pace", feature6Desc: "Learn online in a more flexible and accessible way than traditional classroom courses.", feature6Badge: "",
    feature7Title: "For teachers and centers", feature7Desc: "Digital tools to support, guide and manage learners in a structured way.", feature7Badge: "B2B",
    feature8Title: "Track your progress", feature8Desc: "See what you have learned, your strengths and the skills still to improve.", feature8Badge: "Insights",
    levelsTitle: "A CEFR-aligned learning path",
    levelsSubtitle: "Recognized levels to help you progress from beginner to advanced.",
    available: "Available", locked: "Coming soon", modules: "modules",
    level1Name: "Beginner", level1Desc: "Introduce yourself, talk about your family and understand simple sentences.",
    level2Name: "Elementary", level2Desc: "Communicate in common everyday situations.",
    level3Name: "Intermediate", level3Desc: "Interact with more independence in personal, professional or administrative situations.",
    level4Name: "Advanced", level4Desc: "Express opinions, explain projects and understand more complex content.",
    level5Name: "Mastery", level5Desc: "Communicate with ease in academic, professional or advanced integration contexts.",
    visionTitle: "One platform for the whole journey",
    visionSubtitle: "Learning a language is only the beginning. Yema combines learning, preparation and integration.",
    vision1Label: "Yema Languages", vision1Title: "Learn", vision1Desc: "Structured lessons, interactive exercises and AI tools to help you progress in the language.",
    vision2Label: "Yema Coach · coming soon", vision2Title: "Prepare", vision2Desc: "Simulations, checklists and soon personal coaches to help you prepare for your goals abroad.",
    vision3Label: "Yema Community · coming soon", vision3Title: "Belong", vision3Desc: "A future community to find learning partners, connect with the diaspora and move forward together.",
    germanyTitle: "First destination: Germany",
    germanyText: "For the beta, Yema focuses on German and practical situations useful for studying, working, living or growing in Germany.",
    germany1: "A1 lessons to get started",
    germany2: "Speaking practice with feedback",
    germany3: "Real-life situations",
    germany4: "Useful paths for students, workers and diaspora",
    testimonialsTitle: "What Yema is built to solve",
    testimonial1Text: "", testimonial1Role: "",
    testimonial2Text: "", testimonial2Role: "",
    testimonial3Text: "", testimonial3Role: "",
    problem1Title: "Traditional courses are not enough",
    problem1Desc: "Standard methods teach grammar but not how to actually speak or understand real conversations with native speakers.",
    problem2Title: "Quality resources are out of reach",
    problem2Desc: "Textbooks, private lessons and foreign-currency subscriptions keep quality language learning inaccessible for many.",
    problem3Title: "Platforms ignore your context",
    problem3Desc: "Most language apps are not built for learners in Africa preparing for an international life project.",
    simTitle: "Practice", simHeadline: "Practice realistic conversations",
    simDesc: "Yema helps you practice situations inspired by real life: introductions, personal questions, study goals, work, housing and practical procedures.",
    simCta: "Try the simulator →", simConsulOnline: "AI Assistant · Online",
    simMsg1: "Hello! Could you introduce yourself?", simMsg2: "Hello. My name is Paul, I'm from Cameroon.", simMsg3: "Why do you want to learn German?",
    simScoreLabel: "Live score", simGrammar: "Grammar", simVocab: "Vocabulary", simRelevance: "Relevance",
    simVisa1: "Daily introductions", simVisa2: "Study goals and university life", simVisa3: "Work and professional situations", simVisa4: "Housing and practical procedures", simVisa5: "Building confidence in German",
    centerTitle: "For learners, teachers and centers",
    centerDesc: "Yema helps learners progress independently while giving teachers and centers digital tools to support and structure learning.",
    centerFeature1: "Learn at your own pace with online lessons, speaking practice and progress tracking.", centerFeature2: "Use Yema as a digital support tool to guide learners and structure their progression.", centerFeature3: "Manage classes, teachers and learners through a dedicated space.", centerFeature4: "Mobile-friendly for all learners", centerFeature5: "Partner center access · coming soon",
    centerCta: "Request a demo →", centerOnDemand: "On request", centerPerMonth: "/month",
    centerReassurance: "Pricing depends on the number of learners, teachers and features needed.",
    centerAudience1Label: "Learners", centerAudience1Desc: "Learn at your own pace with online lessons, speaking practice and progress tracking.",
    centerAudience2Label: "Teachers", centerAudience2Desc: "Use Yema as a digital support tool to guide learners and structure their progression.",
    centerAudience3Label: "Centers", centerAudience3Desc: "Manage classes, teachers and learners through a dedicated space.",
    faqTitle: "Common questions",
    faq1Q: "How does speaking practice work?", faq1A: "You interact with an AI assistant in German. It analyzes your responses, flags grammar and vocabulary errors, and suggests more natural phrasing in real time. Sessions are designed to build confidence through practice.",
    faq2Q: "Is the free plan actually free?", faq2A: "Yes — completely free. No credit card required. Full access to A1 with 3 lessons per day.",
    faq3Q: "Does Yema prepare you for German language exams?", faq3A: "Yema develops your spoken and written German skills, aligned with the CEFR framework (A1-C1). We are an independent platform. For official certifications, contact accredited examination bodies in your country.",
    faq4Q: "Can I join a teacher's class?", faq4A: "Absolutely. Enter your teacher's class code when you sign up or from your dashboard. Your teacher approves your enrollment.",
    faq5Q: "Is there a mobile app?", faq5A: "The platform works great on mobile (iOS and Android) through your browser. A native app is on the roadmap.",
    faq6Q: "How do I become a partner center?", faq6A: "Reach out on WhatsApp or email. We offer a free discovery period to try the solution with your team — no commitment.",
    ctaFinalTitle: "Learn. Prepare.", ctaFinalSub: "Belong.",
    ctaFinalDesc: "No credit card. No commitment. Full A1 access — start today.",
    ctaFinalBtn: "Join the beta", ctaFinalSocial: "Beta access · Free A1 · CEFR aligned",
    ctaFinalAppLabel: "Coming soon on", ctaFinalCities: "Starting with German and Germany — more languages coming.",
    footerTagline: "Learn. Prepare. Belong.",
    footerDisclaimer: "Yema Languages provides independent CEFR-aligned language practice and is not affiliated with any official examination institute.",
    footerMade: "Africa speaks. From Douala to Dakar, from Kinshasa to Abidjan.", footerLegal: "Legal", footerTerms: "Terms", footerPrivacy: "Privacy", footerContact: "Contact",
  },
}

// ─── Navigation ────────────────────────────────────────────────────────────────
// Doctrine premium : verbes précis, pas de jargon. "Cours" → "Parcours"
// (personnel, éditorial), "Découvrir" → "Communauté" (le vrai objet),
// "Simulateur IA" → "Pratique orale" (le résultat, pas l'outil),
// "Statistiques" → "Suivi" (incarné). "Apprenant·e·s" partout, jamais "Élèves".
const nav = {
  fr: {
    // Communs
    home: "Accueil",
    settings: "Paramètres",
    login: "Se connecter",
    register: "Commencer gratuitement",
    logout: "Se déconnecter",
    logoutHint: "À bientôt",

    // Student
    path: "Mon parcours",
    myClass: "Ma classe",
    community: "Communauté",
    practice: "Pratique orale",
    journey: "Mon chemin",
    notifications: "Notifications",

    // Teacher
    today: "Aujourd'hui",
    teacherClasses: "Mes classes",
    learners: "Apprenant·e·s",
    corrections: "Corrections",
    studio: "Studio · IA",
    tracking: "Suivi",
    resources: "Ressources",

    // Center
    centerOverview: "Vue du centre",
    teachers: "Équipe pédagogique",
    centerLearners: "Apprenant·e·s",
    centerClasses: "Classes",
    centerTracking: "Suivi",
    billing: "Facturation",

    // Admin
    adminOverview: "Vue d'ensemble",
    adminUsers: "Comptes",
    adminRoles: "Rôles",
    adminCourses: "Bibliothèque",
    adminCenters: "Centres",
    adminSystem: "Système",

    // Legacy (préservés le temps de la migration) —
    // à supprimer une fois tous les usages nettoyés.
    courses: "Mon parcours",
    myClasses: "Ma classe",
    discover: "Communauté",
    simulator: "Pratique orale",
    progress: "Mon chemin",
    overview: "Vue d'ensemble",
    students: "Apprenant·e·s",
    assignments: "Corrections",
    generateCourse: "Studio · IA",
    stats: "Suivi",
    users: "Comptes",
    centers: "Centres",
    activities: "Activités",
  },
  en: {
    home: "Home",
    settings: "Settings",
    login: "Log in",
    register: "Get started free",
    logout: "Log out",
    logoutHint: "See you soon",

    path: "My path",
    myClass: "My class",
    community: "Community",
    practice: "Speaking practice",
    journey: "My journey",
    notifications: "Notifications",

    today: "Today",
    teacherClasses: "My classes",
    learners: "Learners",
    corrections: "Corrections",
    studio: "Studio · AI",
    tracking: "Tracking",
    resources: "Resources",

    centerOverview: "Center overview",
    teachers: "Teaching team",
    centerLearners: "Learners",
    centerClasses: "Classes",
    centerTracking: "Tracking",
    billing: "Billing",

    adminOverview: "Overview",
    adminUsers: "Accounts",
    adminRoles: "Roles",
    adminCourses: "Library",
    adminCenters: "Centers",
    adminSystem: "System",

    courses: "My path",
    myClasses: "My class",
    discover: "Community",
    simulator: "Speaking practice",
    progress: "My journey",
    overview: "Overview",
    students: "Learners",
    assignments: "Corrections",
    generateCourse: "Studio · AI",
    stats: "Tracking",
    users: "Accounts",
    centers: "Centers",
    activities: "Activities",
  },
}

// ─── Student dashboard ─────────────────────────────────────────────────────────
const dashboard = {
  fr: {
    xpLabel: "Points XP", lessonsLabel: "Leçons", scoreLabel: "Score moy.", streakLabel: "Jours streak",
    badgesLabel: "Badges", levelLabel: "Niveau actuel",
    launchSim: "Lancer une simulation", simulatorsTitle: "Simulateurs d'ambassade", simulatorsDesc: "Conversations IA avec Herr Bauer",
    skills: "Compétences", detailedProgress: "Progression détaillée", noSkills: "Commencez votre première leçon pour voir vos compétences !",
    joinClassTitle: "Avancer avec un enseignant", joinClassLabel: "Rejoindre une classe", joinClassDesc: "Tu peux apprendre seul, ou rejoindre une classe avec un code donné par ton enseignant ou ton centre.",
    joinCodePlaceholder: "DEUTSCH-A1-XXXX", pendingTitle: "Inscription en attente", pendingDesc: "Votre enseignant doit valider votre demande.",
    rewardsLabel: "Récompenses", badgesTitle: "Badges obtenus", noBadge: "Complétez votre première leçon pour gagner un badge",
    communityLabel: "Communauté", discoverLabel: "🔍 Découvrir",
    grammar: "Grammaire", vocabulary: "Vocabulaire", pronunciation: "Prononciation", comprehension: "Compréhension",
    classesAvailable: "Classes disponibles", classesJoin: "Rejoindre une classe", groupsLabel: "Groupes d'élèves",
    studyGroup: "Étudier en groupe", findPartner: "Trouver un partenaire", soloStudents: "Élèves en solo",
    loading: "Chargement...",
    greetReturn: "Bonjour",
    greetSubtitle: "Ton parcours ne se construit pas en un jour. Aujourd'hui, fais simplement un petit pas.",
    greetEmotional: "Yema est là pour t'aider à apprendre, te préparer et t'intégrer à ton rythme.",
    streakActive: "jours d'affilée — continuez !",
    streakEmpty: "Connecte-toi chaque jour pour construire ta série",
    levelCurrentLabel: "Niveau actuel",
    levelTowardsLabel: "vers",
    levelConfirm: "À confirmer",
    simPracticeTitle: "Pratique orale",
    simPracticeDesc: "Entraîne-toi avec des scénarios réalistes pour gagner en confiance en allemand.",
    ctaTestLevel: "Tester mon niveau",
    ctaFirstLesson: "Commencer ma première leçon →",
    ctaContinue: "Continuer mon parcours",
    ctaSimulator: "Lancer une simulation",
    journeyTitle: "Votre parcours Yema",
    pillar1Label: "Apprendre", pillar1Desc: "Construis tes bases avec des leçons courtes et progressives.",
    pillar2Label: "Se préparer", pillar2Desc: "Pratique des situations réalistes pour gagner en confiance.",
    pillar3Label: "S'intégrer", pillar3Desc: "Bientôt : trouve des partenaires, groupes et ressources pour avancer ensemble.",
    pillar3Badge: "Bientôt",
    communityGroupsSoon: "Bientôt disponible",
    communityPartnerSoon: "Bientôt disponible",
    badgeStreak: "7 jours", badgeFirstA: "Premier A", badgePrecision: "Précision",
    badgeChampion: "Champion", badgeDiamond: "Diamant", badgeRocket: "Fusée",
    progressWidgetTitle: "Ma progression",
    progressZeroTitle: "Tu commences ici",
    progressZeroText: "Ton parcours commence ici. Une première leçon suffit pour lancer ta progression.",
    progressViewDetail: "Voir le détail",
    progressStartA1: "Commencer A1",
    progressTestLevel: "Tester mon niveau",
    progressContinue: "Continuer mon parcours",
    greetNew: "Bienvenue dans ton parcours Yema",
    greetSubtitleNew: "Ton parcours ne se construit pas en un jour. Aujourd'hui, fais simplement un petit pas.",
    greetSubtitleReturn: "Ton parcours ne se construit pas en un jour. Aujourd'hui, fais simplement un petit pas.",
    encouragementPill: "Chaque étape compte.",
    nextStepCardTitle: "Ton prochain pas",
    nextStep1Title: "Commence par connaître ton niveau",
    nextStep1Text: "Fais le test gratuit pour savoir par où commencer.",
    nextStep1CTA: "Tester mon niveau",
    nextStep2Title: "Commence avec une première leçon",
    nextStep2Text: "Quelques minutes suffisent pour poser tes premières bases.",
    nextStep2CTA: "Commencer ma première leçon",
    nextStep3Title: "Continue là où tu t'es arrêté",
    nextStep3Text: "Reprendre aujourd'hui, même quelques minutes, aide à garder le rythme.",
    nextStep3CTA: "Continuer mon parcours",
    progressViewProgress: "Voir ma progression",
    progressLevelLabel: "Niveau",
    progressXpLabel: "XP total",
    progressModulesLabel: "Modules terminés",
    progressDaysLabel: "Jours de pratique",
    progressNextLabel: "Prochaine étape",
    simCTA: "Pratiquer avec le simulateur",
    classCardTitle: "Avancer avec un enseignant",
    classCardText: "Tu peux apprendre seul, ou rejoindre une classe avec un code donné par ton enseignant ou ton centre.",
    classCardCTA: "Rejoindre une classe",
    communityCardTitle: "Bientôt avec Yema Community",
    communityCardText: "Trouve des partenaires d'apprentissage, rejoins des groupes et avance avec des personnes qui ont les mêmes objectifs.",
    actionLearnTitle: "Apprendre",
    actionLearnText: "Reprends tes cours et avance étape par étape.",
    actionLearnCTA: "Voir les cours",
    actionPracticeTitle: "Pratiquer",
    actionPracticeText: "Entraîne-toi à parler en allemand dans des situations réalistes.",
    actionPracticeCTA: "Pratiquer l'oral",
    actionSupportTitle: "Être accompagné",
    actionSupportText: "Rejoins une classe avec un code donné par ton enseignant ou ton centre.",
    actionSupportCTA: "Rejoindre une classe",
    communityTitle: "Bientôt : avancer avec une communauté",
    communityText: "Yema Community permettra de trouver des partenaires d'apprentissage, des groupes et des personnes qui avancent vers les mêmes objectifs.",
  },
  en: {
    xpLabel: "XP earned", lessonsLabel: "Lessons completed", scoreLabel: "Average score", streakLabel: "Day streak",
    badgesLabel: "Badges", levelLabel: "Current level",
    launchSim: "Start a simulation", simulatorsTitle: "AI Simulator", simulatorsDesc: "Practice conversations with AI",
    skills: "Skills", detailedProgress: "Detailed progress", noSkills: "Complete a lesson to start tracking your skills here.",
    joinClassTitle: "Move forward with a teacher", joinClassLabel: "Join a class", joinClassDesc: "You can learn on your own, or join a class with a code shared by your teacher or center.",
    joinCodePlaceholder: "DEUTSCH-A1-XXXX", pendingTitle: "Pending enrollment", pendingDesc: "Your teacher will approve your enrollment shortly.",
    rewardsLabel: "Rewards", badgesTitle: "Your badges", noBadge: "Finish your first lesson to unlock your first badge.",
    communityLabel: "Community", discoverLabel: "🔍 Discover",
    grammar: "Grammar", vocabulary: "Vocabulary", pronunciation: "Pronunciation", comprehension: "Comprehension",
    classesAvailable: "Available classes", classesJoin: "Join a class", groupsLabel: "Study groups",
    studyGroup: "Study in a group", findPartner: "Find a partner", soloStudents: "Solo students",
    loading: "Loading...",
    greetReturn: "Hi",
    greetSubtitle: "Your journey is not built in one day. Today, just take one small step.",
    greetEmotional: "Yema is here to help you learn, prepare and belong at your own pace.",
    streakActive: "days in a row — keep it up!",
    streakEmpty: "Log in every day to build your streak",
    levelCurrentLabel: "Current level",
    levelTowardsLabel: "towards",
    levelConfirm: "To confirm",
    simPracticeTitle: "Speaking practice",
    simPracticeDesc: "Train with realistic scenarios to build confidence in German.",
    ctaTestLevel: "Test my level",
    ctaFirstLesson: "Start my first lesson →",
    ctaContinue: "Continue my path",
    ctaSimulator: "Start a simulation",
    journeyTitle: "Your Yema journey",
    pillar1Label: "Learn", pillar1Desc: "Build your foundation with short, progressive lessons.",
    pillar2Label: "Prepare", pillar2Desc: "Practice realistic situations to gain confidence.",
    pillar3Label: "Belong", pillar3Desc: "Coming soon: find partners, groups and resources to move forward together.",
    pillar3Badge: "Coming soon",
    communityGroupsSoon: "Coming soon",
    communityPartnerSoon: "Coming soon",
    badgeStreak: "7-day streak", badgeFirstA: "First A", badgePrecision: "Precision",
    badgeChampion: "Champion", badgeDiamond: "Diamond", badgeRocket: "Rocket",
    progressWidgetTitle: "My progress",
    progressZeroTitle: "You start here",
    progressZeroText: "Your journey starts here. One first lesson is enough to begin your progress.",
    progressViewDetail: "View details",
    progressStartA1: "Start A1",
    progressTestLevel: "Test my level",
    progressContinue: "Continue my path",
    greetNew: "Welcome to your Yema journey",
    greetSubtitleNew: "Your journey is not built in one day. Today, just take one small step.",
    greetSubtitleReturn: "Your journey is not built in one day. Today, just take one small step.",
    encouragementPill: "Every step matters.",
    nextStepCardTitle: "Your next step",
    nextStep1Title: "Start by knowing your level",
    nextStep1Text: "Take the free test to know where to begin.",
    nextStep1CTA: "Test my level",
    nextStep2Title: "Start with your first lesson",
    nextStep2Text: "A few minutes are enough to build your first foundation.",
    nextStep2CTA: "Start my first lesson",
    nextStep3Title: "Continue where you left off",
    nextStep3Text: "Coming back today, even for a few minutes, helps you keep your rhythm.",
    nextStep3CTA: "Continue my path",
    progressViewProgress: "View my progress",
    progressLevelLabel: "Level",
    progressXpLabel: "Total XP",
    progressModulesLabel: "Completed modules",
    progressDaysLabel: "Practice days",
    progressNextLabel: "Next step",
    simCTA: "Practice with the simulator",
    classCardTitle: "Move forward with a teacher",
    classCardText: "You can learn on your own, or join a class with a code shared by your teacher or center.",
    classCardCTA: "Join a class",
    communityCardTitle: "Coming soon with Yema Community",
    communityCardText: "Find learning partners, join groups and move forward with people working toward similar goals.",
    actionLearnTitle: "Learn",
    actionLearnText: "Return to your lessons and move forward step by step.",
    actionLearnCTA: "View courses",
    actionPracticeTitle: "Practice",
    actionPracticeText: "Train your German speaking skills with realistic situations.",
    actionPracticeCTA: "Practice speaking",
    actionSupportTitle: "Get support",
    actionSupportText: "Join a class with a code shared by your teacher or center.",
    actionSupportCTA: "Join a class",
    communityTitle: "Coming soon: move forward with a community",
    communityText: "Yema Community will help you find learning partners, groups and people working toward similar goals.",
  },
}

// ─── Teacher ───────────────────────────────────────────────────────────────────
const teacher = {
  fr: {
    space: "Espace Enseignant", access: "Accès Professeur · Vérifié", role: "Enseignant · Yema",
    greeting: "Bonjour, {name}", newClass: "+ Nouvelle classe", studentView: "Vue élève",
    myTeacherCode: "Mon code enseignant", myClassCodes: "Codes de mes classes",
    shareCodeStudents: "Partagez ce code aux élèves pour qu'ils vous trouvent sur Découvrir",
    shareClassCode: "Partagez votre code de classe pour inviter des élèves",
    copied: "✓ Copié", copy: "Copier",
    statStudentsLabel: "Apprenants actifs", statAvgLabel: "Moyenne de la classe", statAvgSub: "Sur 10",
    statAssignmentsLabel: "Travaux à corriger", statAssignmentsSub: "En attente de votre retour",
    statCompletionLabel: "Taux de complétion", statCompletionSub: "Modules terminés cette semaine",
    sectionClasses: "Mes Classes", sectionActivity: "Activité récente",
    activityEmpty: "L'activité récente apparaîtra ici",
    classesEmpty: "Vous n'avez pas encore de classe.", createFirstClass: "+ Créer ma première classe →",
    viewAll: "Voir tout →", progressChart: "Progression des classes — 4 semaines",
    progressEmpty: "Les données de progression apparaîtront ici dès que vos apprenants commenceront les leçons.",
    struggling: "⚠️ Apprenants en difficulté", allGood: "Tous les apprenants sont au-dessus de 50% 🎉",
    recentAssignments: "Activités récentes", assignmentsEmpty: "Créez votre première activité depuis la page Corrections.",
    viewStudent: "Voir →", classStudents: "apprenants", classProgress: "progression", classAvgScore: "score moyen",
    loading: "Chargement...",
    // Today page
    aiPill: "L'IA assiste. Vous guidez.",
    todaySubtitle: "Votre rôle est précieux. Yema vous aide à enseigner mieux, pas à vous remplacer.",
    action1Title: "Accompagner", action1Desc: "Suivez la progression de vos apprenants et identifiez qui a besoin de soutien.", action1CTA: "Voir les apprenants",
    action2Title: "Préparer", action2Desc: "Créez une nouvelle activité ou ajustez le programme de vos classes.", action2CTA: "Créer une activité",
    action3Title: "Suivre", action3Desc: "Analysez la progression collective et repérez les lacunes à combler.", action3CTA: "Voir le suivi",
    // Corrections page
    correctionsSubtitle: "Revoyez les travaux de vos apprenants et donnez-leur un retour humain.",
    filterToReview: "À corriger", filterWaiting: "En attente", filterDone: "Terminés", filterAll: "Tous",
    reviewBtn: "Revoir les réponses", prepareActivity: "+ Préparer une activité",
    aiTrustNote: "💡 Yema peut suggérer des pistes de correction. Votre jugement reste déterminant.",
    sampleLabel: "Exemple", statusOpen: "Ouvert", statusClosed: "Fermé",
    deadline: "Échéance", maxScoreLabel: "Note max", submittedLabel: "Rendus", submittedPctLabel: "remis",
    newActivityTitle: "Préparer une activité",
    fieldTitle: "Titre", fieldTitlePh: "Ex : Vocabulaire Lektion 5",
    fieldClass: "Classe", fieldClassPh: "Groupe A1 Matin",
    fieldDue: "Date limite",
    // Tracking page
    trackingSubtitle: "Comprenez où en sont vos apprenants pour mieux les accompagner.",
    demoDataBanner: "Ces données sont des exemples. Vos vraies statistiques apparaîtront ici dès que vos apprenants seront actifs.",
    chartWeeksLabel: "Progression des scores — 4 semaines",
    chartModulesLabel: "Complétion par lektion (A1 vs A2)",
    // Today — priority card
    todayPriorityTitle: "Votre priorité aujourd'hui",
    todayPriorityPendingText: "Des réponses attendent votre regard. L'IA peut proposer une correction, mais votre validation donne du sens.",
    todayPriorityPendingCTA: "Voir les corrections",
    todayPriorityCalmText: "Tout est calme pour le moment. Vous pouvez préparer une activité ou consulter la progression de vos apprenants.",
    todayPriorityCalmCTA: "Préparer une activité",
    // Today — attention cards
    todayAttnTitle1: "Où votre présence compte", todayAttnDesc1: "Yema met en avant les moments où votre intervention peut vraiment aider.", todayAttnCTA1: "Voir les corrections",
    todayAttnTitle2: "À encourager", todayAttnDesc2: "Un petit message peut relancer la motivation d'un apprenant.", todayAttnCTA2: "Voir les apprenants",
    todayAttnTitle3: "À féliciter", todayAttnDesc3: "Reconnaître un progrès aide souvent à continuer.", todayAttnCTA3: "Voir la progression",
    todayAttnTitle4: "À préparer", todayAttnDesc4: "Préparez une activité courte pour soutenir le prochain pas.", todayAttnCTA4: "Préparer une activité",
    // Learners page
    learnersSubtitle: "Voyez qui avance, qui bloque et qui a besoin d'un encouragement.",
    filterNeedsEncouragement: "À encourager", filterProgressing: "En progression", filterNeedsSupport: "Besoin d'aide", filterInactive: "Inactifs",
    learnersEmpty: "Aucun apprenant pour le moment. Invitez une classe pour commencer à accompagner vos apprenants.",
    learnerNeedsSupport: "Besoin d'aide", learnerGoodProgress: "En progression", learnerInactive: "Inactif",
    learnerLastActive: "Dernière activité",
    demoLabel: "Démo", demoLearnersBanner: "Ces apprenants sont des données d'exemple. Vos vrais apprenants apparaîtront ici.",
    // Corrections tabs
    tabToReview: "À revoir", tabAISuggestions: "Suggestions IA", tabApproved: "Validées", tabAll: "Toutes",
    aiSuggestionAvailable: "Suggestion IA disponible",
    correctionsSubtitle2: "Validez les réponses, ajoutez votre regard humain et aidez chaque apprenant à avancer.",
    trustNote: "Yema peut préparer une première suggestion. Vous validez toujours le feedback final.",
    // Activities page
    activitiesTitle: "Activités",
    activitiesSubtitle: "Préparez des activités pour vos classes. L'IA peut vous aider, mais vous gardez la validation finale.",
    activityTypeWriting: "Exercice écrit", activityTypeSpeaking: "Pratique orale", activityTypeQuiz: "Quiz",
    activityTypeComprehension: "Compréhension", activityTypeReview: "Révision", activityTypeFree: "Devoir libre",
    activityFieldClass: "Classe", activityFieldGoal: "Objectif", activityFieldLevel: "Niveau",
    activityFieldType: "Type d'activité", activityFieldInstructions: "Consigne", activityFieldDeadline: "Date limite",
    activityValidationRequired: "Validation enseignant requise",
    activitiesComingSoon: "La création avancée d'activités est en cours de développement. Pour l'instant, créez des devoirs simples depuis la page Corrections.",
    createActivityDraft: "Créer un brouillon",
    // Teaching Studio
    studioTitle: "Studio pédagogique",
    studioSubtitle: "Préparez des brouillons d'activités avec l'aide de l'IA. Vous gardez toujours la validation finale.",
    studioGenerateBtn: "Créer un brouillon",
    studioPublishWarning: "Les contenus générés doivent être relus avant publication.",
    // Resources
    resourcesSubtitle: "Des supports pour préparer vos cours, encourager vos apprenants et gagner du temps.",
    resource1Title: "Phrases utiles en classe", resource2Title: "Conseils pour motiver les apprenants",
    resource3Title: "Activités A1 prêtes à adapter", resource4Title: "Préparation intégration",
    resourcesComingSoon: "En préparation",
    // Tracking sections
    trackingAttnTitle: "Points d'attention", trackingClassTitle: "Progression par classe",
    trackingSkillsTitle: "Compétences à renforcer", trackingActivityTitle: "Activité récente",
    trackingNextTitle: "Prochaine action recommandée",
    trackingNoData: "Les données apparaîtront lorsque vos apprenants commenceront leurs activités.",
    // Part 1 — positioning
    expertiseCenter: "Votre expertise reste au centre.",
    expertiseSupportCopy: "Yema vous aide à mieux voir vos apprenants, gagner du temps et montrer l'impact réel de votre accompagnement.",
    // Part 2 — impact block
    impactTitle: "Votre impact",
    impactSubtitle: "Un aperçu de ce que votre accompagnement rend possible.",
    impactLearnersGuided: "Apprenants accompagnés",
    impactFeedbackReviewed: "Feedbacks validés",
    impactProgressObserved: "Progrès observés",
    impactEmpty: "Votre impact apparaîtra ici lorsque vos apprenants commenceront à utiliser Yema.",
    // Part 3 — today section + warm state
    todayAttnSection: "Votre radar humain",
    attnEmptyHint: "Tout est calme. Votre accompagnement porte ses fruits.",
    // Part 4 — corrections
    correctionsTrustCopy: "L'IA peut proposer une base. Votre feedback final donne le ton, le contexte et l'encouragement.",
    correctionStepLearner: "Réponse de l'apprenant",
    correctionStepAI: "Suggestion IA",
    correctionStepFinal: "Votre feedback final",
    correctionStepSend: "Envoyer avec votre validation",
    // Part 5 — studio
    studioAdaptNote: "Adapter avant publication",
    studioReviewRequired: "Votre validation est requise",
    // Part 6 — microcopy
    microcopy1: "Vous connaissez vos apprenants mieux que n'importe quel algorithme.",
    microcopy2: "Les données montrent où regarder. Vous décidez comment accompagner.",
  },
  en: {
    space: "Teacher Space", access: "Teacher Access · Verified", role: "Teacher · Yema",
    greeting: "Hi, {name}", newClass: "+ New class", studentView: "Student view",
    myTeacherCode: "My teacher code", myClassCodes: "My class codes",
    shareCodeStudents: "Share this code with students so they can find you on Discover",
    shareClassCode: "Share your class code to invite students",
    copied: "✓ Copied", copy: "Copy",
    statStudentsLabel: "Active learners", statAvgLabel: "Class average", statAvgSub: "Out of 10",
    statAssignmentsLabel: "Work to review", statAssignmentsSub: "Awaiting your feedback",
    statCompletionLabel: "Completion rate", statCompletionSub: "Modules completed this week",
    sectionClasses: "My Classes", sectionActivity: "Recent activity",
    activityEmpty: "Recent activity will appear here",
    classesEmpty: "You haven't created any classes yet.", createFirstClass: "+ Create your first class →",
    viewAll: "View all →", progressChart: "Class progress — last 4 weeks",
    progressEmpty: "Progress data will show up here once your learners start lessons.",
    struggling: "⚠️ Learners needing support", allGood: "All learners are above 50% 🎉",
    recentAssignments: "Recent activities", assignmentsEmpty: "Create your first activity from the Corrections page.",
    viewStudent: "View →", classStudents: "learners", classProgress: "progress", classAvgScore: "avg score",
    loading: "Loading...",
    // Today page
    aiPill: "AI assists. You guide.",
    todaySubtitle: "Your role matters. Yema helps you teach better — it doesn't replace you.",
    action1Title: "Guide", action1Desc: "Follow your learners' progress and identify who needs support.", action1CTA: "View learners",
    action2Title: "Prepare", action2Desc: "Create a new activity or adjust the programme for your classes.", action2CTA: "Create activity",
    action3Title: "Track", action3Desc: "Analyse collective progress and spot the gaps worth addressing.", action3CTA: "View tracking",
    // Corrections page
    correctionsSubtitle: "Review your learners' work and give them real, human feedback.",
    filterToReview: "To review", filterWaiting: "Waiting", filterDone: "Completed", filterAll: "All",
    reviewBtn: "Review responses", prepareActivity: "+ Prepare an activity",
    aiTrustNote: "💡 Yema can offer correction hints. Your judgment is what counts.",
    sampleLabel: "Sample", statusOpen: "Open", statusClosed: "Closed",
    deadline: "Due", maxScoreLabel: "Max score", submittedLabel: "Submitted", submittedPctLabel: "submitted",
    newActivityTitle: "Prepare an activity",
    fieldTitle: "Title", fieldTitlePh: "E.g.: Vocabulary Lesson 5",
    fieldClass: "Class", fieldClassPh: "Group A1 Morning",
    fieldDue: "Deadline",
    // Tracking page
    trackingSubtitle: "Understand where your learners stand so you can support them better.",
    demoDataBanner: "These are sample figures. Your real data will appear here once your learners are active.",
    chartWeeksLabel: "Score progression — 4 weeks",
    chartModulesLabel: "Completion by lesson (A1 vs A2)",
    // Today — priority card
    todayPriorityTitle: "Your priority today",
    todayPriorityPendingText: "Some learner responses are waiting for your review. AI can suggest feedback, but your validation gives it meaning.",
    todayPriorityPendingCTA: "Review corrections",
    todayPriorityCalmText: "Everything is calm for now. You can prepare an activity or review learner progress.",
    todayPriorityCalmCTA: "Prepare activity",
    // Today — attention cards
    todayAttnTitle1: "Where your presence matters", todayAttnDesc1: "Yema highlights the moments where your guidance can truly help.", todayAttnCTA1: "Review corrections",
    todayAttnTitle2: "To encourage", todayAttnDesc2: "A small message can restart a learner's motivation.", todayAttnCTA2: "View learners",
    todayAttnTitle3: "To celebrate", todayAttnDesc3: "Recognizing progress often helps learners continue.", todayAttnCTA3: "View progress",
    todayAttnTitle4: "To prepare", todayAttnDesc4: "Prepare a short activity to support the next step.", todayAttnCTA4: "Prepare activity",
    // Learners page
    learnersSubtitle: "See who is progressing, who is stuck and who may need encouragement.",
    filterNeedsEncouragement: "Needs encouragement", filterProgressing: "Progressing", filterNeedsSupport: "Needs support", filterInactive: "Inactive",
    learnersEmpty: "No learners yet. Invite a class to start guiding your learners.",
    learnerNeedsSupport: "Needs support", learnerGoodProgress: "Progressing", learnerInactive: "Inactive",
    learnerLastActive: "Last activity",
    demoLabel: "Demo", demoLearnersBanner: "These learners are sample data. Your real learners will appear here.",
    // Corrections tabs
    tabToReview: "To review", tabAISuggestions: "AI suggestions", tabApproved: "Approved", tabAll: "All",
    aiSuggestionAvailable: "AI suggestion available",
    correctionsSubtitle2: "Review responses, add your human guidance and help each learner move forward.",
    trustNote: "Yema can prepare a first suggestion. You always validate the final feedback.",
    // Activities page
    activitiesTitle: "Activities",
    activitiesSubtitle: "Prepare activities for your classes. AI can help, but you always keep final review.",
    activityTypeWriting: "Writing exercise", activityTypeSpeaking: "Speaking practice", activityTypeQuiz: "Quiz",
    activityTypeComprehension: "Comprehension", activityTypeReview: "Review", activityTypeFree: "Free assignment",
    activityFieldClass: "Class", activityFieldGoal: "Goal", activityFieldLevel: "Level",
    activityFieldType: "Activity type", activityFieldInstructions: "Instructions", activityFieldDeadline: "Deadline",
    activityValidationRequired: "Teacher review required",
    activitiesComingSoon: "Advanced activity creation is under development. For now, create simple assignments from the Corrections page.",
    createActivityDraft: "Create draft",
    // Teaching Studio
    studioTitle: "Teaching studio",
    studioSubtitle: "Prepare draft activities with AI support. You always keep final review.",
    studioGenerateBtn: "Create draft",
    studioPublishWarning: "Generated content should be reviewed before publishing.",
    // Resources
    resourcesSubtitle: "Support materials to prepare lessons, encourage learners and save time.",
    resource1Title: "Useful classroom phrases", resource2Title: "Tips to motivate learners",
    resource3Title: "A1 activities to adapt", resource4Title: "Integration preparation",
    resourcesComingSoon: "Coming soon",
    // Tracking sections
    trackingAttnTitle: "Attention points", trackingClassTitle: "Class progress",
    trackingSkillsTitle: "Skills to strengthen", trackingActivityTitle: "Recent activity",
    trackingNextTitle: "Recommended next action",
    trackingNoData: "Data will appear when learners start their activities.",
    // Part 1 — positioning
    expertiseCenter: "Your expertise stays at the center.",
    expertiseSupportCopy: "Yema helps you understand your learners better, save time and show the real impact of your guidance.",
    // Part 2 — impact block
    impactTitle: "Your impact",
    impactSubtitle: "A view of what your guidance makes possible.",
    impactLearnersGuided: "Learners guided",
    impactFeedbackReviewed: "Feedback reviewed",
    impactProgressObserved: "Progress observed",
    impactEmpty: "Your impact will appear here when your learners start using Yema.",
    // Part 3 — today section + warm state
    todayAttnSection: "Your human radar",
    attnEmptyHint: "All is calm. Your guidance is working.",
    // Part 4 — corrections
    correctionsTrustCopy: "AI can suggest a first draft. Your final feedback adds tone, context and encouragement.",
    correctionStepLearner: "Learner response",
    correctionStepAI: "AI suggestion",
    correctionStepFinal: "Your final feedback",
    correctionStepSend: "Send with your review",
    // Part 5 — studio
    studioAdaptNote: "Adapt before publishing",
    studioReviewRequired: "Your review is required",
    // Part 6 — microcopy
    microcopy1: "You know your learners better than any algorithm.",
    microcopy2: "Data shows where to look. You decide how to guide.",
  },
}

// ─── Center ────────────────────────────────────────────────────────────────────
const center = {
  fr: {
    portal: "Portail Centre", partnerBadge: "⭐ Centre Partenaire", verified: "✓ Vérifié",
    dashboard: "Tableau de bord", proPlan: "⭐ Plan Pro",
    registrationCode: "Code d'inscription de votre centre",
    shareCodeStudents: "Partagez ce code à vos élèves — ils le saisissent lors de leur inscription sur Yema.",
    viewStudents: "Voir les élèves →", copied: "✓ Copié !", copy: "Copier",
    statTeachers: "Enseignants actifs", statStudents: "Élèves inscrits", statClasses: "Classes actives",
    statRevenue: "Revenus du mois", statRevenueSub: "Monétisation à venir",
    registrationsChart: "Évolution des inscriptions", registrationsEmpty: "Les statistiques d'inscription apparaîtront ici au fur et à mesure.",
    alerts: "Alertes & Notifications", noAlerts: "Aucune alerte pour le moment",
    teachersList: "Enseignants du centre", noTeachers: "Aucun enseignant associé au centre pour l'instant.",
    viewAll: "Voir tout →", studentPortal: "← Portail élève", directorRole: "Directeur · CENTER",
    tableTeacher: "Enseignant", tableSpecialty: "Spécialité", tableClasses: "Classes",
    tableStudents: "Élèves", tableAvgScore: "Score moy.", tableStatus: "Statut",
    overview: "Vue d'ensemble", loading: "Chargement...",
  },
  en: {
    portal: "Center Portal", partnerBadge: "⭐ Partner Center", verified: "✓ Verified",
    dashboard: "Dashboard", proPlan: "⭐ Pro Plan",
    registrationCode: "Your center registration code",
    shareCodeStudents: "Share this code with your students — they enter it during registration on Yema.",
    viewStudents: "View students →", copied: "✓ Copied!", copy: "Copy",
    statTeachers: "Active teachers", statStudents: "Enrolled students", statClasses: "Active classes",
    statRevenue: "Monthly revenue", statRevenueSub: "Payments launching soon",
    registrationsChart: "Enrollment trends", registrationsEmpty: "Enrollment stats will appear here as your center grows.",
    alerts: "Alerts & Notifications", noAlerts: "No alerts right now",
    teachersList: "Center teachers", noTeachers: "No teachers added yet.",
    viewAll: "View all →", studentPortal: "← Student portal", directorRole: "Director · Center Manager",
    tableTeacher: "Teacher", tableSpecialty: "Specialty", tableClasses: "Classes",
    tableStudents: "Students", tableAvgScore: "Avg score", tableStatus: "Status",
    overview: "Overview", loading: "Loading...",
  },
}

// ─── Admin ─────────────────────────────────────────────────────────────────────
const admin = {
  fr: {
    navOverview: "Vue d'ensemble", navUsers: "Utilisateurs", navCourses: "Cours & Contenu",
    navValidations: "Validations", navSystem: "Système", backToSite: "← Retour au site",
    greeting: "👋 Bonjour, Admin",
    kpiTotal: "Total utilisateurs", kpiStudents: "Élèves actifs", kpiTeachers: "Enseignants",
    kpiCenters: "Centres", kpiSessions: "Sessions aujourd'hui",
    kpiTotalSub: "ce mois", kpiStudentsSub: "inscrits", kpiTeachersSub: "vérifiés",
    kpiCentersSub: "partenaires", kpiSessionsSub: "moy.",
    chartMonthly: "📈 Inscriptions mensuelles", chartSeriesUsers: "Utilisateurs",
    chartLevels: "🎯 Niveaux CEFR", chartWeekly: "📅 Activité cette semaine",
    chartSeriesStudents: "Élèves", chartSeriesTeachers: "Enseignants", chartSeriesCenters: "Centres",
    recentActivity: "🔔 Activité récente", recentActivityEmpty: "L'activité récente apparaîtra ici",
    topCities: "🌍 Top villes", topCitiesEmpty: "Données géographiques — bientôt disponibles",
    usersTitle: "👥 Utilisateurs", searchPlaceholder: "Rechercher un utilisateur...",
    filterAll: "Tous les rôles", filterStudents: "Élèves", filterTeachers: "Enseignants", filterCenters: "Centres",
    quickStatNew: "Nouveaux aujourd'hui",
    tableUser: "Utilisateur", tableRole: "Rôle", tableLevel: "Niveau", tableCity: "Ville",
    tableDate: "Inscription", tableStatus: "Statut", tableActions: "Actions",
    statusActive: "Actif", statusPending: "En attente",
    roleLabelStudent: "Élève", roleLabelTeacher: "Enseignant", roleLabelCenter: "Centre", roleLabelAdmin: "Admin",
    actionView: "Voir", actionEdit: "Modifier", actionBlock: "Bloquer",
    coursesTitle: "📚 Cours & Contenu", generateBtn: "✨ Générer avec IA",
    kpiCoursesTotal: "Cours total", kpiPublished: "Publiés", kpiDraft: "Brouillons", kpiModules: "Modules total",
    levelGenerated: "Généré par IA", levelGeneratedSuffix: "générés", generateCourseBtn: "+ Générer",
    validationsTitle: "✅ Validations en attente", noValidations: "✅ Aucune validation en attente",
    validTypeCenter: "Centre", validTypeTeacher: "Enseignant",
    validateBtn: "✅ Valider", rejectBtn: "❌ Refuser",
    systemTitle: "⚙️ Système", apisTitle: "🔌 APIs configurées",
    apiStatusActive: "Actif", apiStatusPending: "À configurer",
    pagesTitle: "📄 Pages de la plateforme", envTitle: "🔐 Variables d'environnement",
    pageDashboardStudent: "Dashboard élève", pageCourses: "Cours", pageSimulator: "Simulateur IA",
    pageDiscover: "Découvrir", pageProgress: "Progression",
    pageDashboardTeacher: "Dashboard enseignant", pageDashboardCenter: "Dashboard centre",
    pageQuiz: "Quiz adaptatif", pageVideos: "Vidéos Remotion", pagePricing: "Tarifs",
  },
  en: {
    navOverview: "Overview", navUsers: "Users", navCourses: "Courses & Content",
    navValidations: "Validations", navSystem: "System", backToSite: "← Back to site",
    greeting: "👋 Hello, Admin",
    kpiTotal: "Total users", kpiStudents: "Active students", kpiTeachers: "Teachers",
    kpiCenters: "Centers", kpiSessions: "Sessions today",
    kpiTotalSub: "this month", kpiStudentsSub: "enrolled", kpiTeachersSub: "verified",
    kpiCentersSub: "partners", kpiSessionsSub: "avg.",
    chartMonthly: "📈 Monthly registrations", chartSeriesUsers: "Users",
    chartLevels: "🎯 CEFR Levels", chartWeekly: "📅 Activity this week",
    chartSeriesStudents: "Students", chartSeriesTeachers: "Teachers", chartSeriesCenters: "Centers",
    recentActivity: "🔔 Recent activity", recentActivityEmpty: "Recent activity will appear here",
    topCities: "🌍 Top cities", topCitiesEmpty: "Geographic data — coming soon",
    usersTitle: "👥 Users", searchPlaceholder: "Search a user...",
    filterAll: "All roles", filterStudents: "Students", filterTeachers: "Teachers", filterCenters: "Centers",
    quickStatNew: "New today",
    tableUser: "User", tableRole: "Role", tableLevel: "Level", tableCity: "City",
    tableDate: "Registered", tableStatus: "Status", tableActions: "Actions",
    statusActive: "Active", statusPending: "Pending",
    roleLabelStudent: "Student", roleLabelTeacher: "Teacher", roleLabelCenter: "Center", roleLabelAdmin: "Admin",
    actionView: "View", actionEdit: "Edit", actionBlock: "Block",
    coursesTitle: "📚 Courses & Content", generateBtn: "✨ Generate with AI",
    kpiCoursesTotal: "Total courses", kpiPublished: "Published", kpiDraft: "Drafts", kpiModules: "Total modules",
    levelGenerated: "AI generated", levelGeneratedSuffix: "generated", generateCourseBtn: "+ Generate",
    validationsTitle: "✅ Pending validations", noValidations: "✅ No pending validations",
    validTypeCenter: "Center", validTypeTeacher: "Teacher",
    validateBtn: "✅ Approve", rejectBtn: "❌ Reject",
    systemTitle: "⚙️ System", apisTitle: "🔌 Configured APIs",
    apiStatusActive: "Active", apiStatusPending: "Not configured",
    pagesTitle: "📄 Platform pages", envTitle: "🔐 Environment variables",
    pageDashboardStudent: "Student dashboard", pageCourses: "Courses", pageSimulator: "AI Simulator",
    pageDiscover: "Discover", pageProgress: "Progress",
    pageDashboardTeacher: "Teacher dashboard", pageDashboardCenter: "Center dashboard",
    pageQuiz: "Adaptive quiz", pageVideos: "Remotion videos", pagePricing: "Pricing",
  },
}

// ─── Common ────────────────────────────────────────────────────────────────────
const common = {
  fr: {
    loading: "Chargement...", error: "Une erreur est survenue", retry: "Réessayer",
    save: "Sauvegarder", cancel: "Annuler", confirm: "Confirmer", back: "Retour",
    next: "Suivant", finish: "Terminer", yes: "Oui", no: "Non", or: "ou",
    search: "Rechercher", filter: "Filtrer", viewAll: "Voir tout", comingSoon: "Bientôt disponible",
    free: "Gratuit", premium: "Premium", new: "Nouveau", beta: "Bêta", active: "Actif", inactive: "Inactif",
  },
  en: {
    loading: "Loading...", error: "An error occurred", retry: "Retry",
    save: "Save", cancel: "Cancel", confirm: "Confirm", back: "Back",
    next: "Next", finish: "Done", yes: "Yes", no: "No", or: "or",
    search: "Search", filter: "Filter", viewAll: "View all", comingSoon: "Coming soon",
    free: "Free", premium: "Premium", new: "New", beta: "Beta", active: "Active", inactive: "Inactive",
  },
}

// ─── Auth ──────────────────────────────────────────────────────────────────────
const auth = {
  fr: {
    loginTitle: "Bon retour !", loginSubtitle: "Continuez votre apprentissage",
    email: "Adresse email", emailPlaceholder: "toi@example.com",
    password: "Mot de passe", passwordPlaceholder: "••••••••",
    loginBtn: "Se connecter", loginLoading: "Connexion...",
    noAccount: "Pas encore de compte ?", subscribe: "S'inscrire",
    chooseRole: "Je suis...", chooseRoleHint: "Qui êtes-vous ? Choisissez votre profil 👇",
    roleStudent: "Apprenant", roleStudentDesc: "Je veux apprendre l'allemand",
    roleTeacher: "Enseignant", roleTeacherDesc: "J'enseigne l'allemand",
    roleCenter: "Centre de langues", roleCenterDesc: "Je représente un centre",
    registerTitle: "Créez votre compte", registerSubtitle: "Commence ton voyage linguistique",
    registerBtn: "Créer mon compte", registerLoading: "Création du compte...",
    fullName: "Nom complet", fullNamePlaceholder: "Paul Nkengue", passwordMin: "Min. 6 caractères",
    passwordError: "Le mot de passe doit contenir au moins 6 caractères.",
    hasAccount: "Déjà un compte ?", signIn: "Se connecter", changeRole: "← Changer",
    confirmTitle: "Vérifie ta boîte mail ✉️", confirmSent: "Un lien de confirmation a été envoyé à",
    confirmClick: "Clique sur le lien pour activer ton compte et accéder à l'espace",
    backToLogin: "Retour à la connexion", createAccount: "Créer un compte",
    errorInvalid: "Email ou mot de passe incorrect.",
  },
  en: {
    loginTitle: "Welcome back", loginSubtitle: "Continue your learning journey",
    email: "Email address", emailPlaceholder: "you@example.com",
    password: "Password", passwordPlaceholder: "••••••••",
    loginBtn: "Log in", loginLoading: "Signing in...",
    noAccount: "New here?", subscribe: "Create an account",
    chooseRole: "Who are you?", chooseRoleHint: "Pick the option that describes you",
    roleStudent: "I'm a learner", roleStudentDesc: "Learning a language, A1 to C1",
    roleTeacher: "I'm a teacher", roleTeacherDesc: "I teach languages and manage classes",
    roleCenter: "I manage a center", roleCenterDesc: "Running a language school or institute",
    registerTitle: "Create your account", registerSubtitle: "Start your language journey",
    registerBtn: "Create account", registerLoading: "Creating your account...",
    fullName: "Full name", fullNamePlaceholder: "Paul Nkengue", passwordMin: "At least 6 characters",
    passwordError: "Your password must be at least 6 characters.",
    hasAccount: "Already have an account?", signIn: "Log in", changeRole: "← Back",
    confirmTitle: "Check your inbox ✉️", confirmSent: "We sent a confirmation link to",
    confirmClick: "Click the link to activate your account and get started.",
    backToLogin: "Back to login", createAccount: "Create account",
    errorInvalid: "Wrong email or password. Please try again.",
  },
}

// ─── Layout (sidebar) ──────────────────────────────────────────────────────────
const layout = {
  fr: {
    searchPlaceholder: "Rechercher un cours, un scénario...", goethe: "CECRL · A1 → C1",
    userFallback: "Utilisateur", studentBadge: "Élève inscrit",
    pendingBadge: "Validation en cours", groupLeader: "Chef de groupe",
    solo: "Solo", levelPrefix: "Niveau",
    studentRole: "Espace apprenant·e",
    teacherRole: "Espace enseignant·e", centerRole: "Espace centre", adminRole: "Espace admin",
    logout: "Se déconnecter",
  },
  en: {
    searchPlaceholder: "Search...", goethe: "CEFR · A1 → C1",
    userFallback: "User", studentBadge: "Enrolled learner",
    pendingBadge: "Pending validation", groupLeader: "Group leader",
    solo: "Solo", levelPrefix: "Level",
    studentRole: "Learner space",
    teacherRole: "Teacher space", centerRole: "Center space", adminRole: "Admin space",
    logout: "Log out",
  },
}

// ─── All text ──────────────────────────────────────────────────────────────────
// FR bundle : micro-typo passée en profondeur sur tout l'arbre.
// EN bundle : tel quel (règles typographiques anglaises différentes).
export const TEXT = {
  fr: {
    landing: deepTypo(landing.fr),
    nav: deepTypo(nav.fr),
    dashboard: deepTypo(dashboard.fr),
    teacher: deepTypo(teacher.fr),
    center: deepTypo(center.fr),
    admin: deepTypo(admin.fr),
    common: deepTypo(common.fr),
    auth: deepTypo(auth.fr),
    layout: deepTypo(layout.fr),
  },
  en: { landing: landing.en, nav: nav.en, dashboard: dashboard.en, teacher: teacher.en, center: center.en, admin: admin.en, common: common.en, auth: auth.en, layout: layout.en },
}

export type Locale = "fr" | "en"
export type TextBundle = typeof TEXT.fr

// ─── Hook ──────────────────────────────────────────────────────────────────────
// Reads locale directly from the URL path — no next-intl context needed.
// Works on every navigation: /fr/... = French, /en/... = English.
export function useT(): TextBundle {
  const pathname = usePathname()
  const locale: Locale = pathname.startsWith("/en") ? "en" : "fr"
  return TEXT[locale]
}
