"use client"
import { usePathname } from "next/navigation"

// ─── Landing page ─────────────────────────────────────────────────────────────
const landing = {
  fr: {
    badge: "Plateforme bêta ouverte · Première destination : Allemagne",
    title: "Apprendre. Se préparer.",
    titleAccent: "S'intégrer.",
    subtitle: "La plateforme d'apprentissage de l'allemand conçue pour les Camerounais. Compétences orales, écrites et culturelles — du A1 au C1.",
    subtitle2: "Sans blabla. Sans engagement. Juste de la progression réelle.",
    ctaPrimary: "Commencer gratuitement",
    ctaSecondary: "Tester mon niveau",
    ctaMicro: "Accès A1 complet · Sans carte bancaire",
    connexion: "Connexion",
    getStarted: "Démarrer",
    navFeatures: "Fonctionnalités",
    navLevels: "Niveaux",
    navPricing: "Tarifs",
    navCenters: "Centres",
    b2bLabel: "Solution B2B",
    statsUsers: "Apprenants",
    statsLevels: "Niveaux CEFR",
    statsSuccess: "Taux de réussite",
    statsCenters: "Centres partenaires",
    stat1Value: "Bêta", stat1Label: "Accès ouvert",
    stat2Value: "A1", stat2Label: "Niveau disponible",
    stat3Value: "FR & EN", stat3Label: "Langues d'interface",
    stat4Value: "✦", stat4Label: "Construit au Cameroun",
    featuresTitle: "Ce que vous allez vraiment apprendre",
    featuresSubtitle: "8 outils conçus pour une progression concrète — pas juste de la théorie.",
    feature1Title: "Pratique orale guidée", feature1Desc: "Conversez avec un interlocuteur IA en allemand. Progression adaptée à votre niveau — sans pression, sans jugement.", feature1Badge: "IA",
    feature2Title: "Audio allemand authentique", feature2Desc: "Des voix natives, des dialogues réels. Entraînez votre oreille à l'allemand du quotidien.",
    feature3Title: "Correction vocale en temps réel", feature3Desc: "Parlez, l'IA vous corrige immédiatement. Votre accent et votre fluidité s'améliorent leçon après leçon.", feature3Badge: "IA",
    feature4Title: "Coaching écriture IA", feature4Desc: "Rédigez en allemand. Gemini vous explique chaque correction avec des exemples contextuels.", feature4Badge: "Gemini",
    feature5Title: "Quiz qui s'adapte à vous", feature5Desc: "Plus vous progressez, plus le niveau s'ajuste. Chaque session cible vos vraies lacunes.", feature5Badge: "Adaptatif",
    feature6Title: "Classes virtuelles", feature6Desc: "Rejoignez la classe d'un enseignant ou créez votre groupe d'étude. Progression collective visible.", feature6Badge: "Bientôt",
    feature7Title: "Solution centres de langues", feature7Desc: "Un tableau de bord pour gérer enseignants, élèves et classes. Idéal pour les instituts de formation.", feature7Badge: "B2B",
    feature8Title: "Suivi de vos 5 compétences", feature8Desc: "Mesurez vos progrès sur Lecture, Écoute, Expression orale, Écriture et Grammaire.", feature8Badge: "Insights",
    levelsTitle: "Programme CECRL — de A1 à C1",
    levelsSubtitle: "Contenu pédagogique original aligné sur le Cadre Européen Commun de Référence pour les Langues.",
    available: "Disponible", locked: "🔒 Premium", modules: "modules",
    level1Name: "Débutant", level1Desc: "Salutations, famille, chiffres, routine quotidienne",
    level2Name: "Élémentaire", level2Desc: "Vie urbaine, médias, santé, voyages",
    level3Name: "Intermédiaire", level3Desc: "Travail, société, culture, environnement",
    level4Name: "Avancé", level4Desc: "Sciences, économie, médias, histoire",
    level5Name: "Maîtrise", level5Desc: "Philosophie, littérature, carrière internationale",
    visionTitle: "Une plateforme. Trois ambitions.",
    visionSubtitle: "Yema n'est pas une simple application de vocabulaire. C'est un parcours complet vers la maîtrise de l'allemand.",
    vision1Label: "Apprendre", vision1Title: "Des bases solides", vision1Desc: "Un programme structuré, du A1 au C1, avec des exercices oraux, écrits et audio pour bâtir de véritables compétences.",
    vision2Label: "Se préparer", vision2Title: "Pour un vrai objectif", vision2Desc: "Que vous visiez des études, un emploi ou une installation en Allemagne — Yema adapte votre apprentissage à votre projet de vie.",
    vision3Label: "S'intégrer", vision3Title: "La langue, la culture, le quotidien", vision3Desc: "Comprendre l'Allemagne au-delà des mots : les usages, les codes culturels, les situations de la vie réelle.",
    germanyTitle: "Pourquoi l'Allemagne ?",
    germanyText: "L'Allemagne reste l'une des destinations les plus accessibles pour les Camerounais souhaitant étudier ou travailler en Europe. La langue est la clé.",
    germany1: "Plus de 400 universités, dont beaucoup proposent des cursus gratuits ou peu coûteux",
    germany2: "Des opportunités professionnelles dans l'ingénierie, la santé et l'informatique",
    germany3: "Une diaspora camerounaise établie, facilitant l'intégration",
    germany4: "Niveau B1 minimum requis pour la majorité des démarches universitaires et professionnelles",
    testimonialsTitle: "Ce que Yema veut résoudre",
    testimonial1Text: "", testimonial1Role: "",
    testimonial2Text: "", testimonial2Role: "",
    testimonial3Text: "", testimonial3Role: "",
    problem1Title: "Les cours classiques ne suffisent pas",
    problem1Desc: "Les méthodes traditionnelles enseignent la grammaire, mais pas comment parler ou comprendre un Allemand dans la vraie vie.",
    problem2Title: "Les ressources coûtent cher",
    problem2Desc: "Manuels importés, cours particuliers, abonnements en devises — apprendre l'allemand reste inaccessible pour beaucoup.",
    problem3Title: "Personne ne prépare au contexte camerounais",
    problem3Desc: "Les plateformes internationales ignorent les objectifs réels : études en Allemagne, mobilité professionnelle, regroupement familial.",
    simTitle: "Fonctionnalité phare", simHeadline: "Entraînez-vous en allemand avec l'IA",
    simDesc: "Notre assistant IA vous met en situation réelle : conversations, vocabulaire des démarches administratives, expressions du quotidien. Chaque réponse est analysée et corrigée pour vous faire progresser.",
    simCta: "Essayer gratuitement →", simConsulOnline: "Assistant IA · En ligne",
    simMsg1: "Bonjour. Pouvez-vous vous présenter ?", simMsg2: "Bonjour. Je m'appelle Paul, je viens du Cameroun.", simMsg3: "Pourquoi souhaitez-vous apprendre l'allemand ?",
    simScoreLabel: "📊 Score en temps réel", simGrammar: "Grammaire", simVocab: "Vocab", simRelevance: "Pertinence",
    simVisa1: "Vocabulaire des démarches administratives", simVisa2: "Expressions du monde du travail", simVisa3: "Vie quotidienne et intégration", simVisa4: "Études et parcours universitaire", simVisa5: "Culture et codes sociaux allemands",
    centerTitle: "Vous êtes un centre de langues ou un enseignant ?",
    centerDesc: "Yema propose une solution B2B pour les instituts et les enseignants indépendants. Tableau de bord centralisé, suivi des apprenants, facturation Mobile Money intégrée.",
    centerFeature1: "Dashboard enseignant avec suivi élèves", centerFeature2: "Analytics progression en temps réel", centerFeature3: "Pratique orale IA intégrée", centerFeature4: "Accès mobile pour tous les élèves", centerFeature5: "Facturation Mobile Money simplifiée",
    centerCta: "Demander une démo →", centerOnDemand: "Sur devis", centerPerMonth: "/mois",
    faqTitle: "Questions fréquentes",
    faq1Q: "Comment fonctionne l'entraînement oral avec l'IA ?", faq1A: "Vous conversez avec notre assistant IA en allemand. Il analyse votre réponse, signale les erreurs de grammaire et de vocabulaire, et vous suggère des formulations plus naturelles — en temps réel.",
    faq2Q: "Le plan gratuit est-il vraiment gratuit ?", faq2A: "Oui, totalement gratuit. Pas de carte bancaire requise. Accès complet au niveau A1 avec 3 leçons par jour.",
    faq3Q: "Yema prépare-t-il aux examens de langue allemande ?", faq3A: "Yema développe vos compétences orales et écrites en allemand, alignées sur le Cadre CECRL (A1-C1). Nous sommes une plateforme indépendante. Pour les certifications officielles, renseignez-vous auprès des organismes accrédités dans votre pays.",
    faq4Q: "Puis-je rejoindre la classe d'un enseignant ?", faq4A: "Oui. Entrez le code de classe de votre enseignant lors de l'inscription ou depuis votre tableau de bord. Votre enseignant validera votre accès.",
    faq5Q: "Y a-t-il une application mobile ?", faq5A: "La plateforme est entièrement optimisée pour mobile via le navigateur. Une application native est en cours de développement.",
    faq6Q: "Comment devenir centre partenaire ?", faq6A: "Contactez-nous via WhatsApp ou email. Nous proposons un accès découverte gratuit pour tester la solution avec votre équipe avant tout engagement.",
    ctaFinalTitle: "Apprendre. Se préparer.", ctaFinalSub: "S'intégrer.",
    ctaFinalDesc: "Pas de carte bancaire. Pas d'engagement. Accès immédiat au niveau A1 complet.",
    ctaFinalBtn: "Rejoins la bêta", ctaFinalSocial: "Sans carte bancaire · A1 gratuit · CECRL A1→C1",
    ctaFinalAppLabel: "Bientôt disponible sur", ctaFinalCities: "Disponible au Cameroun — bientôt en Afrique centrale",
    footerMade: "Construit au Cameroun, pour l'Afrique", footerLegal: "Mentions légales", footerTerms: "CGU", footerPrivacy: "Confidentialité", footerContact: "Contact",
  },
  en: {
    badge: "German Learning Platform",
    title: "Learn German.",
    titleAccent: "Land your future.",
    subtitle: "The German learning platform built for Cameroon. From A1 to C1 — with AI conversation practice, native audio, and real-world language prep.",
    subtitle2: "No fuss. No commitment. Just real progress.",
    ctaPrimary: "Start for free",
    ctaSecondary: "Test my level",
    ctaMicro: "Full A1 access · No credit card",
    connexion: "Log in",
    getStarted: "Get started",
    navFeatures: "Features",
    navLevels: "Levels",
    navPricing: "Pricing",
    navCenters: "Centers",
    b2bLabel: "B2B Solution",
    statsUsers: "Learners",
    statsLevels: "CEFR Levels",
    statsSuccess: "Success rate",
    statsCenters: "Partner centers",
    stat1Value: "Beta", stat1Label: "Open access",
    stat2Value: "A1", stat2Label: "Available level",
    stat3Value: "FR & EN", stat3Label: "Interface languages",
    stat4Value: "✦", stat4Label: "Built in Cameroon",
    featuresTitle: "Everything you need",
    featuresSubtitle: "From speaking practice to language prep — all in one place.",
    feature1Title: "Guided speaking practice", feature1Desc: "Have real conversations with an AI in German. Progress at your own pace — no pressure, no judgment.", feature1Badge: "AI",
    feature2Title: "Native audio dialogues", feature2Desc: "Authentic German voices. Calibrated for every level, A1 through C1.",
    feature3Title: "Real-time voice correction", feature3Desc: "Speak German out loud and get instant AI feedback on your pronunciation and fluency.", feature3Badge: "AI",
    feature4Title: "AI writing coach", feature4Desc: "Write in German and receive detailed corrections on grammar, vocabulary, and style — powered by Gemini.", feature4Badge: "Gemini",
    feature5Title: "Quizzes that adapt to you", feature5Desc: "Every quiz adjusts to your level automatically. Each session targets your actual gaps.", feature5Badge: "Adaptive",
    feature6Title: "Live classes", feature6Desc: "Join a teacher's class or create your own study group. Everyone's progress is tracked in real time.", feature6Badge: "Soon",
    feature7Title: "Language center solution", feature7Desc: "A complete management platform for language schools — teachers, students, classes, and analytics in one place.", feature7Badge: "B2B",
    feature8Title: "Track your 5 skills", feature8Desc: "Measure your growth across Reading, Listening, Speaking, Writing, and Grammar.", feature8Badge: "Insights",
    levelsTitle: "CEFR-aligned curriculum (A1 to C1)",
    levelsSubtitle: "Original content aligned with the Common European Framework of Reference for Languages.",
    available: "Available", locked: "🔒 Premium", modules: "modules",
    level1Name: "Beginner", level1Desc: "Greetings, family, numbers, daily routine",
    level2Name: "Elementary", level2Desc: "Urban life, media, health, travel",
    level3Name: "Intermediate", level3Desc: "Work, society, culture, environment",
    level4Name: "Advanced", level4Desc: "Science, economics, media, history",
    level5Name: "Mastery", level5Desc: "Philosophy, literature, international career",
    visionTitle: "One platform. Three ambitions.",
    visionSubtitle: "Yema isn't a flashcard app. It's a complete path to German fluency.",
    vision1Label: "Learn", vision1Title: "Solid foundations", vision1Desc: "A structured curriculum from A1 to C1, with speaking, writing, and audio exercises to build real skills.",
    vision2Label: "Prepare", vision2Title: "For a real goal", vision2Desc: "Whether you're aiming for studies, a job, or a life in Germany — Yema tailors your learning to your life project.",
    vision3Label: "Integrate", vision3Title: "Language, culture, daily life", vision3Desc: "Understanding Germany beyond words: social codes, cultural norms, and real-life situations.",
    germanyTitle: "Why Germany?",
    germanyText: "Germany remains one of the most accessible destinations for Cameroonians seeking to study or work in Europe. Language is the key.",
    germany1: "400+ universities, many offering free or low-cost programs",
    germany2: "Professional opportunities in engineering, healthcare, and tech",
    germany3: "An established Cameroonian diaspora easing integration",
    germany4: "B1 level minimum for most academic and professional applications",
    testimonialsTitle: "What Yema wants to solve",
    testimonial1Text: "", testimonial1Role: "",
    testimonial2Text: "", testimonial2Role: "",
    testimonial3Text: "", testimonial3Role: "",
    problem1Title: "Traditional courses aren't enough",
    problem1Desc: "Standard methods teach grammar but not how to actually speak or understand a German in real life.",
    problem2Title: "Resources are expensive",
    problem2Desc: "Imported textbooks, private lessons, foreign-currency subscriptions — learning German remains out of reach for many.",
    problem3Title: "No one prepares for the Cameroonian context",
    problem3Desc: "International platforms ignore real goals: studies in Germany, professional mobility, family reunification.",
    simTitle: "Our signature feature", simHeadline: "Practice German with AI",
    simDesc: "Our AI assistant puts you in real situations: conversations, administrative vocabulary, daily-life expressions. Every answer is analyzed and corrected to help you improve.",
    simCta: "Try it free →", simConsulOnline: "AI Assistant · Online",
    simMsg1: "Hello! Could you introduce yourself?", simMsg2: "Hello. My name is Paul, I'm from Cameroon.", simMsg3: "Why do you want to learn German?",
    simScoreLabel: "📊 Live score", simGrammar: "Grammar", simVocab: "Vocabulary", simRelevance: "Relevance",
    simVisa1: "Administrative vocabulary", simVisa2: "Professional expressions", simVisa3: "Daily life and integration", simVisa4: "Studies and university path", simVisa5: "German culture and social codes",
    centerTitle: "Managing a language center or teaching independently?",
    centerDesc: "Yema offers a B2B solution for language schools and independent teachers. Centralized dashboard, learner tracking, and integrated Mobile Money billing.",
    centerFeature1: "Per-student progress tracking", centerFeature2: "Real-time class analytics", centerFeature3: "Integrated AI speaking practice", centerFeature4: "Mobile-friendly for all students", centerFeature5: "Mobile Money billing, simplified",
    centerCta: "Request a demo →", centerOnDemand: "On request", centerPerMonth: "/month",
    faqTitle: "Common questions",
    faq1Q: "How does AI speaking practice work?", faq1A: "You have a live conversation with our AI assistant in German. It analyzes your response, flags grammar and vocabulary errors, and suggests more natural phrasing — in real time.",
    faq2Q: "Is the free plan actually free?", faq2A: "Yes — completely free. No credit card required. Full access to A1 with 3 lessons per day.",
    faq3Q: "Does Yema prepare you for German language exams?", faq3A: "Yema develops your spoken and written German skills, aligned with the CEFR framework (A1-C1). We are an independent platform. For official certifications, contact accredited examination bodies in your country.",
    faq4Q: "Can I join a teacher's class?", faq4A: "Absolutely. Enter your teacher's class code when you sign up or from your dashboard. Your teacher approves your enrollment.",
    faq5Q: "Is there a mobile app?", faq5A: "The platform works great on mobile (iOS and Android) through your browser. A native app is on the roadmap.",
    faq6Q: "How do I become a partner center?", faq6A: "Reach out on WhatsApp or email. We offer a free discovery period to try the solution with your team — no commitment.",
    ctaFinalTitle: "Learn German.", ctaFinalSub: "Build your future.",
    ctaFinalDesc: "No credit card. No commitment. Full access to A1 — right now.",
    ctaFinalBtn: "Join the beta", ctaFinalSocial: "No credit card · Free A1 access · CEFR A1→C1",
    ctaFinalAppLabel: "Coming soon on", ctaFinalCities: "Available across Cameroon and Central Africa",
    footerMade: "Built in Cameroon", footerLegal: "Legal", footerTerms: "Terms", footerPrivacy: "Privacy", footerContact: "Contact",
  },
}

// ─── Navigation ────────────────────────────────────────────────────────────────
const nav = {
  fr: {
    home: "Accueil", courses: "Cours", myClasses: "Mes Classes", discover: "Découvrir",
    simulator: "Simulateur IA", progress: "Progression", settings: "Paramètres",
    overview: "Vue d'ensemble", students: "Élèves", assignments: "Devoirs",
    generateCourse: "Générer cours", stats: "Statistiques", teachers: "Enseignants",
    billing: "Facturation", users: "Utilisateurs", centers: "Centres",
    login: "Se connecter", register: "Commencer gratuitement", logout: "Se déconnecter",
  },
  en: {
    home: "Home", courses: "Courses", myClasses: "My Classes", discover: "Explore",
    simulator: "Embassy Simulator", progress: "My Progress", settings: "Settings",
    overview: "Overview", students: "Students", assignments: "Assignments",
    generateCourse: "Generate Course", stats: "Statistics", teachers: "Teachers",
    billing: "Billing", users: "Users", centers: "Language Centers",
    login: "Log in", register: "Get started free", logout: "Log out",
  },
}

// ─── Student dashboard ─────────────────────────────────────────────────────────
const dashboard = {
  fr: {
    xpLabel: "Points XP", lessonsLabel: "Leçons", scoreLabel: "Score moy.", streakLabel: "Jours streak",
    badgesLabel: "Badges", levelLabel: "Niveau actuel",
    launchSim: "Lancer une simulation", simulatorsTitle: "Simulateurs d'ambassade", simulatorsDesc: "Conversations IA avec Herr Bauer",
    skills: "Compétences", detailedProgress: "Progression détaillée", noSkills: "Commencez votre première leçon pour voir vos compétences !",
    joinClassTitle: "🏫 Vous avez un code classe ?", joinClassLabel: "Rejoindre une classe", joinClassDesc: "Entrez le code fourni par votre enseignant pour rejoindre sa classe.",
    joinCodePlaceholder: "DEUTSCH-A1-XXXX", pendingTitle: "Inscription en attente", pendingDesc: "Votre enseignant doit valider votre demande.",
    rewardsLabel: "Récompenses", badgesTitle: "Badges obtenus", noBadge: "Complétez votre première leçon pour gagner un badge",
    communityLabel: "Communauté", discoverLabel: "🔍 Découvrir",
    grammar: "Grammaire", vocabulary: "Vocabulaire", pronunciation: "Prononciation", comprehension: "Compréhension",
    classesAvailable: "Classes disponibles", classesJoin: "Rejoindre une classe", groupsLabel: "Groupes d'élèves",
    studyGroup: "Étudier en groupe", findPartner: "Trouver un partenaire", soloStudents: "Élèves en solo",
    loading: "Chargement...",
  },
  en: {
    xpLabel: "XP earned", lessonsLabel: "Lessons completed", scoreLabel: "Average score", streakLabel: "Day streak",
    badgesLabel: "Badges", levelLabel: "Current level",
    launchSim: "Start an embassy simulation", simulatorsTitle: "Embassy Simulator", simulatorsDesc: "AI conversations with Herr Bauer",
    skills: "Skills", detailedProgress: "Detailed progress", noSkills: "Complete a lesson to start tracking your skills here.",
    joinClassTitle: "🏫 Have a class code?", joinClassLabel: "Join a class", joinClassDesc: "Enter the code your teacher gave you to join their class.",
    joinCodePlaceholder: "DEUTSCH-A1-XXXX", pendingTitle: "Waiting for approval", pendingDesc: "Your teacher will approve your enrollment shortly.",
    rewardsLabel: "Rewards", badgesTitle: "Your badges", noBadge: "Finish your first lesson to earn your first badge.",
    communityLabel: "Community", discoverLabel: "🔍 Discover",
    grammar: "Grammar", vocabulary: "Vocabulary", pronunciation: "Pronunciation", comprehension: "Comprehension",
    classesAvailable: "Available classes", classesJoin: "Join a class", groupsLabel: "Study groups",
    studyGroup: "Study in a group", findPartner: "Find a partner", soloStudents: "Solo students",
    loading: "Loading...",
  },
}

// ─── Teacher ───────────────────────────────────────────────────────────────────
const teacher = {
  fr: {
    space: "Espace Enseignant", access: "Accès Professeur · Vérifié", role: "Enseignant · Yema",
    greeting: "Bonjour, Prof. {name} 👋", newClass: "+ Nouvelle classe", studentView: "Vue élève",
    myTeacherCode: "Mon code enseignant", myClassCodes: "Codes de mes classes",
    shareCodeStudents: "Partagez ce code aux élèves pour qu'ils vous trouvent sur Découvrir",
    shareClassCode: "Partagez votre code de classe pour inviter des élèves",
    copied: "✓ Copié", copy: "Copier",
    statStudentsLabel: "Élèves actifs cette semaine", statAvgLabel: "Moyenne de la classe", statAvgSub: "Sur 10",
    statAssignmentsLabel: "Devoirs à corriger", statAssignmentsSub: "Dont 2 en retard",
    statCompletionLabel: "Taux de complétion", statCompletionSub: "Modules terminés cette semaine",
    sectionClasses: "Mes Classes", sectionActivity: "Activité récente",
    activityEmpty: "L'activité récente apparaîtra ici",
    classesEmpty: "Vous n'avez pas encore de classe.", createFirstClass: "+ Créer ma première classe →",
    viewAll: "Voir tout →", progressChart: "Progression des classes — 4 semaines",
    progressEmpty: "Les données de progression apparaîtront ici dès que les élèves commenceront les leçons.",
    struggling: "⚠️ Élèves en difficulté", allGood: "Tous les élèves sont au-dessus de 50% 🎉",
    recentAssignments: "📋 Devoirs récents", assignmentsEmpty: "Créez votre premier devoir depuis la page Devoirs.",
    viewStudent: "Voir →", classStudents: "élèves", classProgress: "progression", classAvgScore: "score moyen",
    loading: "Chargement...",
  },
  en: {
    space: "Teacher Space", access: "Teacher Access · Verified", role: "Teacher · Yema",
    greeting: "Hello, Prof. {name} 👋", newClass: "+ New class", studentView: "Student view",
    myTeacherCode: "My teacher code", myClassCodes: "My class codes",
    shareCodeStudents: "Share this code with students so they can find you on Discover",
    shareClassCode: "Share your class code to invite students",
    copied: "✓ Copied", copy: "Copy",
    statStudentsLabel: "Active students this week", statAvgLabel: "Class average", statAvgSub: "Out of 10",
    statAssignmentsLabel: "Assignments to grade", statAssignmentsSub: "Including 2 late",
    statCompletionLabel: "Completion rate", statCompletionSub: "Modules completed this week",
    sectionClasses: "My Classes", sectionActivity: "Recent activity",
    activityEmpty: "Recent activity will appear here",
    classesEmpty: "You haven't created any classes yet.", createFirstClass: "+ Create your first class →",
    viewAll: "View all →", progressChart: "Class progress — last 4 weeks",
    progressEmpty: "Progress data will show up here once your students start lessons.",
    struggling: "⚠️ Students needing support", allGood: "All students are above 50% 🎉",
    recentAssignments: "📋 Recent assignments", assignmentsEmpty: "Head to the Assignments page to create your first one.",
    viewStudent: "View →", classStudents: "students", classProgress: "progress", classAvgScore: "avg score",
    loading: "Loading...",
  },
}

// ─── Center ────────────────────────────────────────────────────────────────────
const center = {
  fr: {
    portal: "Portail Centre", partnerBadge: "⭐ Centre Partenaire", verified: "✓ Vérifié",
    dashboard: "Tableau de bord", proPlan: "⭐ Plan Pro",
    registrationCode: "Code d'inscription de votre centre",
    shareCodeStudents: "Partagez ce code à vos élèves — ils le saisissent lors de leur inscription sur Yema.",
    viewStudents: "Voir les élèves →", copied: "✓ Copié !", copy: "Copier",
    statTeachers: "Enseignants actifs", statStudents: "Élèves inscrits", statClasses: "Classes actives",
    statRevenue: "Revenus du mois", statRevenueSub: "Monétisation à venir",
    registrationsChart: "Évolution des inscriptions", registrationsEmpty: "Les statistiques d'inscription apparaîtront ici au fur et à mesure.",
    alerts: "Alertes & Notifications", noAlerts: "Aucune alerte pour le moment",
    teachersList: "Enseignants du centre", noTeachers: "Aucun enseignant associé au centre pour l'instant.",
    viewAll: "Voir tout →", studentPortal: "← Portail élève", directorRole: "Directeur · CENTER_MANAGER",
    tableTeacher: "Enseignant", tableSpecialty: "Spécialité", tableClasses: "Classes",
    tableStudents: "Élèves", tableAvgScore: "Score moy.", tableStatus: "Statut",
    overview: "Vue d'ensemble", loading: "Chargement...",
  },
  en: {
    portal: "Center Portal", partnerBadge: "⭐ Partner Center", verified: "✓ Verified",
    dashboard: "Dashboard", proPlan: "⭐ Pro Plan",
    registrationCode: "Your center registration code",
    shareCodeStudents: "Share this code with your students — they enter it during registration on Yema.",
    viewStudents: "View students →", copied: "✓ Copied!", copy: "Copy",
    statTeachers: "Active teachers", statStudents: "Enrolled students", statClasses: "Active classes",
    statRevenue: "Monthly revenue", statRevenueSub: "Payments launching soon",
    registrationsChart: "Enrollment trends", registrationsEmpty: "Enrollment stats will appear here as your center grows.",
    alerts: "Alerts & Notifications", noAlerts: "No alerts right now",
    teachersList: "Center teachers", noTeachers: "No teachers added yet.",
    viewAll: "View all →", studentPortal: "← Student portal", directorRole: "Director · Center Manager",
    tableTeacher: "Teacher", tableSpecialty: "Specialty", tableClasses: "Classes",
    tableStudents: "Students", tableAvgScore: "Avg score", tableStatus: "Status",
    overview: "Overview", loading: "Loading...",
  },
}

// ─── Admin ─────────────────────────────────────────────────────────────────────
const admin = {
  fr: {
    navOverview: "Vue d'ensemble", navUsers: "Utilisateurs", navCourses: "Cours & Contenu",
    navValidations: "Validations", navSystem: "Système", backToSite: "← Retour au site",
    greeting: "👋 Bonjour, Admin",
    kpiTotal: "Total utilisateurs", kpiStudents: "Élèves actifs", kpiTeachers: "Enseignants",
    kpiCenters: "Centres", kpiSessions: "Sessions aujourd'hui",
    kpiTotalSub: "ce mois", kpiStudentsSub: "inscrits", kpiTeachersSub: "vérifiés",
    kpiCentersSub: "partenaires", kpiSessionsSub: "moy.",
    chartMonthly: "📈 Inscriptions mensuelles", chartSeriesUsers: "Utilisateurs",
    chartLevels: "🎯 Niveaux CEFR", chartWeekly: "📅 Activité cette semaine",
    chartSeriesStudents: "Élèves", chartSeriesTeachers: "Enseignants", chartSeriesCenters: "Centres",
    recentActivity: "🔔 Activité récente", recentActivityEmpty: "L'activité récente apparaîtra ici",
    topCities: "🌍 Top villes", topCitiesEmpty: "Données géographiques — bientôt disponibles",
    usersTitle: "👥 Utilisateurs", searchPlaceholder: "Rechercher un utilisateur...",
    filterAll: "Tous les rôles", filterStudents: "Élèves", filterTeachers: "Enseignants", filterCenters: "Centres",
    quickStatNew: "Nouveaux aujourd'hui",
    tableUser: "Utilisateur", tableRole: "Rôle", tableLevel: "Niveau", tableCity: "Ville",
    tableDate: "Inscription", tableStatus: "Statut", tableActions: "Actions",
    statusActive: "Actif", statusPending: "En attente",
    roleLabelStudent: "Élève", roleLabelTeacher: "Enseignant", roleLabelCenter: "Centre", roleLabelAdmin: "Admin",
    actionView: "Voir", actionEdit: "Modifier", actionBlock: "Bloquer",
    coursesTitle: "📚 Cours & Contenu", generateBtn: "✨ Générer avec Gemini",
    kpiCoursesTotal: "Cours total", kpiPublished: "Publiés", kpiDraft: "Brouillons", kpiModules: "Modules total",
    levelGenerated: "Généré par IA", levelGeneratedSuffix: "générés", generateCourseBtn: "+ Générer",
    validationsTitle: "✅ Validations en attente", noValidations: "✅ Aucune validation en attente",
    validTypeCenter: "Centre", validTypeTeacher: "Enseignant",
    validateBtn: "✅ Valider", rejectBtn: "❌ Refuser",
    systemTitle: "⚙️ Système", apisTitle: "🔌 APIs configurées",
    apiStatusActive: "Actif", apiStatusPending: "À configurer",
    pagesTitle: "📄 Pages de la plateforme", envTitle: "🔐 Variables d'environnement",
    pageDashboardStudent: "Dashboard élève", pageCourses: "Cours", pageSimulator: "Simulateur IA",
    pageDiscover: "Découvrir", pageProgress: "Progression",
    pageDashboardTeacher: "Dashboard enseignant", pageDashboardCenter: "Dashboard centre",
    pageQuiz: "Quiz adaptatif", pageVideos: "Vidéos Remotion", pagePricing: "Tarifs",
  },
  en: {
    navOverview: "Overview", navUsers: "Users", navCourses: "Courses & Content",
    navValidations: "Validations", navSystem: "System", backToSite: "← Back to site",
    greeting: "👋 Hello, Admin",
    kpiTotal: "Total users", kpiStudents: "Active students", kpiTeachers: "Teachers",
    kpiCenters: "Centers", kpiSessions: "Sessions today",
    kpiTotalSub: "this month", kpiStudentsSub: "enrolled", kpiTeachersSub: "verified",
    kpiCentersSub: "partners", kpiSessionsSub: "avg.",
    chartMonthly: "📈 Monthly registrations", chartSeriesUsers: "Users",
    chartLevels: "🎯 CEFR Levels", chartWeekly: "📅 Activity this week",
    chartSeriesStudents: "Students", chartSeriesTeachers: "Teachers", chartSeriesCenters: "Centers",
    recentActivity: "🔔 Recent activity", recentActivityEmpty: "Recent activity will appear here",
    topCities: "🌍 Top cities", topCitiesEmpty: "Geographic data — coming soon",
    usersTitle: "👥 Users", searchPlaceholder: "Search a user...",
    filterAll: "All roles", filterStudents: "Students", filterTeachers: "Teachers", filterCenters: "Centers",
    quickStatNew: "New today",
    tableUser: "User", tableRole: "Role", tableLevel: "Level", tableCity: "City",
    tableDate: "Registered", tableStatus: "Status", tableActions: "Actions",
    statusActive: "Active", statusPending: "Pending",
    roleLabelStudent: "Student", roleLabelTeacher: "Teacher", roleLabelCenter: "Center", roleLabelAdmin: "Admin",
    actionView: "View", actionEdit: "Edit", actionBlock: "Block",
    coursesTitle: "📚 Courses & Content", generateBtn: "✨ Generate with Gemini",
    kpiCoursesTotal: "Total courses", kpiPublished: "Published", kpiDraft: "Drafts", kpiModules: "Total modules",
    levelGenerated: "AI generated", levelGeneratedSuffix: "generated", generateCourseBtn: "+ Generate",
    validationsTitle: "✅ Pending validations", noValidations: "✅ No pending validations",
    validTypeCenter: "Center", validTypeTeacher: "Teacher",
    validateBtn: "✅ Approve", rejectBtn: "❌ Reject",
    systemTitle: "⚙️ System", apisTitle: "🔌 Configured APIs",
    apiStatusActive: "Active", apiStatusPending: "Not configured",
    pagesTitle: "📄 Platform pages", envTitle: "🔐 Environment variables",
    pageDashboardStudent: "Student dashboard", pageCourses: "Courses", pageSimulator: "AI Simulator",
    pageDiscover: "Discover", pageProgress: "Progress",
    pageDashboardTeacher: "Teacher dashboard", pageDashboardCenter: "Center dashboard",
    pageQuiz: "Adaptive quiz", pageVideos: "Remotion videos", pagePricing: "Pricing",
  },
}

// ─── Common ────────────────────────────────────────────────────────────────────
const common = {
  fr: {
    loading: "Chargement...", error: "Une erreur est survenue", retry: "Réessayer",
    save: "Sauvegarder", cancel: "Annuler", confirm: "Confirmer", back: "Retour",
    next: "Suivant", finish: "Terminer", yes: "Oui", no: "Non", or: "ou",
    search: "Rechercher", filter: "Filtrer", viewAll: "Voir tout", comingSoon: "Bientôt disponible",
    free: "Gratuit", premium: "Premium", new: "Nouveau", beta: "Bêta", active: "Actif", inactive: "Inactif",
  },
  en: {
    loading: "Loading...", error: "An error occurred", retry: "Retry",
    save: "Save", cancel: "Cancel", confirm: "Confirm", back: "Back",
    next: "Next", finish: "Done", yes: "Yes", no: "No", or: "or",
    search: "Search", filter: "Filter", viewAll: "View all", comingSoon: "Coming soon",
    free: "Free", premium: "Premium", new: "New", beta: "Beta", active: "Active", inactive: "Inactive",
  },
}

// ─── Auth ──────────────────────────────────────────────────────────────────────
const auth = {
  fr: {
    loginTitle: "Bon retour !", loginSubtitle: "Continuez votre apprentissage",
    email: "Adresse email", emailPlaceholder: "toi@example.com",
    password: "Mot de passe", passwordPlaceholder: "••••••••",
    loginBtn: "Se connecter", loginLoading: "Connexion...",
    noAccount: "Pas encore de compte ?", subscribe: "S'inscrire",
    chooseRole: "Je suis...", chooseRoleHint: "Qui êtes-vous ? Choisissez votre profil 👇",
    roleStudent: "Apprenant", roleStudentDesc: "Je veux apprendre l'allemand",
    roleTeacher: "Enseignant", roleTeacherDesc: "J'enseigne l'allemand",
    roleCenter: "Centre de langues", roleCenterDesc: "Je représente un centre",
    registerTitle: "Créez votre compte", registerSubtitle: "Commence ton voyage linguistique",
    registerBtn: "Créer mon compte", registerLoading: "Création du compte...",
    fullName: "Nom complet", fullNamePlaceholder: "Paul Nkengue", passwordMin: "Min. 6 caractères",
    passwordError: "Le mot de passe doit contenir au moins 6 caractères.",
    hasAccount: "Déjà un compte ?", signIn: "Se connecter", changeRole: "← Changer",
    confirmTitle: "Vérifie ta boîte mail ✉️", confirmSent: "Un lien de confirmation a été envoyé à",
    confirmClick: "Clique sur le lien pour activer ton compte et accéder à l'espace",
    backToLogin: "Retour à la connexion", createAccount: "Créer un compte",
    errorInvalid: "Email ou mot de passe incorrect.",
  },
  en: {
    loginTitle: "Welcome back", loginSubtitle: "Continue your learning journey",
    email: "Email address", emailPlaceholder: "you@example.com",
    password: "Password", passwordPlaceholder: "••••••••",
    loginBtn: "Log in", loginLoading: "Signing in...",
    noAccount: "New here?", subscribe: "Create an account",
    chooseRole: "Who are you?", chooseRoleHint: "Pick the option that describes you",
    roleStudent: "I'm a learner", roleStudentDesc: "Learning German, A1 to C1",
    roleTeacher: "I'm a teacher", roleTeacherDesc: "I teach German and manage classes",
    roleCenter: "I manage a center", roleCenterDesc: "Running a language school or institute",
    registerTitle: "Create your account", registerSubtitle: "Join the Yema community",
    registerBtn: "Create account", registerLoading: "Creating your account...",
    fullName: "Full name", fullNamePlaceholder: "Paul Nkengue", passwordMin: "At least 6 characters",
    passwordError: "Your password must be at least 6 characters.",
    hasAccount: "Already have an account?", signIn: "Log in", changeRole: "← Back",
    confirmTitle: "Check your inbox ✉️", confirmSent: "We sent a confirmation link to",
    confirmClick: "Click the link to activate your account and get started.",
    backToLogin: "Back to login", createAccount: "Create account",
    errorInvalid: "Wrong email or password. Please try again.",
  },
}

// ─── Layout (sidebar) ──────────────────────────────────────────────────────────
const layout = {
  fr: {
    searchPlaceholder: "Rechercher un cours, un scénario...", goethe: "CEFR · A1 → C1",
    userFallback: "Utilisateur", studentBadge: "✅ Élève inscrit",
    pendingBadge: "⏳ Validation en cours", groupLeader: "👥 Chef de groupe",
    solo: "Solo", levelPrefix: "Niveau",
  },
  en: {
    searchPlaceholder: "Search...", goethe: "CEFR · A1 → C1",
    userFallback: "User", studentBadge: "✅ Enrolled student",
    pendingBadge: "⏳ Pending validation", groupLeader: "👥 Group leader",
    solo: "Solo", levelPrefix: "Level",
  },
}

// ─── All text ──────────────────────────────────────────────────────────────────
export const TEXT = {
  fr: { landing: landing.fr, nav: nav.fr, dashboard: dashboard.fr, teacher: teacher.fr, center: center.fr, admin: admin.fr, common: common.fr, auth: auth.fr, layout: layout.fr },
  en: { landing: landing.en, nav: nav.en, dashboard: dashboard.en, teacher: teacher.en, center: center.en, admin: admin.en, common: common.en, auth: auth.en, layout: layout.en },
}

export type Locale = "fr" | "en"
export type TextBundle = typeof TEXT.fr

// ─── Hook ──────────────────────────────────────────────────────────────────────
// Reads locale directly from the URL path — no next-intl context needed.
// Works on every navigation: /fr/... = French, /en/... = English.
export function useT(): TextBundle {
  const pathname = usePathname()
  const locale: Locale = pathname.startsWith("/en") ? "en" : "fr"
  return TEXT[locale]
}
